### ISSUE TITLE
[Suggestion] Using more than one heart crystal at a time

### ISSUE THREAD

**Issue by GreatestFool** [SilentChaos512/ScalingHealth#101]
It would be incredibly nice to be able to use more than one crystal at a time. Like if I have a stack, and enough levels, if it was possible to hold shift while using it to use the entire stack at once, that would would be amazing.

**Comment by Zunlite** [comment]
I wouldnt want it to be shift or something though, accidentally using all heart crystals would be terrible in a multiplayer game

**Comment by GreatestFool** [comment]
Then simply have a custom keybind for it, it'd resolve any potential keybind problems at least.
