### ISSUE TITLE
*Feature Request* Always Blighted

### ISSUE THREAD

**Issue by m1jordanallen** [SilentChaos512/ScalingHealth#102]
I sure do love me some blights.  So much so, I would find it absolutely incredible if we can guarantee certain entities to be always blighted.  My friend was leisurely killing bosses in a certain mod and having just a swell day killing them.  Until one was blighted, OMG it was so amazing and perfect Id love to just make it always blighted.  Ideally a config like the blacklist, but whitelist for always blighted.

Thank you for considering :)

**Comment by m1jordanallen** [comment]
Any chance at getting a whitelist for this feature? All is a bit much. xD

**Comment by SilentChaos512** [comment]
Done, new version pending approval.
