### ISSUE TITLE
Custom Renderer and Player Health disable doesn't work

### ISSUE THREAD

**Issue by Mrannoyus** [SilentChaos512/ScalingHealth#104]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.14-96
Silent Lib Version: 1.2.2-5

### Expected behavior

We have mods already affecting the player health so we disabled the custom heart rendering and player health adjustments in the config, expecting it to disable using the heart containers and the scalinghealth command to change player health

### Actual behaviour

The custom heart rendering is still in effect and using heart containers/scaling health command does some weird things where it will lower hp but not increase it properly.

Configs attached.
[scalinghealth.zip](https://github.com/SilentChaos512/ScalingHealth/files/1969148/scalinghealth.zip)

**Comment by SilentChaos512** [comment]
For the custom heart rendering, is it just the text that is still displayed, or the custom hearts as well? I see the text, but I didn't try installing another mod that modifies health.

Heart containers are meant to still be consumable, so they can be used purely as a healing item. I don't see heart containers or the command doing anything to max health. What mod(s) do you use to modify health?

**Comment by Mrannoyus** [comment]
Oddly enough, the bugs only appeared while on a dedicated server- we have Improvable Skills 3 which has a max health skill and we also have Botania which has a ring capable of adding hearts- it was really strange where the text was still displayed and flashing colors but then it would also change our max hp back to 20 every other tick while every other tick had it going back to the other value. While in singleplayer the bugs didn't seem to appear.
