### ISSUE TITLE
hunger and saturation increasement

### ISSUE THREAD

**Issue by jiuribu** [SilentChaos512/ScalingHealth#105]
### Versions

Minecraft Version: 1.12
Scaling Health Version: latest
Silent Lib Version: latest

need same thing for hunger and saturation

huge chunk that increase max hunger
huge lemon to increase max saturation

**Comment by SilentChaos512** [comment]
I'll consider it, but feels a little off-topic. But I get that more health = more food with vanilla healing mechanics. Also, those values are not easy to change like health and attack damage. Apple Core provides a way (I think) so I could hook into that.
