### ISSUE TITLE
[Feature Request] Configurable loot tables based on difficulty.

### ISSUE THREAD

**Issue by Matakor** [SilentChaos512/ScalingHealth#106]
Would love for difficult mobs and such to have bigger and better drops, even drops that are non-standard. Would love to use this in conjunction with lootbags and megaloot.

((Imagine an extreme difficulty mob finally being killed and having it drop a bag of loot containing nether stars, or a philosophers stone from projecte, or maybe awakened draconium.))

**Comment by ejektaflex** [comment]
Our server was just thinking of the same thing. Maybe give loot tables an extra value, like lootWeight and the chance of getting that item is lootWeight * (currentDiff / maxDiff)? Similar to the formula for chance of becoming a blight.

**Comment by SilentChaos512** [comment]
Added two entity properties for now, one to check whether or not the entity is a blight, and another to check if its spawn difficulty value was in a given range. Added a wiki page with details: https://github.com/SilentChaos512/ScalingHealth/wiki/Loot-Table-Stuff.
This is in version 1.3.24, which is marked as an alpha and requires Silent Lib 2.3.17.
