### ISSUE TITLE
[Feature Request] Command to add/subtract difficulty levels

### ISSUE THREAD

**Issue by Discomanco** [SilentChaos512/ScalingHealth#107]
Trying to make Scaling Health difficulty for Enigmatica 2 Expert a little friendlier for builders, so wanted to give Difficulty based on your progression. Plan is to run a command every time you reach a certain milestole. But this progress is not linear, so simply setting the difficulty doesn't quite work out. I know there is the items, but I don't want it to be a choice to use it or not.

So I suggest a command to add/subtract difficulty, so that quest rewards could say `/scalinghealth difficulty  add 10 @p`, and have that as a reward on all the milestones.

Maybe expand a bit more on it, to re-do the difficulty command.
```
/scalinghealth difficulty set 10 @p
/scalinghealth difficulty add 10 @p
/scalinghealth difficulty sub 10 @p
```

(and just to top it off, when you press Tab to see command options, it repeats the first options indefinitely)

**Comment by SilentChaos512** [comment]
I'll work on commands for next version, hopefully I'll have a chance this weekend. And I was aware that tab completion is broken, but thanks for reminding me.

**Comment by Discomanco** [comment]
Works like a charm, and it's perfect!
Now I just need BQ3 to fix their Auto-Complete feature ¯\\\_(ツ)_/¯
