### ISSUE TITLE
Damage Type multipliers don't seem to work for mod damage types

### ISSUE THREAD

**Issue by Boolyman** [SilentChaos512/ScalingHealth#108]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.2.15 98
Silent Lib Version: 2.2.18 100

### Expected behavior

- I expect "thrown" damage to deal more damage to the player.

### Actual behaviour

- Still does the same damage whether the multiplier is set higher or not.

### Steps to reproduce the problem

1. Spawn Clink from lycanites mob while debug mode is on.  Note that damage does 3.5 hearts with no armor, and damage type is "thrown."
2. Close game, add "thrown" damage type to Scaling Health config, with 4.0 multiplier
3. Reload game, respawn clink, notice that damage is still at 3.5 hearts, even if you use command to increase Scaling Health difficulty.
4. Weep tears and run to github to place issue tracker.

**Comment by Boolyman** [comment]
After testing vanilla Fire and Wither damage, the multiplier doesnt seem to increase that damage type either.  

This is what the log looks like for Fire damage.  Its the same for the other types I have adjusted as well. And they all do the same damage before I scale them and after.

[14:14:34] [Server thread/INFO]: Player damage: type=wither, scale=2.0, affected=0.0, change=0.0, original=1.0, new=1.0
[14:14:36] [Server thread/INFO]: Player damage: type=wither, scale=2.0, affected=0.0, change=0.0, original=1.0, new=1.0
[14:14:38] [Server thread/INFO]: Player damage: type=wither, scale=2.0, affected=0.0, change=0.0, original=1.0, new=1.0



Can you explain how S:"Scaling Mode"=MAX_HEALTH effects the damage.  Im not fully understanding it, and maybe thats why damage isnt happening properly.  What are the other options for that config?

**Comment by SilentChaos512** [comment]
I added a section to the CurseForge page, search for "Damage Scaling". And I recommend using the in-game config GUI if possible, it allows you to cycle through the modes by clicking a button. I thought the config would contain the valid mode names in the config, usually it does for that kind of option. They are MAX_HEALTH, PLAYER_DIFFICULTY, and AREA_DIFFICULTY.

**Comment by Boolyman** [comment]
Ok thanks, I think I got it working.
