### ISSUE TITLE
Scaling attack Does not work for all mobs

### ISSUE THREAD

**Issue by Eowomir7** [SilentChaos512/ScalingHealth#109]
mod version 1.3.15-98
forge version -2655

tested this for 2 hours with mob spawners 
all mobs get the damage bonus except skeletons, witches, ghasts, and blazes, i think it's because they throw items instead of using physical attacks.

**Comment by SilentChaos512** [comment]
Right, the normal attack damage modifier usually doesn't work for projectiles, only melee-style attacks. Slimes also ignore the modifier. I'm pretty sure I can fix skeletons. I'll have to look into the others, but it's probably doable.

**Comment by Eowomir7** [comment]
i noticed that the new damage scaling config you created in .16 version seems to affect all mob damage types with the 'general' option including all outside damage. it was stacking with the mob damage modifier. With MAX_HP scaling mode and 1 for 1 i was getting zombies to one shot me with 3000hp and fully enchanted diamond gear with bonuses from other mods that made my armor value about 10x normal. lol. consider using this modifier for other mob damage sources(arrows, thrown potions, blaze fire etc) instead of doing a full mob damage section. just an idea. might save you some work.
