### ISSUE TITLE
Request - Can you make a mod called "Growing Hunger"

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/ScalingHealth#11]
Players should be able to increase their apatite after eating more and their apatite should shrink if they forget to eat often. It should act similar to Scaling health except it could have a basic function of auto changing if they often try to over eat they should get nauseous and Zombie flesh will give players endless hunger where they can eat as much as they can and it affects hunger either positively or negatively. Call the buff Hunger X if they get bite by a zombie the have a chance at being stuck with hunger X which hopefully some of my players will die from ;) I do realize now that eventually I might have you make a stamina mod that is separate function from hunger or health but I need to really think about that something like "Athletic Enthusiasm"

**Comment by SilentChaos512** [comment]
Sorry, I don't want to make any more mods now. Between a full-time job and 8 actively-maintained mods, I've got my hands full. I'm also trying to slowly move away from modding Minecraft. I don't plan on quitting anytime soon, but there are other projects I would like to be working on.

**Comment by P3rf3ctXZer0** [comment]
thank you so much for your help however :)
