### ISSUE TITLE
[Commands bug] getting difficulty for others

### ISSUE THREAD

**Issue by Discomanco** [SilentChaos512/ScalingHealth#111]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.6.3.17
Silent Lib Version: 2.3.1-107
Can't even check if an update is out, because Twitch Client is being twitchy, and I'm too lazy to go look it up on Curseforge. Sorry, not sorry?

### Expected behavior

- `/scalinghealth difficulty get [other player]` should get the difficulty for said player

### Actual behaviour

- `/scalinghealth difficulty get [other player]` gets your own difficulty
https://i.gyazo.com/f869306eb9d3f5a181945e0c330e5f13.mp4

### Steps to reproduce the problem

1. Be on Multiplayer
2. Try to Get the difficulty of someone else
3. ...
4. Not Profit

**Comment by SilentChaos512** [comment]
Do the other sub-commands work correctly? For example, can you set another player's difficulty?

**Comment by Discomanco** [comment]
Add, Set and Sub works just fine. It's only Get that's weird

**Comment by SilentChaos512** [comment]
OK, thanks for checking. I think I know what I'm doing wrong there.

**Comment by SilentChaos512** [comment]
Done, new version pending approval.
