### ISSUE TITLE
[Feature Request] negative value for stand still multiplier

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#112]
I'm trying to set up a basic system where difficulty ramps up in the area around where a player builds a base, rather than around the player themselves. 

My solution is to use fake players as indicators of base building. Conceptually I'm attempting positive difficulty growth while standing still, and negative difficultly while moving. 

ex. Difficulty per second: -1, Mult for standing still: -1,
-1 x -1 = +1 difficulty growth while standing still, -1 "growth" while moving. 

Real players will move enough to make their difficulty stat negligible, however, fake players can't move and will always be increasing the area difficulty. I can't do this, however, because the range of the standing still mult is only 0-100.

**Comment by SilentChaos512** [comment]
Done, new version pending approval.
