### ISSUE TITLE
[Suggestion] Serperate Options for Toggling Custom Heart Rendering and Health Text Rendering

### ISSUE THREAD

**Issue by Ghostrider231** [SilentChaos512/ScalingHealth#113]
1.3.15-98

Is there a way to have the health text and rows enabled without the heart rendering? For Example, I'd like to have 10x or 200/200 but not the heart rendering because another mod is already taking care of the heart rendering. So I don't want two mods overriding and fighting over each other on the heart gui. 
**From what I've recalled, older versions let me do this by disabling custom heart rendering but left me with a health text and row.**

Because right now, Custom Heart Rendering seems to affect both Health text and Heart Rendering. So it's either all or nothing atm.

One mod that I know that adds custom heart rendering is Mantle. Which is funny enough, doesn't even have an option to disable it's heart rendering.

**Comment by SilentChaos512** [comment]
Done, new version pending approval.
