### ISSUE TITLE
Incompatibility Between Scaling Health and Extra Utilities 2 Deep Dark Dimension

### ISSUE THREAD

**Issue by ElasticKnife** [SilentChaos512/ScalingHealth#114]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.16
Silent Lib Version: 2.3.1

### Expected behavior

- Mobs in Extra Utilities 2 Deep Dark dimension would take damage relative to damage source

### Actual behaviour

- Mobs in Extra Utilities Deep Dark dimension appear to take no damage and are therefore unkillable

### Steps to reproduce the problem

1. Have Extra Utilities 2 and Scaling Health (along with Silent Lib dependency) installed on an instance
2. Travel to Extra Utilities 2 Deep Dark dimension
3. Attempt to damage mob
4. Mob is immune to all damage sources

### Notes
Just as a guess, this may have something to do with the Deep Dark setting spawned mob health to double the standard amount.

**Comment by SilentChaos512** [comment]
Seems to be functioning normally. Do you have max difficulty set to zero? Any other config changes if not?

**Comment by ElasticKnife** [comment]
Maximum difficulty is default, value of 250.  I do have quite a few different configs tweaked.  I'll attach the config pasted into a text file if you're interested in taking a look:
[main.txt](https://github.com/SilentChaos512/ScalingHealth/files/2113431/main.txt)

**Comment by SilentChaos512** [comment]
Still seems normal with your config file. Mob health looks okay. If done right, there's no practical limit to how many health multipliers you can add. Mobs take damage and can be killed. My best guess is some other mod is at fault.
