### ISSUE TITLE
[1.12.2 - Suggestion]: Custom Absorption Hearts Rendering.

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/ScalingHealth#115]
While I'm sure by normal means you won't ever go above 10 Absorption Hearts unless you use a mod or something but I figure maybe there could be a Custom Render for the Absorption Hearts, much like how the Custom Hearts Render works.

Why I am asking is... well... a mod called "Unnatural Absorption" caught my eye today which appears be the same as "Natural Absorption" only the Unnatural one is for Minecraft versions 1.11.2 & 1.12.2.

What that mod does is make it so the player can start with Absorption Hearts which is configurable, if you take damage the Absorption hearts go first, then it's your health but there's a twist... if you avoid taking damage... the Absorption Hearts will regen overtime. You can gain more Absorption Hearts either via the config, enchantments and I think it works alongside the Potion Effect as well.

It's just odd seeing my health overlay'd while Absorption Hearts are stacked via rows.

Just to show an example... a rough example.
![](https://cdn.discordapp.com/attachments/377171551155650560/455299368514224138/absorbheartrenderidea.PNG)
Since the potion icon shows a heart with a gold outline on it I figure I give it a go to see how it would look alongside the regular health with some of the custom render colors while it's based off the potion icon.

**Comment by SilentChaos512** [comment]
This is something I have been considering but wasn't sure how to handle. I like the gold outline, I'll give that a shot.

**Comment by SonicX8000** [comment]
Just curious of how this is fairing. If the gold outline for the Absorption Hearts isn't alright I'll give it another shot for the texture.

![](https://cdn.discordapp.com/attachments/377171551155650560/466468854823125004/absorbheartrenderideav2x.PNG)
Since Absorption is like a shield in a way with it just being temp health, I shrunk the yellow hearts and added some sort of barrier-like thing around it while following the custom render colors. I also added a white outline for it in case a cap on the current layer can be shown much like the regular health but I dunno since the Absorption Heart disappears one by one as you lose them.

*EDIT*
Fixed up a couple pixels being off as well as some shading.

**Comment by SilentChaos512** [comment]
A proper Scaling Health update is one of my top priorities right now. I'll try this out sometime this week. Been busy reworking my development environment and preparing/planning for 1.13...

**Comment by Darkmega18** [comment]
not sure about the reskinned "heart cubes". @Z-Tunic you think you could maybe have one that looks something akin to maybe... armor hearts? like, make them look like a little shield icon? 

Something like asgard shield's old gui?

![image](https://user-images.githubusercontent.com/8104689/42734905-08484ebe-888f-11e8-9665-d82ce00ce7df.png)

but with the color level of the absorption on the interior of the shield icon with maybe a golden yellow border to it.
Cause fancy you should bring this up, I use unnatural absorption in two of my work in progress packs.

but since this is related, are you changing anything else related to absorption @SilentChaos512 ? Cause just today after updating a few mods including this my absorption started to only absorb maybe 75% of the damage I take, which is still damage seeping through my "shields" on a pack where you don't regen primary health. :V

**Comment by SilentChaos512** [comment]
Meant to comment that I added a WIP absorption overlay to 1.3.21, using the second design. Other than the overlay, nothing else should have changed. I do nothing with absorption except replace the vanilla rendering.

**Comment by Darkmega18** [comment]
alrighty. well, I'm gonna have to track this one down then... through my other mods...

**Comment by SonicX8000** [comment]
Funny that you mention that @Darkmega18, as last night I was tweaking the sprites for them slightly to be less 'orb-like' although I still want to keep the small yellow heart in the center.

Anyway... Take 3...
![](https://cdn.discordapp.com/attachments/377171551155650560/468137801632841768/absorbheartrenderideav3.PNG)

I made them more shield-like now. It kinda reminds me of those Gem Shields from Silent's Gems in a way.

**Comment by Darkmega18** [comment]
ooooh, thats niiiice. since I do call absorption "shield hearts".

**Comment by SilentChaos512** [comment]
1.3.22 uploaded with new textures, color fixes, and some other rendering issues corrected.
(edit) Commit is b1bd81ed108d6b113d29ada2a88307499db95f81. GitHub failed to link it.

**Comment by SonicX8000** [comment]
Yea, v3 of the textures aka shield hearts looks better than the orb hearts after looking at them in-game with 1.3.22.

![](https://cdn.discordapp.com/attachments/377171551155650560/468552283089797121/absorboverlayarmorhudbumpoddcolor.PNG)
...apparently the Armor Bar doesn't like it. The coloring when it goes from half to full absorb textures becomes slightly off, hard to ntoice from afar but if you look closely you'll see them being slightly off.

I know it's a still a WIP but so far it looks good.

**Comment by SilentChaos512** [comment]
I always forget armor (never wear any in dev environment, usually). Should be easy to fix.

**Comment by SilentChaos512** [comment]
Version 1.3.23: tweaked the textures a bit to fix color, fixed armor bar position.

**Comment by SonicX8000** [comment]
![](https://cdn.discordapp.com/attachments/377171551155650560/469031060165099520/whiteoutlineheartsrenderbug.PNG)
Seems 1.3.23 broke the white outline for the Hearts Rendering... kinda... it still shows if you only have half a heart remaining for a layer but anymore than that and it disappears. Wasn't sure to make another Issue about it.

A quick question, with the way that the custom rendering works, would it be possible to override the Red Vanilla Color for the Hearts? Reason for asking is that for the Absorb Hearts it goes...

1. Dark Red -> 2. Orange -> 3. Yellow Orange -> etc.

While with Actual Hearts it goes...

1. Vanilla Red -> 2. Dark Red -> 3. Orange -> 4. Yellow orange -> etc.

With the default colors... for the Hearts you can have 15 Layers aka 300 Health where anything beyond that, the colors loop but starting with Dark Red while for Absorb it's 14 Layers aka 280 Temp Health where anything beyond that, the colors loop.

**Comment by ReporterToTheMax** [comment]
I suggest to add a some sort of config that makes the absorption hearts be more vanilla like (hearts with golden outline is an example) as some ppl aren't used to see absorption hearts having a mismatching texture to their actual hearts.

**Comment by SilentChaos512** [comment]
Added a config to select absorption heart style. Default is the shield style already in use, added a golden outline option (colored rows + gold outline) and vanilla, where it render absorption hearts... like vanilla does.
