### ISSUE TITLE
Unable to deal any damage to hostile mobs.

### ISSUE THREAD

**Issue by JustLiam040** [SilentChaos512/ScalingHealth#116]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.15-98
Silent Lib Version: 2.18-100

### Expected behavior

- I have disabled the difficulty system as i only wanted the custom health value for my modpack. (players should start on 5hp and then work to 20 using heart shards). I would expect mobs to take the default amount of damage.

### Actual behaviour

- Mobs seem to have "perma resistance" meaning i can hit them with a sword and it will do no damage, I discovered this in my creative testing, i found i can hit them repeatedly and they will not be affected, their health will remain full no matter how much i attack them.
### Steps to reproduce the problem

1. Disabled difficulty system
2. Changed drop rate of heart crystals to 0.05 (5%), i increased this as i couldnt seem to find an option to increase the drop rate of heart SHARDS, a tip on where to find this would be awesome as i've enabled the option to drop shards rather than heart crystals.
3. I created a new world and spawned in a few zombies to try and test out the new drop rates.
4. I discovered i couldn't kill them, and that they just tanked all damage.

(I tested this at night and at day just to ensure it wasn't something to do with them getting tougher at night.)

Any help with this issue would be much appreciated.

EDIT; Upon further testing i discovered it was not only zombies but all mobs, i was able to make two mobs attack each other and it effectively turned out to be an infinite fight as neither of them were taking damage from the other.

**Comment by SilentChaos512** [comment]
Looks like mobs are taking damage, but immediately healing before they can die. I fixed a similar bug a few months ago. Should have it fixed sometime this weekend.

The config for heart container drop rate applies to shards as well. So you should have everything right.

**Comment by JustLiam040** [comment]
Alright thank you, no immediate rush i just figured id chuck it in here incase it was something i had done incorrectly with my config. Thanks for your help with the crystal shards aswell, i was hoping that was how it worked.
