### ISSUE TITLE
Mob invulnerability/death stance immortality if they're one shotted

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/ScalingHealth#117]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: ScalingHealth-1.12-1.3.18-101
Silent Lib Version: SilentLib-1.12.2-2.3.2-109

### Expected behavior

I should be able to damage mobs and one shot most things with my REAL SOVIET DAMAGE. (2 strength pot levels, whatever nutrition gives you damage wise, deadly yoyo with magic damage and stuff. yeah)

### Actual behaviour

I whack stuff and they're either not taking damage and instantly regenning it all (hearts come out from their heads but nothing happens). or they're getting one shot but remaining stuck sideways glitching and still attacking but still drop their items as if they were killed.

### Steps to reproduce the problem

Not entirely sure, the mobs started doing this when I was exploring with a friend, they had apparently done it recently before hand aswell. our difficulties weren't super high on either side as I'd lost a bunch killing blights and he'd lost a bunch cause of enchanted hearts I made for him, so he was practically zeroed, and I only had around 50 or so. Another friend who wasn't anywhere near us also had 250 or so but I never seemed to have problems killing mobs near him.
I'm reporting it here cause I know you've had issues with mob immortality before, so figured it'd be a good place to start.

I was getting a lot of this stuff spammed into the console i noticed after I relogged when the server crashed on another issue,  but on reload the mobs still had immortality and these were in the console several minutes later when we stopped.

<details><summary>LOG EXCERPT</summary>
<p>
[B#360]  [20:49:27] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
[B#360]  java.util.concurrent.ExecutionException: java.lang.NullPointerException
[B#360]  	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
[B#360]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#360]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at net.minecraft.network.play.server.SPacketEntity.func_149065_a(SourceFile:161) ~[jj.class:?]
[B#360]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147259_a(NetHandlerPlayClient.java:620) ~[brz.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntity.func_148833_a(SourceFile:152) ~[jj.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntity$S15PacketEntityRelMove.func_148833_a(SourceFile:67) ~[jj$a.class:?]
[B#360]  	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
[B#360]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[B#360]  	... 9 more
[B#360]  [20:49:27] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
[B#360]  java.util.concurrent.ExecutionException: java.lang.NullPointerException
[B#360]  	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
[B#360]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#360]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:2084) ~[brz.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntityProperties.func_148833_a(SourceFile:70) ~[kv.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntityProperties.func_148833_a(SourceFile:15) ~[kv.class:?]
[B#360]  	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
[B#360]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[B#360]  	... 9 more
[B#360]  [20:49:27] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
[B#360]  java.util.concurrent.ExecutionException: java.lang.NullPointerException
[B#360]  	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
[B#360]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#360]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147275_a(NetHandlerPlayClient.java:579) ~[brz.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntityTeleport.func_148833_a(SourceFile:55) ~[kt.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntityTeleport.func_148833_a(SourceFile:9) ~[kt.class:?]
[B#360]  	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
[B#360]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[B#360]  	... 9 more
[B#360]  [20:49:27] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
[B#360]  java.util.concurrent.ExecutionException: java.lang.NullPointerException
[B#360]  	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
[B#360]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#360]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:2084) ~[brz.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntityProperties.func_148833_a(SourceFile:70) ~[kv.class:?]
[B#360]  	at net.minecraft.network.play.server.SPacketEntityProperties.func_148833_a(SourceFile:15) ~[kv.class:?]
[B#360]  	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
[B#360]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[B#360]  	... 9 more
[B#360]  [20:49:27] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
[B#360]  java.util.concurrent.ExecutionException: java.lang.NullPointerException
[B#360]  	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
[B#360]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
[B#360]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#360]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at moze_intel.projecte.network.packets.StepHeightPKT$Handler$1.run(StepHeightPKT.java:40) ~[StepHeightPKT$Handler$1.class:?]
[B#360]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
[B#360]  	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[B#360]  	... 9 more
</p>
</details>
<p>

this was all while I was on the server with friends server side.

(edit) SilentChaos512: put log stuff in collapsible block

**Comment by SilentChaos512** [comment]
This kind of issue has been popping up a lot lately (#116 and #114 for example). Sounds like mobs are still healing constantly in some cases. Just need to figure out what kind of state they are in to cause this...

_Note to self: maybe check if max health has actually changed before healing?_

Not really sure if the log info is relevant, seems to be related to entity movement, just glancing at it. But thanks for including it, the more info the better.

**Comment by Darkmega18** [comment]
oh! yeah thats what keeps happening! they take damage but instantly heal the whole thing! thats what was happening. but if I killed them outright with crits instantly they'd go back to full but remain in death state.

Could it be related to giving potion buffs? Cause I have no idea why they'd be healing otherwise... unless you change health after they spawn and then you give them a heal to top them off cause their current hp doesn't actually change? and then perhaps it lags and the heal persists infinitely? :v since we were potentially having some lag due to blood moon and some other things.

**Comment by SilentChaos512** [comment]
Uploaded version 1.3.19 with a potential fix. Let me know if this fixes the issue.
https://minecraft.curseforge.com/projects/scaling-health/files/2576434
