### ISSUE TITLE
Game Stages Support

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/ScalingHealth#118]
Had a couple of requests for this, but I don't know what needs to be added. What should be controllable by stages?

**Comment by SeriousCreeper** [comment]
Personally being able to set the difficulty level depending on gamestages would be nice. 
So the difficulty could start at 0, and once you reach, say, gamestage "difficutly1", it sets the difficulty for that player to a specific amount.
Same perhaps for the spawn rate of blights.

**Comment by Dulciphi** [comment]
Indeed. At the moment (by default), difficulty value increases slowly over time. The only other tools you really have for increasing difficulty lie with players killing certain mobs. It's great that you can reset difficulty when the player dies, and it's great that you can average the difficulty level of all nearby players, but the actual increasing of difficulty could definitely benefit from Game Stages support. 

We use a mod called Ancient Warfare 2 and want heavy PvE elements. We have some players who like to take the game slowly. They're very slow to progress - if at all. They may kill quite a few mobs, but their "base" is still early-game and they may only have basic farming NPCs (no soldiers).  Meanwhile, other players progress the tech stages quickly and do so without killing many mobs. They end up with excellent defences and nothing to really challenge those defences. 

Game Stages support would enable us to gate the stages of difficulty behind certain advancements, the crafting or placement of certain blocks, etc. Then we could really tailor the difficulty of raids in some interesting and fun ways.

**Comment by SilentChaos512** [comment]
Version 1.3.21 adds support for setting difficulty by game stages. Let me know whether or not anything needs to be changed.
