### ISSUE TITLE
[Feature Request] Player Health scaling with Minecraft experience levels

### ISSUE THREAD

**Issue by Ariannae** [SilentChaos512/ScalingHealth#119]
As Title indicates, I'd like to suggest a feature similar to nohero's 1.7.10 mod, [More Health Enchanted](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272363-1-7-10-noheros-mods-more-health-enchanted-beta).

Basically, some arbitrary experience level(s) indicated in the configuration file would give the player character additional health. Resultingly, dying, enchanting an item, or using/consuming experience in some other manner would then revert the player health to where it would be at the new experience level.

ScalingHealth is incredibly close to what I was looking to change Minecraft's health system to, but I would also really enjoy having the player's actual level tied to the health in some way. A side effect of this is that experience would now be a valuable resource that you would need to decide whether to consume or continue to accrue until a later point.

**Comment by SilentChaos512** [comment]
Just uploaded 1.3.22 with this feature. Let me know whether or not it works as you expected.
(edit) Commit is 75deb4739494a5e55de4a237483799ebb3cdcf66. GitHub failed to link it.

**Comment by Ariannae** [comment]
This is definitely what I was looking for, and I really appreciate it. I'll have to mess around with it and double check compatibility with other mods (Currently the Ignite HUD appears to crash me, but I kind of assume that to be Ignite's fault).

The only other thing I can even think to request until more ideas pop up is to somehow make it compatible with stuff like heart containers (Config option?) so that it's tied to experience but would also allow for increasing maximum HP in ways such as a Quest rewarding you a container. Preferably, the heart containers would increase your starting maximum Health, and levels would add additional hearts as configured, depending on the level. The hearts gained from containers would be kept upon death or just generally treated as they normally would be. Sort of a blend between the two options. I have absolutely no idea whether that would be an easy implementation or not though.
Same sort of deal with maximum health lost on death. It would allow some pseudo hardcore playstyle where you lose maximum health when dying but also have the maximum health fluctuate upon level. Basically more fluidity, I guess?

**Comment by SilentChaos512** [comment]
I should be able to make the heart container health bonus separate, sounds easy enough. I'll try that tomorrow.

**Comment by SilentChaos512** [comment]
Version 1.3.23 is up. Heart container bonuses now stack on top of the XP bonus.

**Comment by Ariannae** [comment]
It looks like it's working beautifully. Thank you Silent, it's really appreciated. You're awesome.
