### ISSUE TITLE
[1.12] commands to give health don't work

### ISSUE THREAD

**Issue by mensreaMC** [SilentChaos512/ScalingHealth#120]
1.12.2 Versions

Minecraft Version: 1.12
Scaling Health Version: 1.12-1.3.19-102
Silent Lib Version: 1.12.2-2.3.5-117

### Expected behavior

- I use /scalinghealth health <amount> [player] to set a players health to a certain amount.

### Actual behaviour

- The /scalinghealth health <amount> [player] command returns something saying I don't have access to that command, and this is regardless of my user permissions. Even in admin mode it won't let me use the command.

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by SilentChaos512** [comment]
Need a bit more info. Singleplayer world with cheats enabled, multiplayer server, or a singleplayer world opened to LAN?

**Comment by mensreaMC** [comment]
Tried it with singleplayer with cheats enabled as well as a singleplayer world opened to LAN, with cheats enabled.

**Comment by HydrogenC** [comment]
It's probably because you used the wrong format
It should be
/scalinghealth health [set/add] [amount] [player]
not
/scalinghealth health [player]
