### ISSUE TITLE
[1.12 Suggestion] Command to add to a players health.

### ISSUE THREAD

**Issue by mensreaMC** [SilentChaos512/ScalingHealth#121]
This is for the mods latest 1.12 release.

/scalinghealth health <amount> [player] should allow you to set a players health. I'm requesting a command that lets you add to a players health, something like..

/scalinghealth health add <amount> [player]

..so that instead of setting it you can just add to whatever they already have. It would be really useful in situations where you want to limit life to quest rewards, and since people can share the heart item there's ways to abuse that.

**Comment by SilentChaos512** [comment]
Command is `/scalinghealth health <get|set|add|sub> [value] [player]` in recent versions.
