### ISSUE TITLE
[Suggestion] Possible to change the color for the very first row of hearts? The Red vanilla hearts.

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/ScalingHealth#123]
Would it be possible to allow the color for the first row of hearts aka the red vanilla hearts to have it follow the custom heart render? Currently at the moment, using the default settings there are 14 custom colors, a total of 15 if you count the vanilla heart color, however... when the health meter loops it'll go from the 14th custom color to the 1st custom color, ignoring the red vanilla color.

In case the above doesn't explain it, here's an image of what I'm trying to say.
**Note: I've changed the colors for my client to have the custom render loop via a rainbow-way.**

V is Vanilla Heart Color. 1 thru 14 is Custom Heart Colors.
![](https://cdn.discordapp.com/attachments/377171551155650560/473687689883942912/currentcustomrender.PNG)
In this image... with the way the render works, for the hearts it uses V, 1 thru 14. When it loops... it doesn't use V again but instead it's 1 thru 14. Absorb Hearts uses 1 thru 14.

![](https://cdn.discordapp.com/attachments/377171551155650560/473690584792432680/newcustomrender.PNG)
If the Vanilla Heart Color is completely overridden by the Custom Render... that will be 15 custom colors to use. The Hearts & Absorb Hearts will both use 1 thru 15.

If it's possible to have it changed. The Hex Color to use in place of the Vanilla Hearts is "ff0000". It'll be like this order alongside the default Hex Colors.

01. ff0000
02. bf0000
03. e66000
04. e69900
05. e6d300
06. 99e600
07. 4ce600
08. 00e699
09. 00e6e6
10. 0099e6
11. 0000e6
12. 9900e6
13. d580ff
14. 8c8c8c
15. e6e6e6

**Comment by SilentChaos512** [comment]
Sorry I've let this sit for so long, I'm working on it now. Most likely I will add a boolean config to enable/disable the vanilla hearts. The code for rendering vanilla hearts is different.

**Comment by SonicX8000** [comment]
No worries. Now if the Vanilla Hearts is disabled it should read off of the custom render, right? Much like in the second image?

**Comment by SilentChaos512** [comment]
Yes, that's the plan. It will just "add" a new row of the custom hearts.

**Comment by SilentChaos512** [comment]
Version 1.3.24 is up. It requires Silent Lib 2.3.17. I decided to have the new config enabled by default.

**Comment by SonicX8000** [comment]
Neat, although there's a slight texture issue on the half heart of the custom render when on the first row, A missing light pixel on it.
![](https://cdn.discordapp.com/attachments/377171551155650560/479234623742935052/whiteshinepixelmissing.PNG)
