### ISSUE TITLE
[Request] Remove regeneration boost hunger max's limit.

### ISSUE THREAD

**Issue by Zunlite** [SilentChaos512/ScalingHealth#125]
Theres this mod Iblis that allows you to increase your maximum hunger past its limit with its leveling up system. The problem is when my hunger is at an amount higher than 20 the regen boost will not happen, setting the max hunger for health to regen would fix this but the mod itself wont let me.

**Comment by SilentChaos512** [comment]
Fixed in version 1.3.24.
