### ISSUE TITLE
Spongeforge incompatibility?

### ISSUE THREAD

**Issue by Swash984** [SilentChaos512/ScalingHealth#126]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: ScalingHealth-1.12.2-1.3.23-118.jar
Silent Lib Version: 1.12.2-2.3.11-127.jar

### Expected behavior

- Uses modified config

### Actual behaviour

- Doesn't use the modified config.

### Steps to reproduce the problem

1. install spongeforge
2. love spongeforge because it works so well
3. realize that it takes away a key part of the server
4. realize that scaledhealth still works, though just completely ignores whatever was changed in the config.

**Comment by SilentChaos512** [comment]
Same config file on both client and server? And the file is in the correct location?

**Comment by Swash984** [comment]
Yep, it's in the appropriate location. It actually worked until I added sponge to the mix. That's why I'm a bit confused. Unless it somehow changed from /config/scalinghealth

https://swash.s-ul.eu/za5xcOS2
The config doesn't reset either.

Feel free to add me on discord: Swash#0427
and we can troubleshoot the issue further

**Comment by SilentChaos512** [comment]
Best thing I can think of is to try turning on debug mode in the Scaling Health config on the server. Play a bit (let some mobs spawn) and paste a link to the log file.

I imagine this is a spongeforge issue. Perhaps it's interfering with Forge events somehow. Or maybe another mod is canceling events. The effects of Scaling Health are almost entirely event-based.

**Comment by Swash984** [comment]
Luckily it randomly started working. So I'm not exactly sure why it didn't in the first place.

**Comment by SilentChaos512** [comment]
Good to hear. I'll go ahead and close the issue, let me know if you have any more problems.
