### ISSUE TITLE
[question] Distance from spawn difficulty, does it still work with direct number configs?

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/ScalingHealth#127]
Hey Silent, quick question. If I'm using only distance from origin mode for my difficulty can I still gain personal difficulty from stuff like mob kills, blight kills, sleeping, deaths and boss kills or specific mob kills? I'm just fiddling with my settings in transcendence and figured I should ask directly.

**Comment by SilentChaos512** [comment]
You should still gain player difficulty, it just won't be used for difficulty calculations. So, it's tracked but not used. The Distance and Time mode will use distance from spawn and player difficulty together, if that's what you want.

**Comment by Darkmega18** [comment]
alrighty. that'll be the one then. thanks
