### ISSUE TITLE
[1.12.2] Bandages, Medkits and Enchanted/Cursed Hearts has no texture.

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/ScalingHealth#128]
Minecraft: 1.12.2
Forge: 14.23.4.2750

Mods:
ScalingHealth-1.12.2-1.3.24-119
SilentLib-1.12.2-2.3.17-138

Image:
![](https://cdn.discordapp.com/attachments/377171551155650560/479234491689205775/scalinghealthmissingtexture.PNG)

**Comment by Darkmega18** [comment]
Yep. This. Was doing recipes for them in my game just today and noticed it too.
