### ISSUE TITLE
[Feature Request] Lose Health on Death tweak (-1 heart)

### ISSUE THREAD

**Issue by clifftrials** [SilentChaos512/ScalingHealth#13]
Hello,

Thank you for a wonderful mod. I'm not sure if this is possible, but I would love to see a feature like this implemented in the mod somehow--would definitely love to use it in my server.

Instead of losing all your health on death, could you just lose 1 heart until you hit the default value?
For instance, let's say my starting health is **(3 hearts)**. 
I work my way up to **(10 hearts)**. I die, and lose **(1 heart)** for a now total of **(9 hearts)**. 
However, if I kept dying over and over, I would eventually stop losing hearts at **(3 hearts)** as specified in the config as my starting health.

Thanks for reading, hope it can be considered if you have time (:

**Comment by SilentChaos512** [comment]
I was actually thinking of doing this. Very easy change too, consider it done!

**Comment by clifftrials** [comment]
Very cool. I'll keep an eye out for the next update :D. Hopefully you're still supporting 1.10.2?

**Comment by SilentChaos512** [comment]
Sorry this has taken so long, time has been a bit scarce lately. Yes, I'll backport this to 1.10.2.
