### ISSUE TITLE
minecraft server crashing because of scaling health

### ISSUE THREAD

**Issue by MCPO-Spartan-117** [SilentChaos512/ScalingHealth#134]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.26-127
Silent Lib Version: 3.0.4-150

### Expected behavior

- To work and make a new world for me and friends to play on
[crash-2018-09-11_08.50.14-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/2371027/crash-2018-09-11_08.50.14-server.txt)

### Actual behaviour

- It crashs with no warning

### Steps to reproduce the problem

1. having scaling health in the mods folder
2. Profit

**Comment by SilentChaos512** [comment]
Please update Silent Lib to 3.0.5

**Comment by MCPO-Spartan-117** [comment]
thanks
