### ISSUE TITLE
Last 1.12.2 issue

### ISSUE THREAD

**Issue by BadLucKWyvern** [SilentChaos512/ScalingHealth#135]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: ScalingHealth-1.12.2-1.3.28-129
Silent Lib Version: SilentLib-1.12.2-3.0.4-150

### Expected behavior ### Actual behaviour

I have recently installed Thermal expension with its addons, and i have upgraded my Scaling health to the last version of 1.12.2
Since that upgrade, i have a problem with Ancien Warfare mod: each time a combat NPC dies, it drop its stuff (as usual) and a Name tag because i have renamed it with the UI from the AW mod (with not on purpose). Also, they aren't ressurected anymore.

### Steps to reproduce the problem

Equip a NPC from AW with stuff, rename it with the UI, and let it killed by a mob
![image](https://user-images.githubusercontent.com/17027691/45484387-376fa680-b754-11e8-829e-4c5b8382c7c1.png)
![image](https://user-images.githubusercontent.com/17027691/45484489-96352000-b754-11e8-83e0-cf2a1169cadf.png)

**Comment by BadLucKWyvern** [comment]
EDIT: It seems NPC can respawn like before, the first time it happened, they didn't respwned. thats probably a bug from Ancien Warfare itself. The lone little problem is now NPCs are dropping a custom nametag on death

**Comment by SilentChaos512** [comment]
I've seen the name tags on some pack as well, not sure what mod is adding them.

**Comment by BadLucKWyvern** [comment]
I have an another issue, when a demoman from TF2 weapons killed a blight spider, the tchat said:
Blight Spider has been killed by   using a   .
Sometimes some more blight are dying weirdly:
Blight zombie is dead.
What does it mean ? How ? who ?
By the way, when tamed entities or NPC are dies, since the update of scaling health, everything is written in the tchat. Meaning it didn't make it before. It seems its better now right ?
