### ISSUE TITLE
[Enhancement Request] Adding a command to export potions/effects on a .csv external file

### ISSUE THREAD

**Issue by BadLucKWyvern** [SilentChaos512/ScalingHealth#136]
Remind of the post N°245 from Curseforge Scaling health mod:

I wanted to know if thats possible to add a command that can export all potion/effects type on a external file

Ancien Warfare have a command to export all entities on a .csv file like this: /awutils exportentities

When the command is done, all entities types have their ID etc... saved on a file, this is very usefull to blacklist/white list mobs on config files

I had that request for potions/effect, because some mods are adding potions and effects, and i wanted to get all potions id to set on the white list potion/effect on mobs on Scalling health mod :P

 Is it possible ?

i would like to send you the file here to show you the exemple, but i can't...

(Sorry, i tryed to explain things with my english level)

**Comment by SilentChaos512** [comment]
I'm working on the command, but it's part of Silent Lib. Right now, it just puts everything in the log file. Is that acceptable?
(edit) commit is [here](https://github.com/SilentChaos512/SilentLib/commit/6e23a3f5a7c36bc9227fb18859e918168f72e3b6)

**Comment by BadLucKWyvern** [comment]
On the log file ? i think its ok, i just need to see if im able to handle it, i remind you that im lost with this code business xP
