### ISSUE TITLE
Some suggestions!

### ISSUE THREAD

**Issue by SadMametchi** [SilentChaos512/ScalingHealth#137]
Minecraft Version: 1.12.2
Scaling Health Version: 1.3.26
Silent Lib Version: 3.0.1

I'm really digging the mod, but the amount of healing bandages and medkits do isn't very good. 

Maybe, instead of having bandages heal 30% over 60 seconds, bandages could recover 30% health instantly after holding it down for five seconds. 
So that players have an incentive to use the more expensive medkits as opposed to only cheap bandaids, there could be a 'Heal Fatigue' that occurs after using a bandage. During this 'Heal fatigue', players won't be able to use bandages or medkits for 15 seconds. 

Same with medkits, but with 70% health recovery. Maybe it could take 7 seconds to use instead of 5.

Also! I made some sprites for the bandage and medkit items! If you like them, I'd be more than happy to let you use them!

![medkitbig](https://user-images.githubusercontent.com/43279199/45568761-77558d00-b82b-11e8-9ad5-76d0c9e4d5ef.PNG)
![bandagebig](https://user-images.githubusercontent.com/43279199/45568762-77558d00-b82b-11e8-921e-e51ebdd8f071.png)
![medkit](https://user-images.githubusercontent.com/43279199/45568763-77ee2380-b82b-11e8-9c6c-8e1332037b0c.png)
![bandage](https://user-images.githubusercontent.com/43279199/45568764-77ee2380-b82b-11e8-94d6-95a5955f9e11.png)

**Comment by SadMametchi** [comment]
If you like how these sprites look, I'd be more than happy to redo all of them! From the ore, to the heart containers. Please let me know, thanks!

**Comment by SilentChaos512** [comment]
Those textures are nice, but I would rather keep textures in the base mod 16x16. If you wanted to make and publish a resource pack, I'd be happy to promote it however.
I do agree the healing items could use some work. I'll play around with it next time I work on the mod.

**Comment by SadMametchi** [comment]
I gotcha. I'll make them as 16x16 sprites, then!

One more thing: Is there any way to change the sound effect that plays when you use a Heart Crystal? Preferably, one inside the mod folder so that it doesn't play in the vanilla game. 

Something like this: https://youtu.be/0_z47pt0oao

**Comment by SadMametchi** [comment]
I've completely redone the sprites! Enchanted and Cursed hearts look good already, so I left them alone. Check it out! 
![sprites](https://user-images.githubusercontent.com/43279199/45788462-b418ee00-bc48-11e8-9d4d-78d566d07e65.png)
(Don't worry about the awkwardly light pixel on the heart container. I fixed it in the google drive download.)

You can download them here. I animated the Heart Container, but I don't like how it turned out. I wanted it to beat twice to act like the 'lub-dub' of an actual heart, but I can't figure out how to make it look good. 

Also, I added a potential sound effect for the extra HP effect. Let me know what you think. 

https://drive.google.com/drive/folders/1eB9OF386ENEiPlorgD5PTtiBRf-Pwo9M?usp=sharing

**Comment by SadMametchi** [comment]
Actually, now that I look at the Heart Crystal Shard sprite, I don’t like how it looks. I’m not used to 16x16! I’ll redo the Heart Container and the Heart Crystal Shard some other time.
