### ISSUE TITLE
Crash when difficulty goes up to 240

### ISSUE THREAD

**Issue by Neglevin** [SilentChaos512/ScalingHealth#138]
Minecraft Version: 1.12.2
Scaling Health Version: 1.12.2-1.3.28-129
Silent Lib Version: 1.12.2-3.0.5-152

### Expected behavior

- I expected to be able to continue playing on my world without any problems.

### Actual behaviour

- The game crashes when it gets to difficulty level 240.

### Steps to reproduce the problem

1. Download the above versions of Scaling Health and Silent Lib.
2. Set the difficulty meter to 240.
3. ...
4. Profit

Also here's the crash log if it helps: https://paste.dimdev.org/vofegiyolu.mccrash

**Comment by SilentChaos512** [comment]
Crash report points to OptiFine. No other mod is in the stacktrace.

**Comment by Neglevin** [comment]
Alright I'll remove Optifine and see if it fixes anything. Thanks for the quick reply!

Edit: Okay so it seems that it was Optifine that was causing the issue. Thanks for the help and sorry for the confusion.
