### ISSUE TITLE
[SUGGESTION] Nutrition compat

### ISSUE THREAD

**Issue by Sunconure11** [SilentChaos512/ScalingHealth#139]
Either I'm having issues with another mod, or Nutrition's potion effects simply do not work right with this mod (cannot see hearts from this mod). In addition, it seems to play an irritating sound effect which sounds like something burning up in fire or lava.

https://github.com/WesCook/Nutrition

**Comment by Sunconure11** [comment]
![screenshot 2018-09-23 16 42 26](https://user-images.githubusercontent.com/5614902/45932782-b4b6ca80-bf4f-11e8-9021-6cce0a39014d.png)

After dying, the rendering became... weird when I used custom rendering.

**Comment by SilentChaos512** [comment]
From the screenshot, it looks like some other mod is also drawing hearts, so you're getting whatever the other mod is doing, then Scaling Health hearts above that (the red and orange). Aside from the extra rows of hearts, it looks normal.
Just glancing at how Nutrition handles potion effects, I see no reason it would cause an issue. Health bonuses from mods should add together correctly. Does your max health seem wrong?

**Comment by Sunconure11** [comment]
Hm, as I will likely be a bit busy for the day, this is the pack of mine in question, though I'm working on another update, hopefully to fix this, and add some new content. The pack does have glass hearts, in case thats an issue.

https://minecraft.curseforge.com/projects/compitum-magia

See if there are any mods that stand out in terms of screwing with health rendering. It's been there for a while and I have no clue what mod is doing it.
