### ISSUE TITLE
Crash with Ignite HUD

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#140]
### Versions

Minecraft Version: 1.12
Scaling Health Version: 1.3.26
Silent Lib Version: 3.0.1

### Expected behavior

HUD should be replaced with the "Ignite HUD" version

### Actual behaviour

game crashes with error:

`The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/silentchaos512/scalinghealth/config/ConfigScalingHealth`

### Steps to reproduce the problem

1. Install Scaling Health, SilentLib and Ignite HUD
2. launch the game in survival mode
3. wait for it to load
4. CTD!

Thank you for your time!

**Comment by SilentChaos512** [comment]
Try updating to the latest versions of Scaling Health and Silent Lib. If that doesn't help or isn't possible, please link a full crash report.

**Comment by ghost** [comment]
same problem running the newest versions. Here's the crashlog [attached] 
[crash-2018-10-03_01.52.11-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/2438862/crash-2018-10-03_01.52.11-client.txt)
. i can deduct that the only ones causing problems are Ignite HUD and scaling health as removing either one fixes the crashing.

**Comment by SilentChaos512** [comment]
I did rename my config class a while ago, didn't realize another mod was referencing it. That will be up to Ignite HUD to fix, since the entire structure is changing.
