### ISSUE TITLE
Game Crash due to mysterious circumstances??? (Crash Reports found within)

### ISSUE THREAD

**Issue by Astralika** [SilentChaos512/ScalingHealth#141]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.29
Silent Lib Version: 3.0.6

### Expected behavior

- Attempting to Join my friend's server in a bespoke modpack of our assembly. Expected behavior is for this to simply open up as intended. 

### Actual behaviour

- Game crashes when I attempt to join said server. Said server is set up on his end as a single-player world opened to LAN, and then accessed through EVOLVE.

### Steps to reproduce the problem

1. The bespoke modpack we're using: 
[Bold_New_World_1.2-1.2.zip](https://github.com/SilentChaos512/ScalingHealth/files/2454480/Bold_New_World_1.2-1.2.zip)
2. He set up the server, I connected, as described above
3. On entering the game, I immediately disconnect due to timeout the first time (as I expect, this happens even when we use modpacks without this mod, I believe this to be a facet of our method of connecting, or perhaps just my computer.)
4. On disconnect, whether through timeout or manually disconnecting, the game crashed with this crash report (this is the first crash report)
[crash-2018-10-07_19.59.52-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/2454489/crash-2018-10-07_19.59.52-client.txt)
5. We had changed our configs to suit our needs and, given Scaling Health was the issue, decided to test if reverting to Scaling Health's original configs would fix the problem. (Before, when he'd save and quit, his game would stop responding and never start responding again.) When we both moved the edited config to let the game generate the default config again and repeated the connection/disconnection steps. When he save-and-quit, his game responded fine, but when I disconnected from the server I got *this* crash report, which looks fairly identical. 
[crash-2018-10-07_20.20.48-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/2454490/crash-2018-10-07_20.20.48-client.txt)

I'm still not 100% sure if this is a problem on our end, or a problem with the mod. I suspect, due to current results in our testing, that it's a matter with how the mod handles our method of server setup??? I will follow up this issue, I'm curious if reverting to 1.3.26 will fix our problems.

**Comment by Astralika** [comment]
Reverting to 1.3.26 immediately resulted in no crashing on disconnect, either with the default configs *or* our edited configs. My conclusion is this is something on 1.3.29's end, though I'm not sure what.

**Comment by SilentChaos512** [comment]
Looks like the kind of crash that would be a random occurrence. I couldn't reproduce it, but I have an idea of how to fix it.
