### ISSUE TITLE
[Request] Percentage-based bonus regeneration

### ISSUE THREAD

**Issue by Ariannae** [SilentChaos512/ScalingHealth#147]
As the Title indicates, I'd like to see the configuration file setting for 

"# Bonus regen will stop when players have this much health or more."

be changed to allow for percentage-based bonus regeneration. So perhaps if the I:"Health Max"= is in decimal format it takes the percentage of health, and if it's a whole number it would use the actual number of health points?

With a percentage-based format, a 100 HP player that has mobs hitting them on average for, say, ten damage will get as much benefit out of it as a 10 HP player having mobs hit them for one damage.

**Comment by SilentChaos512** [comment]
Just added a setting to turn scaling with max health on for now.
