### ISSUE TITLE
A mod is stopping me from adding more health? Don't know what mod tho?

### ISSUE THREAD

**Issue by justxice** [SilentChaos512/ScalingHealth#148]
### Versions

Minecraft Version: 1.12
Scaling Health Version: 1.3.32
Silent Lib Version: 3.0.10

Whenever I consume a heart container, in the console it shows "[Scaling Health]: Another mod seems to have canceled healing from a max health increase (player Motome)" not sure what mod is cancelling it.

**Comment by SilentChaos512** [comment]
There's no easy way to tell which mod is responsible. That log message is also a separate issue from max health increases. A mod can cancel healing without interfering with max health.

First try enabling Scaling Health's debug mode in the config. Log into a world and there should be some extra text on the screen, including a list of health modifiers. Trying using some heart containers, see if anything changes. You should see one called "ScalingHealth.HealthModifier".

If that doesn't give you any clues, you'll just have to try disabling mods until you find the one. I usually disable half, then enable/disable 5 at a time.

**Comment by kreezxil** [comment]
Which pack is this from?
