### ISSUE TITLE
Blight Mobs are Suffocating in Walls ??

### ISSUE THREAD

**Issue by Zombiella** [SilentChaos512/ScalingHealth#150]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.32-134
Silent Lib Version: 3.0.10-161

### Expected behavior

- Blight Mobs spawning "normally" ??

### Actual behaviour

- I have never seen a Blight Mob but I see messages all the time that one has suffocated in a wall. IS this normal???

### Steps to reproduce the problem

1. No need,
2. happens constantly.
3. ...
4. Profit ???

Lol

**Comment by SilentChaos512** [comment]
Depending on the mod list, this can happen frequently. Especially with spider jockeys, the spiders will climb a wall and suffocate the rider. The only option right now is to either turn off blight death messages or enjoy the show.

**Comment by Zombiella** [comment]
Well I finally saw my first Blight Mob in all this time and it kicked my butt 6 times but I got it. :< At least I know not ALL of them were spawning in walls which is kinda what I was afraid of tbh.

**Comment by Zombiella** [comment]
So, a lot of Blight Mobs are still suffocating, but that may just be an unfortunate occurrence. However, I see enough Blight Mobs for it not to really matter and now I'm just happy to know I can actually fight them lol.
