### ISSUE TITLE
Spongeforge Issue

### ISSUE THREAD

**Issue by Aehryn** [SilentChaos512/ScalingHealth#151]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.12.2-1.3.31-132.jar
Silent Lib Version: 1.12.2-3.0.9-159.jar

### Expected behavior

- Standard Usage

### Actual behaviour

- HP is Constantly Resetting to 20 then back to Modded
Showcase: https://i.imgur.com/DlKDpmo.gifv

### Steps to reproduce the problem

1. Installed SpongeForge
2.Ran server with No Plugins
3. Ran into this Issue with Scaling Health

**Comment by ghost** [comment]
This issue has occurred to me too on my server. Not sure if it’s fixed yet or not but I feel as though this is more of a SpongeForge Issue than it is ScalingHealth.

**Comment by SilentChaos512** [comment]
Probably a SpongeForge issue, not really sure what to do with this. I am setting health with vanilla's attribute modifiers. I would think using a vanilla system should work as intended, unless SpongeForge has some kind of issue with that.

**Comment by ghost** [comment]
Confirmed; this is an SpongeForge Issue. Not an SH Issue. 

Actions to take:
@Kottonboru You will need to forward this issue to the SpongeForge Issue page

**Comment by LANCECHEN117** [comment]
the recommand version of sponge 2768 has fixed that problem, however this problem happens again in new version of sponge

**Comment by ghost** [comment]
Then forward it to the SpongeForge team.
