### ISSUE TITLE
[1.12.2] Log Spam + Some kind of 'damage delay' happening if you take damage from Magma Blocks, Cacti, etc.

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/ScalingHealth#152]
Minecraft: 1.12.2
Forge: 14.23.5.2807

Mods: 2
ScalingHealth-1.12.2-1.3.32-134
SilentLib-1.12.2-3.0.9-159

-----
Might be related to 'LivingAttackEvent' as before the change this didn't occur. If you take damage from something that hits you many times such as being in lava, hugging a cacti, getting a hot foot on a Magma Block. You apparently get hit MANY times despite only taking damage once due to invincibility frames. As shown in the log here...

![](https://cdn.discordapp.com/attachments/377171551155650560/536444802028535818/shlogspamdamagevanilla.PNG)

I stood on a Magma Block for one damaging hit then got off before the next damaging hit occurred, as you can see... it seems to think that I got hit oh-so-many times while on the Magma Block, despite only one hit registering. Also for some reason the 'generic' damage source appears as I'm taking oh-so-many hits which I cannot explain.

Despite the log spam... apparently this can cause some sort of 'damage delay' when taking damage, you can tell if you watch your screen shake as you take damage on a Magma Block, Cacti, Lava, etc. It does this even if the Debug Info is disabled, as if it's trying to keep up or something when you lag in the game.

**Comment by SilentChaos512** [comment]
LivingAttackEvent is fired before damage is dealt, I probably need to check whether or not the target can be hurt that tick.
