### ISSUE TITLE
How to lower the armor strip?

### ISSUE THREAD

**Issue by YAoi111** [SilentChaos512/ScalingHealth#153]
### Versions

Minecraft Version: 1.12/2
Scaling Health Version: 1.3.32
Silent Lib Version: 3.0.10

### Expected behavior

- How to lower the armor strip? Sorry for my English, I from Russia).
![screenshot_2](https://user-images.githubusercontent.com/47037006/51760663-f7dea100-20db-11e9-9c5e-94ad0752fbf8.png)

**Comment by SilentChaos512** [comment]
Scaling Health should not affect the armor bar. Whatever mod is changing the armor bar style is likely the cause.

**Comment by YAoi111** [comment]
thanks

**Comment by Tfarcenim** [comment]
Overpowered armor bar is causing this issue, use overloaded armor bar instead.
