### ISSUE TITLE
Client crash on Logging in server

### ISSUE THREAD

**Issue by halsaegusa** [SilentChaos512/ScalingHealth#157]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.31.132
Silent Lib Version: 3.0.10-161

Im playing Mod pack:forever Stranded Lost Souls with some friends on my server.
When 1 player Logging in, then others can't Loggin,the client crashes.

Some day, it works well,but today it not works.
Maybe, Difficulty rising cause it.

[crash-2019-02-18_00.28.54-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/2873129/crash-2019-02-18_00.28.54-client.txt)

### Steps to reproduce the problem

1. Difficulty rising some level
2. Login, and other Login
3. 2nd player can't Login

**Comment by SilentChaos512** [comment]
I've seen something like this before. I think it has something to do with either connection quality or the player's computer's speed. Like the server is talking to the client before it's ready.. I'll add in a few safety checks which should prevent the crash.
