### ISSUE TITLE
Crashing when entering a world.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/ScalingHealth#158]
### Versions

Minecraft Version: 1.13.2
Scaling Health Version: 2.0.0+2
Silent Lib Version: 4.0.0+2

### Expected behavior

- World loading in as normal.

### Actual behaviour

- Loading into a newly created world and crashing.

### Steps to reproduce the problem

1. Create a world
2. Enter the world
3. Wait for game to crash.
4. Crashed.

Crash-report: [Hastebin paste](https://hastebin.com/ivebobijam)

**Comment by SilentChaos512** [comment]
1. What Forge version are you using?
2. Does it crash with only Scaling Health and Silent Lib installed?

**Comment by Gbergz** [comment]
I'm using Forge: 25.0.26 (1.32.2)

And it does NOT crash when only using Scaling Health & Silent Lib.


EDIT: Here's another crash-log.
[Hastebin](https://hastebin.com/ayomawihay)

**Comment by SilentChaos512** [comment]
I believe this is the fault of another mod. No idea which, but they must have not updated their capabilities correctly. The API did change.

**Comment by Gbergz** [comment]
Ah ok. I guess i could remove a mod 1 by 1 and see if i find what mod it is. Thanks for the help anyways!
