### ISSUE TITLE
Crash on startup 1.12.2

### ISSUE THREAD

**Issue by klmjr** [SilentChaos512/ScalingHealth#159]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.33+135
Silent Lib Version: 3.0.13

### Expected behavior

No crash and start up

### Actual behaviour

Crash with an exception:
[STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/20/19 6:53 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Scaling Health (scalinghealth)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;
	

### Steps to reduce the problem

1. re running
2. deleting config

**Comment by SilentChaos512** [comment]
Forge version? Or a link to a complete crash report, which would also answer that question.

**Comment by barrowisp** [comment]
I'm also getting crashes on attempts to startup, noting exception for Scaling Health.  I used the recommended version of Forge: 1.12.2 - 14.23.5.2768
[https://gist.github.com/barrowisp/1017d5cad5071289b8a226e14d843c43](https://gist.github.com/barrowisp/1017d5cad5071289b8a226e14d843c43)

Seems OK with latest, though: 1.12.2 - 14.23.5.2814
:)

**Comment by SilentChaos512** [comment]
Confirmed, crashes in 2768, but works on latest.
