### ISSUE TITLE
[Crash-Report] When trying to open the game ( ScalingHealth-1.12.2-1.3.33+135)

### ISSUE THREAD

**Issue by J3susGam3r** [SilentChaos512/ScalingHealth#161]
Hi, this is my first report and it's about a crash I had when trying to load the mods.

It turns out that a few weeks ago I downloaded the latest version of "Scaling-Health" which was the version "1.3.33 + 135" in which I have about 36 active Mods (counting Scaling-Health and Silent Lib) which until now use the last version which is "1.3.31-132".

When trying to enter the game, the loading screen of Minecraft + Forge opens loading the Mods and all that, but in phase 2/7 or I think the 3/7 closes the game and opens the launcher warning me that my game failed to load the mods (a game crash basically).

I have not the remotest idea that this crash of the game may be causing, knowing that from version "1.3.31-132" below, the game opens correctly.

The only thing that I suppose I can do is provide the "crash-log" if any of the creators of the Mod or those who are associated with this project can help me with this problem.

I'll leave the .txt file of the crash report and a paste bin link just in case.

[crash-2019-03-10_16.38.36-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/2950138/crash-2019-03-10_16.38.36-client.txt)

https://pastebin.com/UP8iwmzu

The mods that I use both normal and secondary / support are: Abyssalcraft, Aether Legacy, Advent of Ascension, Backpacks, Baubles, Bookshelf, Botania, CFM (Mr Cryfish Furtniture), Chisel, CTM (Connected Textures Mod), cx library, Enchanting Plus , Forgelin, Global xp, Gravestone, Guide API, Hwyla, Ironchest, JEI (Just Enough Items), Journeymap, Librarianlib, Mantle, More furnaces, Openglider, Optifine, petbuddy, Radixcore, Silentlib, subcommonlib-sublib, Tconstruc (Tinkers Construct) , Twilight Forest, Wizardry and Scaling-Health (the 1.3.31-132 that is the one that supports me).

About my Laptop:

CPU: i5 8400H - 8 Cores/CPU (2.30GHz up to 3.10GHz)
GPU (integrated): Intel UHD Graphics 630
GPU (Dedicated): Nvidia Geforce GTX 1050 (4GB)
RAM: 8GB Ram (4GB Dedicated to Java & Minecraft)

I will gladly wait for an answer if it is possible, at the moment I have nothing left but to stay in an old version of said mod.

Up to here I say goodbye.

PS: I do not know much in English so I use a translator.

**Comment by SilentChaos512** [comment]
Looks like the same crash as #159. Updating to a more recent version of Forge fixes the crash.

**Comment by J3susGam3r** [comment]
Well, I just updated the Silentlib that came out on February 17 and I thought that would fix it, but I see that it remains the same, it only works with the previous version at +135 (132). 

Well, I just updated the Silentlib that came out on February 17 and I thought that would fix it, but I see that it remains the same, it only works with the previous version at +135 (works with 132).

I guess it must be the version of Forge (2768) as I saw in post #159 

Then it is thing of the version or we would have to wait for a new version of the Forge or the Mod, I suppose?

**Comment by SilentChaos512** [comment]
No, recent Forge versions do work. I do not know which version it was fixed in, but it works with the latest version (14.23.5.2814).

**Comment by J3susGam3r** [comment]
Well, that's what I saw in the aforementioned post, although I do not like using the versions which are not the recommended ones, well the same way the predecessor version works for me and then I just have to wait for the update of some Of the 2 things, I think that with that it is already clear to me that this version of Forge will not allow me to run the Mod and vice versa, I think that with this I should close the post that I have done so to say that it is "solved" or more well "closed" that would be the most logical? I suppose?

  It is not so bad to be a version below the most recent, It is very well enjoyed the game. Anyway, thank you very much for your comments and I hope it has not been a nuisance for you.

**Comment by wendall911** [comment]
Building ScalingHealth against 2768 also resolves the issue. This would probably be the better course unless you want to keep getting these reports. Also setting a required Forge version would work as well. Otherwise, it is just a random crash that is difficult to debug.
