### ISSUE TITLE
Exception in server tick loop (1.12.2)

### ISSUE THREAD

**Issue by DatrixTHLK** [SilentChaos512/ScalingHealth#162]
### Versions

 Minecraft 1.12.2
- **Scaling Health**:  1.3.35+138
- **Silent Lib**:  3.0.13
- **Forge**:  14.23.5.2838
- **Modpack** (if applicable): Custom

### Expected behavior

-  To run around in the game without it crashing randomly.

### Actual behaviour

-  I launch the game run around for a small amount of time before the game takes me back to the Main menu.

### Links/Images

- Crash Log [here](https://paste.dimdev.org/iguditicut.mccrash)
- FML Report [here](https://gist.github.com/DatrixTHLK/0651bae02d03c8bb42c4797284fec309)

### Steps to reproduce the problem

1. Launch Minecraft
2. Run around in the game
3. Game crashed

If this has been mentioned before, then you may ignore, unless 1.12.2 isn't being developed anymore. 
What do you know, that rhymes. xD

**Comment by ghost** [comment]
I, personally, was unable to reproduce this issue. Maybe this is a config related issue or perhaps your client being weird.

May I ask if this is a crash or just a error (as I saw VanillaFix (if it were an error it would just take you to the title screen as if nothing happened))

**Comment by DatrixTHLK** [comment]
Hi, the error happened with VanillaFix in my mod list. All it did was take me to the menu screen. I downgraded to the previous version 1.3.32-134 and so far the error still occurs, though it is much more rare than 135 was. I hope this helped answer your question. Not sure if this is related but instead of 2048 max hearts I set it to 4096 max hearts within the config. If that is what caused the issue within minecraft, then I will set it back to 2048 and see what happens.

**Comment by DatrixTHLK** [comment]
Newest update 1.3.34+135 has caused no issues as far as crashing or bringing me back to the main menu screen. If the issue comes back I will let you know about it, for now it's fixed. Thank you for the update I appreciate the response as well! :) Keep up the nice work!

Edit: No longer crashes at random times. I'll consider this closed. :)

**Comment by DatrixTHLK** [comment]
Nevermind crash occured again: https://paste.dimdev.org/liqozurife.mccrash 1.3.34+135
