### ISSUE TITLE
Difficulty above 250

### ISSUE THREAD

**Issue by ketpain** [SilentChaos512/ScalingHealth#163]
Bar doesn't represent the actual difficulty level

**Comment by SilentChaos512** [comment]
Need a bit more information. Is this 1.13.2 or 1.12.2? Playing on a server or singleplayer? If playing on a server on 1.12.2, are the server and client config files the same?

**Comment by ghost** [comment]
@SilentChaos512 You should probably make an Issues Template

**Comment by SilentChaos512** [comment]
There is an issue template.

**Comment by iCingCong** [comment]
Hi, I believe I have the same issue as this one. Mine is on version 1.12.2, our maximum difficulty level is 10000 but the difficulty bar only shows 250 as its max. When I am near another player (we both reached 250 difficulty and maybe more) the bar readjusts to a value of 262 couple weeks ago and 263 as of today. We both believe that the actual difficulty value is more than 250 and have no idea how to find it out. I understand this is sort of a small issue and you guys probably stopped focusing on the 1.12.2 version but I'm just curious if there is a way to fix this visual bug.
