### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by genisis1234r** [SilentChaos512/ScalingHealth#165]
Scaling health Version 1.3.33
Silent Lib version 3.0.13
Forge Version 14.23.5.2778

On startup, on entering phase two of loading mods, once it gets to scaling health, it crashes.
Pastebin: https://pastebin.com/hC7VTRtv

**Comment by SilentChaos512** [comment]
Duplicate of #161. You can either update Forge to latest, or downgrade Scaling Health.
(edit) Minimum version is 2779.
