### ISSUE TITLE
#ScalingHealth doesn't work in other dimentions (in Sponge server)

### ISSUE THREAD

**Issue by LANCECHEN117** [SilentChaos512/ScalingHealth#169]
<ScalingHealth works well in any dimention of forge server however it only works in the overworld(Level 0) in the sponge server.

First of all, I've tried to create new world by nucleus plugin and it doesn't works as well.

Then I used Cursed Heart item in DIM-1 in order to see whether server is sync with client, however this item cannot increase difficult by right clicking it, the difficulty indication didn't increase at all！

Finally, I delete sponge forge then this mod works well in just forge server
->

### Versions

- **Scaling Health**: <1.12.2-1.3.34+135>
- **Silent Lib**: <1.12.2-3.0.13+167>
- **Forge**: <forge-1.12.2-14.23.5.2825-universal>
- **Modpack** (if applicable): Custom

### Links/Images
[latest.log](https://github.com/SilentChaos512/ScalingHealth/files/3142023/latest.log)

**Comment by SilentChaos512** [comment]
There has been another report of Sponge issues (#151), might be related. I'm not sure if there's anything I can do. I don't know much about Sponge, but I can confirm this happens even with no plugins installed.

**Comment by LANCECHEN117** [comment]
> 
> 
> There has been another report of Sponge issues (#151), might be related. I'm not sure if there's anything I can do. I don't know much about Sponge, but I can confirm this happens even with no plugins installed.

I've reported it to sponge issue！
