### ISSUE TITLE
Right clicking on the HeartContainer does nothing

### ISSUE THREAD

**Issue by MCJediYoda** [SilentChaos512/ScalingHealth#17]
I am in 1.10.2 and right clicking on the HeartContainer does nothing.  I went to get the version of the mod and noticed it shows 1.11-1.0.4-41.  Is this version for 1.11 only?  I am also using Forge 12.18.3.2239.  I am going to go back down to version 1.10.2-1.0.3-36 for now.  

Thanks
MCJediYoda

**Comment by SilentChaos512** [comment]
The new build is compatible with 1.10.2 and 1.11.x. I added some CompatLayer-like features to Silent Lib a couple days ago. That means updates for 1.10.2 again, but also new bugs to iron out. Thankfully, this one is easy to fix.

**Comment by MCJediYoda** [comment]
ok thanks for the update
