### ISSUE TITLE
Option to Remove Hearts Upon Death

### ISSUE THREAD

**Issue by djwoozie** [SilentChaos512/ScalingHealth#170]
### Versions
- **Scaling Health**: 1.2.245-135
- **Silent Lib**:  3.0.13-167
- **Forge**: 14.x.x.2815
- **Modpack** (if applicable): Custom

### Expected behavior
Player loses 28 health on death

### Actual behaviour
Player loses all extra hearts consistently on death.
In the config it's set:

            I:"Health Lost On Death"=28
            S:"Health Lost on Death"=28

Not sure with the "I" or "S" is so I set it on both and we still end up losing all hearts on death.
Also does your mod add bleed?

**Comment by SilentChaos512** [comment]
Should be "I" (for integer). The "S" is probably a leftover from an older version. Try removing the S version completely (just remove the entire line). Not sure if that will help, but the Forge config format can be a bit weird, so you never know.

Actually, it might be better to wipe your config completely and redo it if it's been there for so long. I think there have been compatibility-breaking changes in the past. But it's been a while, I can't remember what configs were affected.
