### ISSUE TITLE
Null Pointer Exception: Ticking Player

### ISSUE THREAD

**Issue by DatrixTHLK** [SilentChaos512/ScalingHealth#172]
### Versions

- **Scaling Health**: 1.3.34+135, 1.3.35+138 
- **Silent Lib**: 3.0.13+167
- **Forge**: 14.23.5.2838
- **Modpack** (if applicable): Custom

### Expected behavior

- Not crash at random times

### Actual behaviour

- Game crashes to main menu (since vanillafix is involved)

### Links/Images

- Crash Log: https://paste.dimdev.org/kuveyacoxi.mccrash
- Config (main.cfg): https://gist.github.com/DatrixTHLK/fbec6f072ae0dca71370c6595a3a4acd

### Steps to reproduce the problem

1. Run game
2. Run around
3. Wait for mobs to spawn
4. Wait for mobs to die
5. Game randomly crashes

**Comment by DatrixTHLK** [comment]
Um not really sure what's going on now, but as of 1.3.36+140 my game seems to tank and the block lag when I try to break a block is terrible and the mobs all seem to go at a snails pace. Going back to previous version fixed that (1.3.35+138).

**Comment by SilentChaos512** [comment]
There are two changes in 1.3.36 that might cause this... Would you mind sending me your config file? I'd like to test this myself.

**Comment by DatrixTHLK** [comment]
Sure! Here you go.
[main.zip](https://github.com/SilentChaos512/ScalingHealth/files/3221008/main.zip)

Thanks for the response!

**Comment by P3rf3ctXZer0** [comment]
@SilentChaos512 I have no idea if that would help but it was mentioned in JVM crash

Compilation events (10 events):
Event: 3394.254 Thread 0x000000000fac4800 nmethod 29740 0x00000000848d9090 code [0x00000000848d9240, 0x00000000848d97a0]
Event: 3394.254 Thread 0x000000000fac3000 nmethod 29741 0x0000000081f551d0 code [0x0000000081f554a0, 0x0000000081f56ba0]
Event: 3395.060 Thread 0x000000000fac2000 29743       4       net.silentchaos512.scalinghealth.utils.SHPlayerDataHandler$PlayerData::writeToNBT (106 bytes)
Event: 3395.068 Thread 0x000000000fac2000 nmethod 29743 0x0000000086370150 code [0x0000000086370340, 0x0000000086370d70]
Event: 3399.455 Thread 0x000000000fab9000 29744       4       net.minecraft.block.state.BlockStateContainer$StateImplementation::func_185897_m (9 bytes)
Event: 3399.456 Thread 0x000000000fab9000 nmethod 29744 0x00000000842d6210 code [0x00000000842d6360, 0x00000000842d63f8]
Event: 3399.706 Thread 0x000000000fac0000 29745       4       net.minecraftforge.common.ForgeHooks::canHarvestBlock (120 bytes)
Event: 3399.749 Thread 0x000000000fac0000 nmethod 29745 0x0000000085be10d0 code [0x0000000085be1540, 0x0000000085be3508]
Event: 3400.203 Thread 0x000000000fab3800 29746       4       net.silentchaos512.gems.util.SoulManager::getSoul (114 bytes)
Event: 3400.226 Thread 0x000000000fab3800 nmethod 29746 0x0000000084a94c50 code [0x0000000084a94ee0, 0x0000000084a96220]

**Comment by P3rf3ctXZer0** [comment]
[hs_err_pid440.log](https://github.com/SilentChaos512/ScalingHealth/files/3225776/hs_err_pid440.log)

My issue is only caused server-side. I have no issues client-side.

**Comment by DatrixTHLK** [comment]
It's fixed, I no longer crash at random times. I'll close this issue. if it happens again though I'll make sure to let you know. Thanks for fixing this.
