### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by DevTimur** [SilentChaos512/ScalingHealth#178]
https://pastebin.com/rrrqQ61J
Not sure if it's reported already. Google gave nothing.

**Comment by SilentChaos512** [comment]
Looks like WirelessInterfaceTerminal uses the same mod ID as WIT, which would be the cause of the crash. I hate when mods use abbreviated mod ID's like that... I guess I'll have to add a config to disable WIT support.

Also, follow the issue template next time you create an issue somewhere. They exist for a reason, even though I was able to get all the information from the crash report in this case.

**Comment by SilentChaos512** [comment]
I copied the missing classes into Scaling Health, so you shouldn't need to edit the config. If it still causes issues, search for "Enable WIT Support" in the main.cfg config file and change it to "false".
