### ISSUE TITLE
Difficulty meter doesn't reposition with the window size

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/ScalingHealth#179]
### Versions

- **Scaling Health**:  1.3.37+142
- **Silent Lib**:  3.0.13+167
- **Forge**:  14.23.5.2838
- **Modpack**: Custom

### Expected behavior

- For the difficulty meter to reposition according to window size.

### Actual behaviour

-  I have the meter set to 'Always display'. I had to reposition the difficulty meter to prevent an overlap with another mod's hud, but when shrinking the window size, it overlaps the hotbar. It seems like the difficulty meter doesn't reposition properly?
- Making the window size smaller also makes the word 'Difficulty' harder and harder to read.

### Links/Images

 ![2019-06-19_14 37 35](https://user-images.githubusercontent.com/12000593/59795233-6812dc80-92a0-11e9-8577-6b4184e10684.png)

### Steps to reproduce the problem

1. Set the difficulty meter to always display.
2. Reposition it to 148, -3
3. Try resizing the Minecraft window, making it smaller.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.

**Comment by WenXin20** [comment]
Yeah, no problem! I haven't used 1.12 in a long time anyways.
