### ISSUE TITLE
Right Clicking the Heart Keeps Giving Hearts

### ISSUE THREAD

**Issue by MCJediYoda** [SilentChaos512/ScalingHealth#18]
I updated to the latest version 1.11-1.0.4-42.  I am in Normal mode not creative.  I also tested in Hardcore.  I can continuously right click the Heart Container and keep getting hearts. I am using Forge 1.10.2-12.18.3.2239.

**Comment by SilentChaos512** [comment]
Thanks for reporting. Interesting that this doesn't crash the game, but still an easy fix.
