### ISSUE TITLE
[1.14.3] Health Configurations and Commands do not function correctly

### ISSUE THREAD

**Issue by docfail** [SilentChaos512/ScalingHealth#180]
### Versions

- **Scaling Health**: 2.2.0+17
- **Silent Lib**: 4.2.2+33
- **Forge**: 1.14.3 - 27.0.50 

### Expected behavior
Excerpt from config/scaling-health/dimensions/default.toml:
```
[player.health]
		#Player health and max health are unique to this dimension.
		localHealth = false
		#Starting player health, in half-hearts (20 = 10 hearts)
		startingHealth = 6
		#Allow Scaling Health to apply health modifiers. Heart crystals will not work if this is disabled.
		allowModification = true
		#EvalEx expression: On death, set the player's max health to this value. By default, there is no change.
		setOnDeath = "maxHealth-2"
		#The minimum amount of health a player can have (this can be lower than starting health)
		minHealth = 6
		#The highest max health a player can reach, not considering the vanilla
		# health cap and modifiers from other sources. 0 means 'unlimited'.
		maxHealth = 0
```
From this, I would expect that starting a new world after setting these configurations would result in starting with a health of 3 hearts. 

### Actual behaviour
Unfortunately, these settings do not start you out with 3 hearts of health, but rather the usual 10.
Furthermore, using the command `/sh_health set name value` wont set the player's health to the value input, but rather it seems to be along the lines of `actual health = the greater of(input health + 4, 20)`

### Steps to reproduce the problem
1. Install scalinghealth and silentLib as per version numbers listed.
2. Attempt to modify config files.
3. Create a new world.

**Comment by SilentChaos512** [comment]
Should be working correctly in 2.2.1. Health should update to match the value in the config in existing worlds.

**Comment by docfail** [comment]
Just tested it out. Everything seems to be in order. Thanks for the speedy fix!
