### ISSUE TITLE
ScalingHealth crashing 1.10.2

### ISSUE THREAD

**Issue by adeganStand** [SilentChaos512/ScalingHealth#182]
ScalingHealth 1.10.2-1.0.3-36 is crashing with SilentLib 1.10.2-2.1.5-63 running on Forge 1.10.2-12.18.3.2185.
The specific error message, after mod loading, says that Scaling Health is missing **SilentLib** 1.1.0 or above. From the look of both mods' Twitch pages, they're the most recent version, but according to SilentLib's FAQ it's an issue with Scaling Health's version.

**Comment by SilentChaos512** [comment]
Please update to the latest versions of both mods:
- https://www.curseforge.com/minecraft/mc-mods/scaling-health/files/2481753
- https://www.curseforge.com/minecraft/mc-mods/silent-lib/files/2447709

**Comment by adeganStand** [comment]
Oh dang!! I didn't realize that universal meant they were shared back to 1.10! Thank you so much man!!!
