### ISSUE TITLE
Crash when unlock a new stage with GameStages

### ISSUE THREAD

**Issue by Fireztonez** [SilentChaos512/ScalingHealth#184]
### Versions

- **Scaling Health**: 1.3.38+143
- **Silent Lib**: 3.0.13+167
- **Forge**: 11.12.2 - 4.23.5.2838
- **Modpack** (if applicable): Custom

### Actual behaviour
I execute the command `/gamestages add @p nuclearcraft`, and the pack froze for a second, with a chunk reload, something normal when you unlock a new stages, but, just after, the game crashes and the crash report look seam to point directly to SilentChaos512 ScalingHealth.

I try to reopen my game and load the world and I can't open the world anymore, the game instantly crash.

### Links/Images
**Crash report: https://gist.github.com/Fireztonez/934fa6c1d3e895f6de7baca747ff2a82**
**ScalingHealth Config: https://gist.github.com/Fireztonez/239a221dd4265185de8dd11e4542d5f4**

- 

### Steps to reproduce the problem
1. Stages somes things
2. Start your world, enjoy the view, because this is your last chance!!
3. Give your the Stages, in my case the stage `nuclearcraft`...
4- Wait about 2 second, and enjoy the crash!

**Comment by Fireztonez** [comment]
I think I understand the issue...
If I try to give me any gamestages how is not in the Scaling Health Config, the mod try to found the difficulty with that specific Stages and if is not set in the config, this will caused a crash...

I just add in my config file the nuclearcraft stage and I can now open back my world...

But, this is still an issue, it should not be needed to set a difficulty for all different stages... A stage can be used for lock only somes mobs, items or ores and other one for difficulty... This is what I want to do in my modpack, because I want to have a big amount of stages, how unloack somes little things at the time, and unlock with somes research, but each Game Stages will not necessary unlock in the same order for each player, so, adding difficulty for every Game Stages is 1- Annoying for nothing, 2- Will possibly caused difficulty to go up and down depending the order the player will choose to unlock things.

So, can you fixed that, question to make sure the game not crash and the player doesn't loose is difficulty number when unlocking stages not in the config

thank's

**Comment by Fireztonez** [comment]
Any idea if you will be able to fix that issue soon, because I work now on the staging part of my modpack, and this is a total pain to have to add each time for each stages in Scalling Health config... And this caused a lot of problem question of the good setting I want for my pack, so, I make a change how I know for the fact I will have to remove.

And, I'm now pretty mutch ready to send a new update to my testers... If I can have that fixed soon. it will be really nice.

Thank's

**Comment by SilentChaos512** [comment]
Uploading a new version now

**Comment by Fireztonez** [comment]
Thank's for the update!
