### ISSUE TITLE
Scaling Health causes damage indicators to show incorrect values by adding 1 more health to every mob

### ISSUE THREAD

**Issue by iWERTSQ** [SilentChaos512/ScalingHealth#186]
# Versions
- Scaling Health: ScalingHealth-1.12.2-1.3.38+143
- Silent Lib: SilentLib-1.12.2-3.0.13+167
- Forge: forge1.12.2-14.23.5.2838
- Modpack: Custom

### Expected behavior
- Current health should exactly be equal to the max health when mobs first spawn.

- For example: Sheep should spawn with 8 health and if they get hit 8 times by hand, they should die.

### Actual behaviour
- Current health when mobs first spawn is always 1 more than max health, which makes no sense. (9/8, 11/10 etc.)

- For example: Sheep should spawn with 8 health and have max of 8 health. Instead, they have 9 CURRENT HEALTH and 8 MAX HEALTH which makes no sense. You have to hit them 9 times instead of 8.

- No matter what mod that mob is from, this happens to every mob and causes damage indicators mods to show incorrect values of health.

- The issue has been tested with and without other mods and scaling health was the one that caused the problem only.

- Depending on what damage indicator you're using, there are 2 possible ways to see this issue:
    + Mods such as The One Probe will first show sheep's health as 8/8 but when they get hit 8 times, it will still show 0/8 and then if you hit one more time, the mob will die.
    + Mods such as ToroHud will show sheep's health as 9/8.

    Either way, scaling health causes damage indicators to fail.

### Links/Images

Some of the mobs to illustrate the issue (look at the top left corner to see the health values):
- https://i.hizliresim.com/lQZ94b.png
- https://i.hizliresim.com/VQD6Br.png
- https://i.hizliresim.com/nbl2yl.png

### Steps to reproduce the problem

    Install Scaling Health and any damage indicator mod. No need to change config.

**Comment by SilentChaos512** [comment]
This would be an issue with Damage Indicators. My guess is they are rounding up current health, but truncating (rounding down) max health. Note that health values in Minecraft are _not whole numbers_. This is also why you can see 0 health from TOP. The mod must be truncating health values. Either way there's nothing I can do to fix this.
