### ISSUE TITLE
[Suggestion] Reduced bonus health for spawner mobs

### ISSUE THREAD

**Issue by raindropworks** [SilentChaos512/ScalingHealth#187]
Not a bug, but something of an annoyance.  New to the mod and while I love the increased health, when I run across spawners it gets insane.  Facing up against 4+ skeletons each with 70+ hearts is insanity, even with non-vanilla armor and combat abilities that deal damage much faster.  One or two I could deal with, but more than that and I get killed within seconds.

I don't want to have to nerf a specific mob (even though so far skeletons are the worst, zombies are also somewhat annoying, and I imagine cave spiders will be a nightmare when they get their poison back) entirely, but something that reduces health X% based on what spawned them may be very useful.

**Comment by Cyborgmas** [comment]
Added this in the [2.3.10] - 2020-01-22 release, closing.
