### ISSUE TITLE
"Exception in server tick loop"

### ISSUE THREAD

**Issue by Wiral2** [SilentChaos512/ScalingHealth#190]
### Versions
1.12.2

- **Scaling Health**: <1.12-1.3.11-91>
- **Silent Lib**: <1.12-2.2.16-97>
- **Forge**: <14.23.5.2387>
- **Modpack** : Custom

Not 100% sure what causes this crash because it rarely happens. Here is the crash log:

https://paste.dimdev.org/ofovutoduv.mccrash

**Comment by SilentChaos512** [comment]
Those are some really old versions. Are you able to update?

**Comment by Wiral2** [comment]
Yeah I can try updating it and see if the problem still happens. Will the config file still stay the same?

**Comment by SilentChaos512** [comment]
The config file format is unchanged in 1.12
