### ISSUE TITLE
Cursed Heart and Enchanted Heart

### ISSUE THREAD

**Issue by Neobenmike** [SilentChaos512/ScalingHealth#191]
Cursed Heart and Enchanted Heart are missing 1.14.4

**Comment by SilentChaos512** [comment]
What do you mean by "missing"? The items are definitely being registered, they are even obtainable through drops in 1.14.

**Comment by Neobenmike** [comment]
It just won't appear, my difficulty is already at 92 and it still won't appear, I tried the command but it won't work as well. I then used JEI and both heart aren't either. Does the difficulty also affect the ender dragon?

**Comment by SilentChaos512** [comment]
That's odd. Do any items from Scaling Health appear? Like when you search for `@scalinghealth` in JEI?

If everything is missing, I might know the cause of that. Some mods can cause other mods to fail to load correctly, but don't crash the game. It's a Forge bug I reported recently. Not saying that's the issue for sure, but it's a very common one. Could explain the items being missing but difficulty still working.

**Comment by Neobenmike** [comment]
Only the two hearts are missing, I think? Here are the ones that show in JEI: Heart crystal and shard, Power crystal and shard, heart dust, bandages and medkit
