### ISSUE TITLE
my player can't die 1.12.2

### ISSUE THREAD

**Issue by nightmarezero5** [SilentChaos512/ScalingHealth#192]
the problem is when I want to receive damage from the mobs, nothing on the life bar is diminished, even if I put /kill, I can't die
The minecraft version is 1.12.2
the version of ScalingHealth-1.12.2-1.3.40 + 145
the version of SilentLib-1.12.2-3.0.13 + 167
the version of minecraft forge 14.23.5.2838

**Comment by SilentChaos512** [comment]
Any more information you can provide? I don't have anything to work with here.

For example:
- Do you have a log file? debug.log if possible
- What is your max health? Do you have other mods modifying your health?

**Comment by nightmarezero5** [comment]
Here is the debug.log, I have 44 life or it would be 22 hearts, I have no other mod that modify my health
[debug.log](https://github.com/SilentChaos512/ScalingHealth/files/3618779/debug.log)
