### ISSUE TITLE
[suggestion] Game Stages Compat

### ISSUE THREAD

**Issue by mxnmnm** [SilentChaos512/ScalingHealth#194]
Would it be possible to add an option where difficulty stops growing at a certain gamestage until you reach it.  After you get the gamestage it should then grows until it reaches another gamestage or it reaches the hard limit.  Maybe have this option also work where you can customize the base difficulty which is difficulty achieved by the passage of time and a leeway difficulty which is the amount that can increase due the to distance traveled.  This would be really nice for configuring material damage to be as balanced as possible.  Thanks!

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
