### ISSUE TITLE
Capabilities lost when returning from The End

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/ScalingHealth#195]
### Versions

- **Scaling Health**: 2.3.2 (dev)
- **Silent Lib**: 4.4.0
- **Forge**: 28.1.24
- **Modpack** (if applicable): N/A

### The Problem

Reproduced in dev. Capabilities are lost when players exit The End. For example, extra health is lost.

**Comment by Insane96** [comment]
Seems to happen even when dieing

**Comment by BentoGambin** [comment]
This bug persists on 2.3.13+40 :(

**Comment by Cyborgmas** [comment]
Okay, should get a fix out in the weekend
