### ISSUE TITLE
[Suggestion] Death Difficulty

### ISSUE THREAD

**Issue by TorinnTheDragon** [SilentChaos512/ScalingHealth#198]
I was wondering if I can suggest you change the config of "Lost On Death,"  by a percentage instead of a flat rate here is an example down below.

      Default Setting:
        S:"Lost On Death"=20.0  
    Example: Difficulty was at 250. Once you die the difficulty goes down to 230 when you respawn.

     Suggested Setting:
       S:"Lost On Death"=25%
    Example: Difficulty was at 250. Once you die the difficulty goes down to 188ish when you respawn.

**Comment by SonicX8000** [comment]
This is a neat idea, actually. I wonder if that could be done for sleeping as well.

**Comment by Cyborgmas** [comment]
For feedback, this was added in 1.14, will leave this open, might be ported eventually (will be long though).

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
