### ISSUE TITLE
Crazy in-world behavior rather than simple crash when Silent Lib missing

### ISSUE THREAD

**Issue by juliand665** [SilentChaos512/ScalingHealth#199]
### Versions

- **Scaling Health**: 1.14.4-2.3.3+23
- **Silent Lib**: _that's the thing_
- **Forge**: 28.1.39
- **Modpack** (if applicable): Custom

### Expected behavior

When Silent Lib is missing, Scaling Health cannot work at all. However, rather than notifying the user and/or crashing, it outputs a half-formatted exception to the log and causes very strange-looking behavior once in world (probably because the event buses shut down due to the setup failing).

### Actual behaviour

Letting the player know somehow that they messed up, ideally upon load rather than waiting until they open a world. Once that's done, simply crashing would be preferable to… whatever this is. I actually got an issue report on Spice of Life: Carrot Edition because someone thought we were the cause (that's the reason I'm here).

### Links/Images

[latest.log](https://gist.github.com/juliand665/6027e98a86335cc32ce7ae372b146d8f), for your enjoyment. The relevant section is right near the start.

The crazy behavior:
![Crazy Behavior](https://media.discordapp.net/attachments/631475456977272862/631476743445676043/unknown.png?width=1410&height=897)

### Steps to reproduce the problem

1. Add Scaling Health
2. Don't add Silent Lib
3. Enter a world

**Comment by SilentChaos512** [comment]
Seems to be a Forge bug. The log file shows Forge detecting a missing dependency, but it keeps running anyway. Nothing I can do about this.

**Comment by juliand665** [comment]
Huh, interesting. I suppose you could still call something from the lib so it crashes because it's not present, but yeah, this is really on forge.
