### ISSUE TITLE
Crash with Scaling health and Ignite Hud. 1.12.2

### ISSUE THREAD

**Issue by Sarelth** [SilentChaos512/ScalingHealth#203]
#169 # Versions
- **Scaling Health**: 1.12.2-1.3.42+147
- **Silent Lib**: 1.12.2-3.0.13+167
- **Forge**: 14.23.5.2847
- **Modpack** (if applicable): Custom
Was testing mod compatibility for a pack. Just have Scaling health, Silent lib, and Ignite hub installed. 

### Expected behavior
Ignite Hud should show and there should be no errors.

### Actual behaviour
Game loads fine, then when you try to enter a world, it completely crashes to desktop with
- The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/silentchaos512/scalinghealth/config/ConfigScalingHealth

as the message. 
[crash-2019-10-30_07.37.46-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/3789165/crash-2019-10-30_07.37.46-client.txt)

Crash report attached also.

### Links/Images

- 

### Steps to reproduce the problem

1. make new instance in Twitch, add Scaling health and ignite hud.
2. Load into game, create world.
3. Enter world.

**Comment by SilentChaos512** [comment]
Ignite HUD needs to update. Guess they aren't planning to based on how long it's been. See #143 and #140.

(edit) Forgot to include this: https://www.curseforge.com/minecraft/mc-mods/ignite-hud/issues/32

**Comment by Sarelth** [comment]
My bad, I thought I had searched it up here.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
