### ISSUE TITLE
Dimension Value Factor doesnt appear to actualy do anything

### ISSUE THREAD

**Issue by BlueYoshi68** [SilentChaos512/ScalingHealth#205]
### Versions

- **Scaling Health**: 1.3.42
- **Silent Lib**: 3.0.13
- **Forge**: 14.23.5.2825
- **Modpack** (if applicable): Eco-Bello (My own)
### Expected behavior

- Difficulty is supposed to increase by 10 upon going into the nether
- Here is the config
```
S:"Dimension Value Factor" <
                -1 +10.0
         >
```

### Actual behaviour

- It...doesnt.
- Read the above.

### Steps to reproduce the problem

1. Put this in the config 
```
S:"Dimension Value Factor" <
                -1 +10.0
         >
```
2. Repeat step 1
3. See step 2

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
