### ISSUE TITLE
Use difficulty by game stages as "base" difficulty, instead of fixed difficulty

### ISSUE THREAD

**Issue by TowardtheStars** [SilentChaos512/ScalingHealth#206]
This is a feature request, but really important.

### Versions
 

- **Scaling Health**: 1.12.2-1.3.42+147
- **Silent Lib**: 1.12.2-3.0.13+167
- **Forge**: 1.12.2-14.23.5.2847
- **Modpack** (if applicable): Custom, with Game Stage

### Expected behavior

It will be more convenient to use difficulty by game stages as a "base" difficulty for players. By adding it in getter of players' difficulty. If you would not to change this feature, could you please add an option for that?

Pretty please?

- 

### Actual behaviour

Difficulty will be fixed once there are entries in the list for compating game stage mod in this mod's config file. Even if players haven't been given a game stage inside the list or have no game stages at all, their difficulty values will not change by all means.

Even commands from this mod cannot modify players' difficulty.

- Difficulty
- Compatibility
- Game Stage

### Links/Images

- 

### Steps to reproduce the problem

1. Fill some entries in the list about game stages in config file
2. Run Minecraft with Scaling Health and Game Stage
3. Try to use command from this mod or any other means to change difficulty of players
4. Find out you cannot change difficulty anymore

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
