### ISSUE TITLE
[Suggestion] "Absorption Text Solid Color" config option & Text Resizing.

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/ScalingHealth#207]
Currently the "Health Text Solid Color" is shared for both Health & Absorb if set to SOLID so if one wishes to change their text for example... Health to Red & Absorb to a Light Blue... this would be impossible to do due to it being shared.

If there was a "Absorption Text Solid Color" config option... this would be possible to do.

On another note... could there be an option to resize the text size for Health & Absorb as well as fixing up the text resize for the difficulty bar? Like in this example image.
![](https://cdn.discordapp.com/attachments/377171551155650560/646168660766883840/scalinghealthtextscale.PNG)

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
