### ISSUE TITLE
Server crash during evaluation of GetBlightChance

### ISSUE THREAD

**Issue by Syndaryl** [SilentChaos512/ScalingHealth#209]
### Versions
- **Scaling Health**: ScalingHealth-1.14.4-2.3.3+23.jar
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44.jar
- **Forge**: net.minecraftforge:28.1.96
- **Modpack**: Custom

### Links/Images
- [crash-2019-12-09_20.36.55-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/3945029/crash-2019-12-09_20.36.55-server.txt)
- [crash-2019-12-10_08.23.48-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/3945024/crash-2019-12-10_08.23.48-server.txt)
- Common config file (.txt added for GitHub) [common.toml.txt](https://github.com/SilentChaos512/ScalingHealth/files/3945035/common.toml.txt)
- Client config file (again, .txt added for GitHub) [client.toml.txt](https://github.com/SilentChaos512/ScalingHealth/files/3945036/client.toml.txt)
- dimensions/default config file [default.toml.txt](https://github.com/SilentChaos512/ScalingHealth/files/3945040/default.toml.txt)
- I do not have any dimension-specific config files.

### Steps to reproduce the problem
This issue happens at random, with no obvious trigger behavior on my part or world interaction I can see (which does not surprise me - I presume the Blight check event fires periodically based on a timer or something).

**Comment by Syndaryl** [comment]
I just tested with Forge 28.1.99 and it crashes on launch with ScalingHealth in an ERROR state (although while Cooking For Blockheads is trying to initialize - I can't imagine what kind of interaction is going on *there*)

**Comment by SilentChaos512** [comment]
I may know what I did wrong here... What is your max difficulty set to in your config?

**Comment by phyne** [comment]
I'm having the same issue, with a default config maxValue = 250.0

**Comment by SilentChaos512** [comment]
In that case I have no idea what's going wrong here. Will probably need to add a bunch of logging statements to track this down.

**Comment by RuffertoNGroo** [comment]
Had similar issues with crash.  I edited the Client.TOML file: 
difficulty meter: Never 
Hearts.Absorption.text:  Disabled
hearts.absorption.icons: gold_outline
hearts.health.tanks: false
hearts.health.text: disabled
hearts.health.icons: vanilla

Scaling health now functions, will do further crash testing, but it looks like something may be conflicting over these settings?

**Comment by Syndaryl** [comment]
I have no idea how I missed the update on this issue, very sorry. I'm attaching my config files.


[scaling-health.zip](https://github.com/SilentChaos512/ScalingHealth/files/4019012/scaling-health.zip)

**Comment by phyne** [comment]
> 
> 
> Had similar issues with crash. I edited the Client.TOML file:
> difficulty meter: Never
> Hearts.Absorption.text: Disabled
> hearts.absorption.icons: gold_outline
> hearts.health.tanks: false
> hearts.health.text: disabled
> hearts.health.icons: vanilla
> 
> Scaling health now functions, will do further crash testing, but it looks like something may be conflicting over these settings?

This affected nothing for me, still crashing.

**Comment by dragon076** [comment]
I had a Similar problem with just starting a new single player world.
I had updated some mods and started to see this error:
```
Ticking entity
java.lang.NumberFormatException: null
at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.passive.fish.AbstractGroupFishEntity.func_70071_h_(SourceFile:75) ~[?:?] {re:classloading}
```
these are just snippets not the full log but each time over about 6 crashes during testing the "entity.passive.fish" part would change from being a bat or a zombie.
My solution was to update to the latest ver' and delete the config folder completly.

**Comment by Cyborgmas** [comment]
Yeah so in the latest update i added a blacklist for mobs that won't get turned into blight. I recommend for mods with a high number of mobs to add some to the blacklist. By default I put all the passive mobs, but I'll prob change it later once blights work 100%. Since the blacklist is called before getBlightChance it should reduce the chances of crashing. I'll have to check more in depth for a permanent fix.
