### ISSUE TITLE
Latest 1.10.2 crash on startup

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/ScalingHealth#21]
https://gist.github.com/P3rf3ctXZer0/ec87a53dc768205ccdbeb0b51a72b105

**Comment by Boolyman** [comment]
I'm getting the same error.

**Comment by jumpsplat120** [comment]
Also getting the same error

**Comment by SilentChaos512** [comment]
Seems that the latest 1.10.2 version of Silent Lib did not get one of the new classes somehow. I'll upload a fixed version immediately.

**Comment by jumpsplat120** [comment]
Did you get around to doing that? I still have the crash, and Curse didn't receive a new version.

**Comment by P3rf3ctXZer0** [comment]
Yeah its been fixed.

**Comment by jumpsplat120** [comment]
Well I still have the broken version then. (ScalingHealth-1.11.x-1.0.5-47) Could you let me know where to get the version that had the fix added to it?

**Comment by jumpsplat120** [comment]
My mistake, it is silentLib that needed to be updated.
