### ISSUE TITLE
Suggestion/Request - Difficulty reset compatibility for Bloodmoon (1.12.2)

### ISSUE THREAD

**Issue by katubug** [SilentChaos512/ScalingHealth#212]
### Suggestion
I am working on a hardcore-ish singleplayer modpack, and my hope was that I could set SH's difficulty to reset after a Bloodmoon event (from the Bloodmoon mod). I didn't see a way I could accomplish that with the existing options, so I thought I would make a suggestion!

If there's an existing way to do this, let me know! Thank you. :)

### Versions
- **Scaling Health**: 1.3.42+147
- **Silent Lib**: 3.0.14+168
- **Forge**: 2847
- **Modpack** (if applicable): Custom

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
