### ISSUE TITLE
Experience bar no showing xp level

### ISSUE THREAD

**Issue by KaIiguIa** [SilentChaos512/ScalingHealth#213]
### Versions

- **Scaling Health**:  1.14.4-2.3.8+34 and 1.14.4-2.3.6+32 
- **Silent Lib**:  1.14.4-4.4.0+44 
- **Forge**:  1.14.4-28.1.106
- **Modpack** : Custom

### Expected behavior
The experience bar should constantly show experience level  

### Actual behaviour
Experience level shows always after gaining a new level, but disappears after half a second. Version 1.14.4-2.3.3+23 does not have this problem

I don't have any mods that change health (except this), food, armor or exp bars

### Steps to reproduce the problem

1.Install the mod
2.Open the game
3.Gain some level

**Comment by Cyborgmas** [comment]
do you mean that you lose experience? or it just doenst show? like you can still use it to enchant.

**Comment by KaIiguIa** [comment]
Ok, i made a research:
No, i don't loose it, i can still enchant things, but the game tells me that i dont have enough xp.

Pics:
1. I gave myself some xp with command
2. I put pickaxe and enchanted book into an anvil 
3. They disappeared when i took enchanted  pickaxe
4. It spawned right beside the anvil
5. It had enchantment i wanted it to have
![2020-01-14_16 29 28](https://user-images.githubusercontent.com/59836494/72358055-4077db80-36ec-11ea-8594-9e5b67a5ea94.png)
![2020-01-14_16 30 39](https://user-images.githubusercontent.com/59836494/72358056-41107200-36ec-11ea-828b-487616ee3172.png)
![2020-01-14_16 30 44](https://user-images.githubusercontent.com/59836494/72358058-41107200-36ec-11ea-9e92-02ff7dda711d.png)
![2020-01-14_16 30 51](https://user-images.githubusercontent.com/59836494/72358052-3fdf4500-36ec-11ea-8a90-7472f8a94cf2.png)

![2020-01-14_16 31 00](https://user-images.githubusercontent.com/59836494/72358053-4077db80-36ec-11ea-8eab-ff6690b311c2.png)

**Comment by Cyborgmas** [comment]
okay, that is very weird. Thank you very much for the in-depth reporting! I'll fix it (soon-ish)
