### ISSUE TITLE
Toggle Difficulty Meter Display?

### ISSUE THREAD

**Issue by Yourname942** [SilentChaos512/ScalingHealth#214]
## Version

12.2.2

## What Should Be Added or Changed?
As a client I want to have a feature that lets me toggle the difficulty meter display via a configurable hotkey.

## Why Should This Be Done?

Rather than showing up after some arbitrary number of seconds, I would be able to view this information when I need or want to know the current difficulty.

**Comment by Cyborgmas** [comment]
this was added to 1.14 + versions

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
