### ISSUE TITLE
[1.12.2] Bug with Iguana Tweaks Reborn Poison option

### ISSUE THREAD

**Issue by pimalel233** [SilentChaos512/ScalingHealth#216]
## Versions
- **Scaling Health**:1.3.42+147
- **Silent Lib**: 3.0.13+168
OR
+ **Mantle 1.3.3.55

- **Forge**: 14.23.5.2838
- **Modpack**:  N/A
- **Optifine Installed**: Does not matter
- **IguanaTweaks Reborn: 1.4.20

## Expected Behavior
The health bar stays as one bar when poisoned.

## Actual Behavior
The health bar duplicates or second row above first one appears when posioned and IguanaTweaks Reborn has option below set to true.
misc
        # The poison effect will be changed to be deadly and drain hunger, but will damage the player 3 times slower
        B:"Alter Poison"=true

## Links/Images
Scaling Health only:
No poison: http://prntscr.com/qplp9p
Poisoned: http://prntscr.com/qplm87
No posion, custom hearth rendering off: http://prntscr.com/qploze
Custom hearth rendering off+poisoned: http://prntscr.com/qplmg5
*with Scaling Health, if health vanilla or lower, issue does not happen as long as Custom heath rendering is off

Mantle only (health increased with Scaling health, then uninstalled, if health is not higher than vanilla issue does not happen)
Not poisoned: http://prntscr.com/qplvz3
Poisoned: http://prntscr.com/qplw4q

Tried also with Mantle + Scaling Health (Rendering off so Mantle would handle wrapping up rows) and it still bugs out.

## Steps to Reproduce the Problem
1. Install mods mentioned in versions
2. Make sure poison option in IguanaTweaks in misc is set to true
3. Poison yourself

Would be great if 1.12 version could receive some kind of compatibility patch for this option. I tested it few times with everything off in IguanaTweaks and only posion on and it still happens. With the poison off and Hardness/Movement Restriction and rest of the misc section mostly on, so far have not seen it happening again.

I will be reporting it also on other mods pages.
SlimeKnights/Mantle#130
Insane96/IguanaTweaksReborn#97

Thanks for the great mods guys!

**Comment by Cyborgmas** [comment]
Looked at the other mod author's responses and mine is pretty much the same, I'm only working on 1.14 and this issue is too specific and complex to deal with. So, sadly, going to close this. Do want to note the awesome issue reporting you did, it is super detailed.
