### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by Vesyyy** [SilentChaos512/ScalingHealth#218]
Won't run on server, 
[crash-2020-01-26_21.03.50-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/4114353/crash-2020-01-26_21.03.50-server.txt)

**Comment by Cyborgmas** [comment]
Ok, next time post the complete bug report, but it was a quick fix, messed up a Dist value. The new version should be up in 2 min on curse. I can't test, so do respond here telling me it works properly now that would be great!

**Comment by Vesyyy** [comment]
Sorry, haven't reported or done anything like this before but it seems to be working fine now, thanks!
