### ISSUE TITLE
Fake Hearts

### ISSUE THREAD

**Issue by LIGITPICKLE** [SilentChaos512/ScalingHealth#219]
ScalingHealth-1.12.2-1.3.42+147.jar

RLCraft
No Optifine

I'm not sure what has caused it but when I log onto my server I keep getting "hit" by absolutely nothing and have 3 hearts that flicker in and out like they aren't there. I can't heal them and I have the sound effect and flinch from taking damage every few seconds or so.

![Scaling Health Bug](https://user-images.githubusercontent.com/46726946/74063053-498b5e00-49b5-11ea-8187-297dcb2319c3.gif)

**Comment by SilentChaos512** [comment]
Make sure the server and your client have the same config file. They must
match exactly.

**Comment by LIGITPICKLE** [comment]
How do I tell if they are the same files? They appear to be the same but I can't be sure. I have also just got someone to log into the server as well to see if it was just me but it appears to be server wide? If I had more accounts to test I would be able to tell better.

**Comment by SilentChaos512** [comment]
Easiest way would be to just copy one file over the other.

**Comment by LIGITPICKLE** [comment]
Doesn't seem to have changed anything. I'm still taking damage and still have those fake hearts.

**Comment by LIGITPICKLE** [comment]
I seem to have fixed it sort of. I removed the entire Sponge mod/plugin and every plugin I had on the server still one by one and it only seemed to be resolved when I completely removed Sponge.

**Comment by SilentChaos512** [comment]
Oh, I had forgotten about the Sponge bug. I guess they never fixed it.

**Comment by LIGITPICKLE** [comment]
Is there anything I can do to get it to work properly? If not then I am not sure if I can actually run any plugins on my server :P

**Comment by SilentChaos512** [comment]
No fix that I'm aware of, sorry

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
