### ISSUE TITLE
Clarification on Attack Damage Configuration

### ISSUE THREAD

**Issue by Boolyman** [SilentChaos512/ScalingHealth#22]
So the newly added Attack Damage configuration option is a huge improvement, thank you for following through on that like you said.  
My question is, does attack damage scale upwards like Health does?  Or is it a flat increase from day 1?  The configuration option seems to represent a flat increase, instead of a scaling amount that would increase with each difficulty level.   Either way, ill take what we can get, as this is a big help.... but was hoping it was something we could adjust the scaling of as difficulty increased.

**Comment by SilentChaos512** [comment]
Yes, attack damage scales upward with difficulty. It's roughly linear, but has some randomness thrown in, just like with health. Think of the new config option as the rate of change: the bigger the number, the faster attack power increases and the higher it can potentially get.

**Comment by Boolyman** [comment]
So the configuration starts at .1  which is 10%.... Does that mean that at max difficulty the mobs will have a total increase of 10%?  Or it goes up 10% per tick of difficulty?  Im just trying to understand... Im sorry if im being a pest.

**Comment by SilentChaos512** [comment]
No, I understand. I was a bit lazy with the value. The original code divides the value by 10 at the end (hence multiplying by 0.1). If I understand everything (keep in mind a good chunk of the code here was taken straight from Difficult Life), you could theoretically see hostile mobs with +12.5 attack on default settings and max difficulty, although a quarter of that is far more likely. Extra health is determined first, then that amount is subtracted from the difficulty. The remaining difficulty is the main factor in extra damage. So the +12.5 figure is assuming the smallest amount possible gets taken by extra health and the random factor is maxed out, which is very unlikely to happen.

If you want, you can view the code that determines health and damage increases [here](https://github.com/SilentChaos512/ScalingHealth/blob/master/common/net/silentchaos512/scalinghealth/event/DifficultyHandler.java#L61). The damage part specifically [starts here](https://github.com/SilentChaos512/ScalingHealth/blob/master/common/net/silentchaos512/scalinghealth/event/DifficultyHandler.java#L89).

I'm going to bed now, so I won't be able to respond until after work tomorrow. Hopefully that cleared things up (I know my explanations can be a bit poor), but let me know.

**Comment by Boolyman** [comment]
Thanks for taking the time to explain.
