### ISSUE TITLE
[1.14.4] Armor Causing Lag and Potentially Worse

### ISSUE THREAD

**Issue by Qsandas** [SilentChaos512/ScalingHealth#224]
- **Scaling Health**: 2.3.14
- **Silent Lib**: 4.4.0
- **Forge**: 28.2.0
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Mobs get stronger, better armor, enchantments, etc. as difficulty rises

## Actual Behavior
Well, They Get stronger, armor, enchantments and so on. All well and good. But as some of them hang around (quite noticeably the Blight enemies) things quickly bog down. I wouldn't bother making a report on just some lag, but this is far more than usual, and I think I found out why. I killed a blight enemy, and they dropped their armor, instantly relieving much of it. I pick it up, and this is what I see:

![Untitled](https://user-images.githubusercontent.com/12309371/74408347-0a13a600-4de9-11ea-822f-ddd59c06e63e.jpg)

At this point, I could see it becoming a massive problem to my world if just left alone, so I went ahead and killed all entities before anything worse happened, so I don't know how bad it could get, but I didn't feel like waiting around to find out.

## Steps to Reproduce the Problem

1.Raise difficulty 
2.let mobs stick around without despawning (possibly just blight mobs, not 100% sure)
3.Kill them and pick up the armor they drop

Edit: Quick note, The blacklist for Blight enemies seems to act like a whitelist. All the blight "enemies" I've encountered have been on the blacklist. I got that helmet off a blight salmon.

**Comment by Cyborgmas** [comment]
Damn I thought I fixed that bug already where I inverted the blacklist with a white list... and the blight salmon dropped the helmet? Wasn't sure about that either (if entities that can't where armor will still drop it), thanks for the bug report. I'll also have to change the enchantments. Major oops on my part, I'll try and eliminate some of the bugs this weekend.
