### ISSUE TITLE
Weird Health Display Bug With Classic Bars

### ISSUE THREAD

**Issue by Flypaste** [SilentChaos512/ScalingHealth#226]
## Versions
- **Minecraft**: 1.12.2
- **Optifine Installed**: Yes

## Expected Behavior
I turn off all the custom health rendering from Health Scaling and then Classic Bars takes over and displays everything

## Actual Behavior
Scaling Health hearts do not show up while health is full or regenerating HOWEVER AFTER TAKING DAMAGE the Scaling Health hearts show up above the classic bars for a few seconds until and after regeneration begins

## Links/Images
https://i.imgur.com/RDo9l5Q.png
https://i.imgur.com/vL49vYY.png
https://i.imgur.com/dpOx4l8.png

I'm working on a 1.12 modpack, so if you fix this I'd really like to see the fix make it into the 1.12 version :)

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
