### ISSUE TITLE
server ticking entity crash

### ISSUE THREAD

**Issue by ThoMax42** [SilentChaos512/ScalingHealth#228]
## Versions

- **Scaling Health**: ScalingHealth-1.14.4-2.3.14+41
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44
- **Forge**: 1.14.4-forge-28.2.1
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior

(mobs become more difficult to defeat when difficulity is raised)

## Actual Behavior

(
After entering a server with only forge, ScalingHealth and SilentLib instaled
Difficulty is raised using /sh_difficulty set @p 100     command
Server crashes moments after
)

## Links/Images

- (
[crep.txt](https://github.com/SilentChaos512/ScalingHealth/files/4225710/crep.txt)
)

## Steps to Reproduce the Problem

1.enter server and raise difficulty using  /sh_difficulty set @p 100 command or wait a suficient amount of time for it to raise by itself
2.server crashes due to a ticking entity few seconds later

**Comment by ThoMax42** [comment]
For anyone having the same issue: downgrading to ScalingHealth-1.14.4-2.3.3+23 solves it.

**Comment by Cyborgmas** [comment]
Sorry forgot to explain the issue. It's with the armored mobs, I'm doing something wrong so downgrading to 2.3.12 will solve it, in .13 i added the armored mobs
