### ISSUE TITLE
Limit Heart Canister drops

### ISSUE THREAD

**Issue by DennHenda** [SilentChaos512/ScalingHealth#23]
Could you add an option to prevent heart canisters from dropping from certain things such as mob spawners and breedable animals?

Also is there a way to reset difficulty on death? Possibly only if a mod like Iberia is installed?
Thanks

**Comment by SilentChaos512** [comment]
Preventing heart drops from non-hostiles will be very easy. I could also add a blacklist for more fine-tuning.
What sort of mob spawning system are you using? I know there are some issues with some auto-killers being recognized as a player.

I can add a way to reset difficulty as well. Probably a config where you set a number of "difficulty points" to lose when you die. Then you can just set that to your max difficulty (250 or whatever) to reset it completely.

**Comment by DennHenda** [comment]
As far as I know it's just the default Minecraft spawner, and we're not using any sort of machine to kill. Just a dungeon with a zombie spawner, and cutting their feet through a small gap.
It was set up for exp, but since hearts were​ dropping they just keep farming for them.

**Comment by SilentChaos512** [comment]
Sorry this has taken so long to get around to. I'm still not sure of the best way to limit heart drops from mob spawners, but I've taken care of the smaller stuff. I have some ideas for fixes, but I'm worried about them affecting other play styles. I'm one of those weirdos who normally doesn't build mob spawners. I guess that's why I always felt Difficult Life's default heart drop rate was too low.

**Comment by DennHenda** [comment]
I've currently got it set to only drop hearts from blights, which seems to be working for limiting the drops. I'd always assumed that mobs from spawners had a tag or something attached to them.
Looking forward to the difficulty decrease upon death.
Also, take your time, I understand how busy life can be. Your mods are awesome, I'm surprised they aren't at the top of the list.

**Comment by Winddbourne** [comment]
I just set things for only blights to drop hearts too. Came back here looking for information about heart crystal ore and reading this I want to also say good job! :)
