### ISSUE TITLE
Combat level system. I really need this for my modpack!

### ISSUE THREAD

**Issue by SupremeMarshal** [SilentChaos512/ScalingHealth#230]
## Version

- 1.12.2

## What Should Be Added or Changed?

- I don't need the difficulty tool or any other things beside the combat system below. If possible, an option to disable everything undesirable.

- First of all, I need the mod to work with forge 1.12.2 - 2768
It's for my modpack that work with cubic chunk.
Then I need to have instead of health level, it's combat level. Each combat level grant you health and damage bonus.
Damage bonus is equivalent to total health divided by 5.
Health regen is always healing player to 100% base health in 300 seconds.
Then, I want +1 health and + 2% health every level. Damage always follow health bonus by dividing by 5.

## Why Should This Be Done?

Because if you have nothing else to do. But I really want it. When I get the chance, I will be able to pay you for this.

**Comment by Cyborgmas** [comment]
This seems like you want an other mod completely. This is also a forum for suggestions not demands.
