### ISSUE TITLE
Additional Hearts Hidden Behind Armor Bar

### ISSUE THREAD

**Issue by Yourname942** [SilentChaos512/ScalingHealth#231]
## Versions
- Minecraft: 1.12.2
- Scaling Health: 1.12.2-1.3.42+147.jar
- Silent Lib: 1.12.2-3.0.14+168.jar
- Forge: 14.23.5.2847
- Modpack: The Land of Super Friends
- Optifine Installed: Yes

## Expected Behavior

I expect to see additional rows of hearts, even when I am wearing armor

## Actual Behavior

While wearing armor, the armor bar overlays on top of the additional heart rows.

## Links/Images
Without Armor: (looks fine)
https://oi1250.photobucket.com/albums/hh524/Yourname9422/2020-02-25_12.22.22_zpsdmj2wxyn.png

With Armor: (armor bar is on top of additional heart row)
https://oi1250.photobucket.com/albums/hh524/Yourname9422/2020-02-25_12.22.07_zpsii8edxgq.png

The weird thing is if I eat a golden apple or something that gives temp extra hearts, the armor bar doesn't overlay on the additional heart row, but once I lose those temp hearts, the armor bar overlays on the additional heart bar.
https://oi1250.photobucket.com/albums/hh524/Yourname9422/2020-02-25_12.25.28_zpssmthtima.png

Is there any way to make the armor bar always above the additional heart rows? I can only assume that if I had a 3rd heart row that the 3rd heart row would be above the armor bar.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
