### ISSUE TITLE
Crash to desktop with 2.4.1+44

### ISSUE THREAD

**Issue by BentoGambin** [SilentChaos512/ScalingHealth#234]
## Versions

- **Scaling Health**:2.4.1+44
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.2.0
- **Modpack**: Private
- **Optifine Installed**: Yes, (latest)

## Expected Behavior
Not aplicable

(Description here)

## Actual Behavior
Installed new version on a save made with previous version, after playing a bit it crashed to desktop
[crash-2020-02-26_15.31.48-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/4257555/crash-2020-02-26_15.31.48-server.txt)

## Steps to Reproduce the Problem
N.A.

**Comment by Cyborgmas** [comment]
Did you log back in after the crash and play again? I'm not quite sure what's causing this (if it's a one time thing or not...). Could you try that? If you crash again post the new log here (please use a paste site, don't give me a download). That would be very helpful.

**Comment by BentoGambin** [comment]
Ok, so i gathered some info. The pigman that made me crash was in the nether, and the crashed happened while I was in the overworld close to my nether portal (so it was probably loaded with the vanilla portal check thinghy [ I bet it's not relevant]). So I went to the nether and next to that position there was a blight pigman, but he also was a Infernal Mob from atomicstriker's mod.
About retrying to play... I might do that later, but I downgraded the version to the previous one and haven't crashed since (been playing for ~1h).
Here's the culprit maybe:
![2020-02-26_16 33 26](https://user-images.githubusercontent.com/41645690/75380580-0a667380-58b6-11ea-8838-0a4de738ea26.png)

**Comment by Cyborgmas** [comment]
okay great, tell me if you have any other crashes (preferably same version), because it seems to be a niche bug - as far as i can tell the riding entity was null, but the blight is a passenger entity not riding... so have no idea.

**Comment by Cyborgmas** [comment]
Hey, any update on this bug ? If you ahve not encountered it since ill be closng the issue

**Comment by BentoGambin** [comment]
Hey, brother. I'm now on 1.15.2, everything is working accordingly. Thanks for the concern! :)
