### ISSUE TITLE
AFK message when at Full difficulty

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#235]
## Versions

- **Scaling Health**: 1.14.4-2.4.1+44
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: 28.2.1
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/resolute
- **Optifine Installed**: Yes

## Expected Behavior

When at max difficulty, dont show afk message

## Actual Behavior

When at maximum difficulty the afk message is still displayed, saying I'll gain less difficulty overtime. Which is impossible because im already at max difficulty.

## Steps to Reproduce the Problem

1. use sh_difficulty command to set maximum difficulty
2. after 2mins (set in config) AFK message appears
3.

**Comment by Cyborgmas** [comment]
yep, did not account for that, bummer, thanks for the report
