### ISSUE TITLE
Blight Death, Blacklisting and Chat Spam

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#236]
## Versions

- **Scaling Health**: 1.14.4-2.4.1+44
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: 1.14.4-28.2.1
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/resolute-lite
- **Optifine Installed**: Yes

## Expected Behavior

No message to appear at all
Blacklisted mobs not to become Blight

## Actual Behavior

https://imgur.com/a/MyVhIA3

- (Link or file)
- (Another link or file, if needed)

## Steps to Reproduce the Problem

1. Just wait for a Blight mob to die
2. Chat gets the message
3.

**Comment by ghost** [comment]
seems the 'Actual Behaviour' got cut off?

when some Blight creatures die, such as squid or salmon, I get messages in chat saying
"Blight Salmon was slain by"

Because some entities die naturally, or if a death reason cant be determined then maybe the message should not appear?

I notice the config file has a blacklist for mobs that cant become blight - as you can see from the screenshot I get Salmon/Squid/Wandering Trader Blights - even tho they are blacklisted - the config is default - untouched by me

**Comment by Cyborgmas** [comment]
So you can deactivate the message if you choose (search notifyOnBlightDeath).

Also, you will need to update the config. I changed the logic and now old mob names no longer work. If you check, your names should have a capital so
[... , **Salmon**, **Squid**, ...]
But now it requires a minuscule (**salmon**) and _ for spaces (so **wandering_trader** will work)
Please test this and let me know

**Comment by Cyborgmas** [comment]
or you can copy my list here:
["bat", "cat", "chicken", "cod", "cow", "donkey", "fox", "horse", "mooshroom", "mule", "ocelot", "parrot", "pig", "rabbit", "salmon", "sheep", "tropical_fish", "turtle", "villager", "wandering_trader"]

**Comment by ghost** [comment]
I deleted the config and let it regenerate the default.  I thought it was weird it was showing Blight messages when the config says "#Notify everyone that a blight died in combat", and there was no combat, lol

I'll test it, but Im sure it'll be fine

**Comment by Cyborgmas** [comment]
yeah, i need to fix those messages too but just close the issue if it fixed it

**Comment by ghost** [comment]
all seems fine

thanks
