### ISSUE TITLE
1.14.4 Crash on World load.

### ISSUE THREAD

**Issue by mcenderdragon** [SilentChaos512/ScalingHealth#237]
It crashes.
ScalingHealth-1.14.4-2.4.2+46.jar
Forge 28.2.1

https://gist.github.com/mcenderdragon/86dfa51dcb17ca9c74d2b3bcbca133fd

**Comment by mcenderdragon** [comment]
Interestign enough: this only happenend once so far, after that I can load the world & play, ahppenend in single player.

**Comment by Cyborgmas** [comment]
best guess is the config had a problem loading... but dont know why or how

**Comment by Cyborgmas** [comment]
Pretty sure I now know the cause but have no real practical way to verify it (and I think I fixed it if I am correct). Have you ever had this bug since then? If not I will be closing the issue
