### ISSUE TITLE
Disabling ore gen does not work with SH 1.14.4-2.4.2+46.jar

### ISSUE THREAD

**Issue by rejahtavi** [SilentChaos512/ScalingHealth#238]
## Versions
- **Scaling Health**: ScalingHealth-1.14.4-2.4.2+46.jar
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44.jar
- **Forge**: 1.14.4-forge-28.2.0
- **Modpack**: N/A (Only SilentLib and SH installed for testing & it still occurs)
- **Optifine Installed**: Occurs with or without it

## Expected Behavior
It should be possible to disable oregen of both health crystal and power crystal ores.

## Actual Behavior
My `default.toml` 'item' section contains `oregen = false`, in the item.heart_crystal section, and I added it to the item.power_crystal section as well, but both heart crystal and power crystal ores continue to spawn, even in brand new worlds.

## Links/Images
Config: [https://pastebin.com/YV3Fk6Me](https://pastebin.com/YV3Fk6Me)
Things to note:
1. 'oregen = false' in health crystals
2. loading the game deletes 'oregen = false' from power crystals even if i provide it

## Steps to Reproduce the Problem
1. Install SilentLib and SH
2. Start up MC instance once to generate default config file
3. Configure "oregen = false" in the config file
4. Restart MC and Generate new world
5. Give yourself night vision + spectator fly around lower levels of caves and you'll find both ore types are still generating.

**Comment by Cyborgmas** [comment]
damn, oops that is my bad completely... I shouldn't have comitted that. The disabling of oregen does nothing currently... so this is normal behaviour... sorry for any problems caused

**Comment by Cyborgmas** [comment]
i'll have it working next version, can't make it work by dimension however

**Comment by rejahtavi** [comment]
Awesome.

Any chance of being able to control the mob drops and dungeon loot rates in the next patch as well?

What I'm trying to set up is having bonus health tied to the exp bar, plus a very rare chance for hearts to appear in dungeons. I'm trying to encourage exploration and survival; losing a big chunk of exp (and thus scaling health) will be the biggest penalty for death since I have a death chest mod as well.

Thanks!

**Comment by Cyborgmas** [comment]
You can control that already using vaniulla mechanics, datapacks. I encourage you to look up how to do so here: https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack .
You'll need the mod id, scalinghealth , and to look in github for the name of the loot tables you want to modify.

**Comment by Cyborgmas** [comment]
Implemented in latest version
