### ISSUE TITLE
1.14.4 Health boost does not work on a Server

### ISSUE THREAD

**Issue by mcenderdragon** [SilentChaos512/ScalingHealth#239]
## Versions

- **Scaling Health**: ScalingHealth-1.14.4-2.4.2+46.jar
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44.jar
- **Forge**: 28.1.1
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/stellar-expansion
- **Optifine Installed**: No

## Expected Behavior
Health scaling by XP & Crystals. But after eating 12 Crystals & gaining level 100 (commands) we got no boost. But instaed our health is reduced to 18.

All is happening on our multiplayer server.

https://pastebin.com/GCu5m6kX

**Comment by Cyborgmas** [comment]
Is this still the case or is it fixed in the latest version?

**Comment by mcenderdragon** [comment]
this was fixed arounf version 50.
