### ISSUE TITLE
InGameInfoXML HUD causing difficulty meter to vanish

### ISSUE THREAD

**Issue by Synngularity** [SilentChaos512/ScalingHealth#24]
I've come across what looks like a conflict between Scaling Health and the [InGame Info XML mod](https://minecraft.curseforge.com/projects/ingame-info-xml). When the InGame Info XML HUD is enabled the Scaling Health difficulty meter vanishes. Disabling the InGame Info XML HUD causes the difficulty meter to reappear. I have B:"Render Difficulty Meter Always"=true. All InGame Info XML settings are default.

It can be reproduced with the the following minimal setup (as of this post, the most recent versions of everything for Minecraft 1.10.2):
Minecraft 1.10.2 + Forge 12.18.3.2297
ScalingHealth-1.11.x-1.0.6-48.jar + SilentLib-1.10.2-2.1.3-58.jar
InGameInfoXML-1.10.2-2.8.1.89-universal.jar + LunatriusCore-1.10.2-1.1.2.38-universal.jar

Hopefully it's not too complex a fix. Let me know if you need any other information.

**Comment by Zer0Lyfe** [comment]
this is happening to me also but it only shows up in the F3 Screen but for 1.10.2
all recent versions as well
ScalingHealth-1.11.2-1.0.8-52 + SilentLib-1.10.2-2.1.5-63
InGameInfoXML-1.10.2-2.8.1.89-universal + LunatriusCore-1.10.2-1.1.2.38-universal

**Comment by SilentChaos512** [comment]
I don't think there's anything I can do to fix this. InGameInfoXML is canceling several overlay rendering events before they get to Scaling Health.
