### ISSUE TITLE
1.14 Cannot work in server, it crashed

### ISSUE THREAD

**Issue by hanerx** [SilentChaos512/ScalingHealth#240]
## Versions

- **Scaling Health**: 2.5.0+47
- **Silent Lib**: 4.4.0+44
- **Forge**: 1.14.4-28.2.0
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Load the mod, run the server.

## Actual Behavior

Crashed during loading.

## Links/Images

- https://gist.github.com/hanerx/7b0b0ee9e0457e3fb82b990b692fc882

## Steps to Reproduce the Problem

1. run the 1.14 server once
2. put the mod into mods folder
3. run it again

**Comment by Cyborgmas** [comment]
That is very possible huh. The log you provided gives me nothing, you should have a crash.log but i am assume thats what you gave me? and the latest.log also could help?

**Comment by hanerx** [comment]
latest.log: https://gist.github.com/hanerx/19d610dab794504efee9b85cc2d1f332
I'm sorry but I cannot find crash.log in my server folder, only I can find is this latest.log

**Comment by Cyborgmas** [comment]
It seems it did not generate the file config automatically, can you check that in your server, in config/scalinghealth/ you have a "game_settings.toml" file

**Comment by hanerx** [comment]
Strangely, I did not have this file in config folder, my config folder is like this:
![image](https://user-images.githubusercontent.com/31791623/77248628-e3f9e500-6c75-11ea-8762-c5a4b0b55a2d.png)
Should I delete all files and generate them again?

**Comment by Cyborgmas** [comment]
No, add one manually (empty) and see if it launches then. After, if it launched check if it is empty or not

**Comment by Cyborgmas** [comment]
Actually I use a folder, maybe that is why. Create an empty folder called scaling-health and see if it runs first.
There should be a common.toml and a game_settings.toml

**Comment by hanerx** [comment]
Oh, that works. The error disappeared. Thanks.

**Comment by 90sPixelDev** [comment]
I have the same issue, I attempted to do the empty folder but not dice just  get a hanging mojang loading screen. Unlike him though I do have a scalinghealth-client.toml file that creates itself in the config file though
[crash-2022-02-16_01.59.13-fml.txt](https://github.com/SilentChaos512/ScalingHealth/files/8077560/crash-2022-02-16_01.59.13-fml.txt)
[latest.log](https://github.com/SilentChaos512/ScalingHealth/files/8077563/latest.log)

I attached both my crash report and my latest log for reference.
.
