### ISSUE TITLE
Scaling Health (scalinghealth) has failed to load correctly - null

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#241]
## Versions

- **Scaling Health**: 3.5.0+47
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.2.3
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Getting to the Main Menu

## Actual Behavior

Getting this error

## Links/Images

- Pic: ![bild](https://user-images.githubusercontent.com/48165318/77255323-ce30f380-6c66-11ea-9974-793d7ac98b4e.png)

- Log: https://paste.dimdev.org/reqagonewo.md

## Steps to Reproduce the Problem

1. Use the same unnamed modpack
2. Launch it
3. Get the issue

**Comment by Cyborgmas** [comment]
See #240 , same problem (and guide to fix it)
