### ISSUE TITLE
version +47 config not found crash

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#242]
## Versions

- **Scaling Health**: 1.14.4-2.5.0-47
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: 28.2.1
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Minecraft to load and not crash

## Actual Behavior

Minecraft crashes before getting to titlescreen
The weird thing is the Crashlog says its CookingForBlockheads trying to initialize. But the Latest.log shows lots of ScalingHealth config errors
When I remove ScalingHealth my modpack loads

Using just Forge and ScalingHealth, I get a screen that says "ScalingHealth failed to load correctly"
[https://imgur.com/a/Ju3ncif](https://imgur.com/a/Ju3ncif)

## Steps to Reproduce the Problem

1. delete old config folder
2. install new version of scaling health v 2.5.0+47
3. wait for crash

It seems if there is no config folder (ie: a clean install) then it crashes?

[Latest.log](https://pastebin.com/HuLGJXec)

**Comment by Cyborgmas** [comment]
Yep, thought the new folder would be auto installed, was wrong (oops) see how to fix in #240  (it is simple)
