### ISSUE TITLE
Request for 1.15.2 

### ISSUE THREAD

**Issue by BunCat09** [SilentChaos512/ScalingHealth#243]
## Version

- 1.15.2

## What Should Be Added or Changed?

- nothing, just a version update

## Why Should This Be Done?

- Just to be able to play version 1.15.2 . The games performance is better than older versions now. So it will be more playable with mods.

**Comment by BunCat09** [comment]
Hello...  Anybody there... ??

**Comment by Cyborgmas** [comment]
I usually only respond if I have more questions for you. Your request was pretty clear, so I did not respond

**Comment by BunCat09** [comment]
Oh, ok but will there be an update ?
Thanks.

**Comment by Cyborgmas** [comment]
So should have been more precise, but I do not generally give ETA's. However, I am working on 1.15 yes

**Comment by BunCat09** [comment]
Thank you for the information. ScalingHealth has been a must have mod for me for some time. Keep up the good work 💪👌
