### ISSUE TITLE
[1.12.2] Possible Damage Reduction bug with High Armor & If damage taken is scaled?

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/ScalingHealth#244]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 4
AttributeFix-1.12.2-1.0.8
jei_1.12.2-4.15.0.291
ScalingHealth-1.12.2-1.3.42+147
SilentLib-1.12.2-3.0.13+167

There might be some kind of bug with the damage source scaling when you have too much armor & other damage reductions although I managed to get it with just Armor alone. 

Taking damage from a cactus which deals 1.0 damage with no scaling.

0 Armor -> 1 Damage
255 Armor -> 0.2 Damage
65535 Armor -> 0.2 Damage

-----

cactus on Zonic_Tonic: 1.0 -> 601.00006 (scale=20.0, affected=30.000002, change=600.00006)
0 Armor -> 601 Damage
255 Armor -> 0 Damage
65535 Armor -> 120 Damage

0 damage with 255 Armor but 120 damage with 65535 Armor?

-----

cactus on Zonic_Tonic: 1.0 -> 1201.0001 (scale=20.0, affected=60.000004, change=1200.0001)

0 Armor -> 1201 Damage
255 Armor -> 0 Damage
65535 Armor -> 240 Damage

A closer look it seems that it sets it to 1/5 of the damage.

=====

I am aware that reaching such high armor values is very... VERY unlikely but I've already ran into this when using other mods where Damage Reduction from Armor just... breaks. Such mods would be Potion Core, Quality Tools, Living Enchantment, RPG Inventory, etc. which has some modded damage reductions and depending on how much of those you have will affect the cap for Armor. I was able to hit this hidden cap with roughly 80+ Armor alongside some other modded reductions that I mentioned above.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
