### ISSUE TITLE
Was wondering if this mod is compatible with SAO UI Mod?

### ISSUE THREAD

**Issue by Ohioman12** [SilentChaos512/ScalingHealth#247]
The game will launch with them but for some reason in game your mods UI overrides the SAO UI mod and looks off. Just curious if there is a fix for this or would you need to make a patch for it? I'm playing with the 1.12.2 versions of each of those mods.

**Comment by Cyborgmas** [comment]
In the configs there should be an option to deactivate the SH UI. There is one in 1.14 but I do not know if exists in 1.12

**Comment by Ohioman12** [comment]
I'll try and check that if i can find one.

**Comment by Cyborgmas** [comment]
Closing this issue, if it wasnt there nothing i can do for 1.12
