### ISSUE TITLE
Mobs health changes rapidly

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#248]
## Versions

- **Scaling Health**: 1.14.4-2.5.2+50
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: 28.2.1
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior

Mobs to maintain health level

## Actual Behavior

after spawning several mobs, llamas, donkeys, husks etc, Neat mod and The One Probe show the mobs are rapidly changing current/maximum health values

They seem to be regenerating health, as it took quite a few punches to kill a fish

## Links/Images

[65mb video clip](https://1drv.ms/u/s!ArSGAcC04KWsoRRwAJ4-7i6e64-F?e=TKb6lh)

## Steps to Reproduce the Problem

1. spawn mobs
2. watch Neat/The One Probe for mob health
3.

**Comment by DoriDori308** [comment]
I have the save problem :<
The mobs keep healing when difficulty above 0 and their max heal change repidly

**Comment by Cyborgmas** [comment]
Could you test with latest verison of SH and latest forge? i am not able to reproduce the problem

**Comment by ghost** [comment]
with Forge 28.2.3/Scaling Health 1.14.4-2.5.2+50
Use the sh_difficulty command to set difficulty to 10 and the mobs in my world have the health changing problem, all the mobs, chickens, spiders,pigs, sheep etc 

it seems if difficulty is above 0 it happens

**Comment by Cyborgmas** [comment]
yup messed up was checking in 1.15.2 ... anyway fixed it, the new version is on curse
