### ISSUE TITLE
[1.15.2] Question about Difficulty System

### ISSUE THREAD

**Issue by TheUntamed** [SilentChaos512/ScalingHealth#249]
Just a little question:

If I disable the difficulty system the config says everything will have 0 difficulty.
Does that mean the default server difficulty that it would be without this mod installed (like "EASY", "NORMAL", "HARD")
or does it mean something else?
"0 difficulty" sounds like everything is easier than normal. Just like peaceful.

**Comment by Cyborgmas** [comment]
Yeah 0 difficulty is purely scaling health related. Vanilla's difficulty system will still be functional
