### ISSUE TITLE
Damage modifier not changing mob damage (1.10.2)

### ISSUE THREAD

**Issue by Needmoremods** [SilentChaos512/ScalingHealth#25]
Vanilla mob damage is seemingly unchanged in version 1.10.2 when difficulty is set to distance from spawn (tested at 16,000 blocks away from spawn and although difficulty per block was modified, it was not zero and a clear hp increase was observed).

**Comment by SilentChaos512** [comment]
Make sure you are using the latest versions of Scaling Health and Silent
Lib. For MC 1.10.2, you need the latest 1.11.x version of SH and the latest
1.10.2 version of SL.

**Comment by Needmoremods** [comment]
Hi, I have now tried that, but only with zombies. It seems to still hit three damage at all ranges. I did have to update my SH to the latest but unfortunately that did not seem to work. I attempted changing difficulty values and tried at both minimum and maximum difficulty values. 

Note that I did try turning on and off difficulty per time whilst raising both values for damage modifier and difficulty per time but that did not seem to work. I have not tested anything other than standard zombies and spiders (They hit 3 and 2 at both 0, 1000 and 10,000 despite the massive hp increases).

Regards

**Comment by SilentChaos512** [comment]
Okay, I'll take a look at it when I get a chance. It might just be that the
increases are too small to see by only looking at hearts.

**Comment by SilentChaos512** [comment]
Did a bit of testing and it does seem like the damage modifier has gone missing. Even on max difficulty, there's nothing there.
(edit) No, it's definitely there. It's not showing up on the tool I normally check with, but zombies are hitting me for 25+ hearts with the damage modifier set to 1 and difficulty at 250.

**Comment by Needmoremods** [comment]
Hi, thanks for the testing! I'm going to try test again when I have time with the values you have specified above and I'll let you know. 

Best

**Comment by Needmoremods** [comment]
So I've also gotten it to work, although it seems I can't change damage modifier for the mobs but simply the max difficulty etc.. at least through the ingame config. Seems that all works fine. Thanks!
