### ISSUE TITLE
Rapidly changing health for mobs 1.15.2

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#250]
## Versions

- **Scaling Health**: ScalingHealth-1.15.2-3.0.1+49
- **Silent Lib**: 1.15.2-4.6.0+48
- **Forge**: 31.1.36
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Mobs to not have rapidly changing health
similar to issue #248 

## Actual Behavior

Mobs health rapidly changes. Seems to just be Villagers and Wandering Traders
All configs are default, even at difficulty 0 this happens

## Links/Images

- (Link or file)
- (Another link or file, if needed)

## Steps to Reproduce the Problem

1. spawn villager/trader
2. watch the health rapidly go up and down
3.

**Comment by Cyborgmas** [comment]
Should be fixed, the update is on curse
