### ISSUE TITLE
1.14.4 EXP Health Scaling on re-log when disabled

### ISSUE THREAD

**Issue by Qsandas** [SilentChaos512/ScalingHealth#251]
- **Scaling Health**:  2.5.3+51
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.2.3
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Well... Nothing. Nothing is what I expected.

## Actual Behavior

It's me again, back with another bug. Whenever I log out of a level and back in, even when Health scaling by Exp is disabled, I log back in with my health adjusted for my current Exp level. Took me the longest time to find this one and even longer to figure out the cause due to the fact that I usually store all my Exp in an item or block when not enchanting.

## Links/Images
Before logging out:
![image](https://user-images.githubusercontent.com/12309371/78734399-07bb5d00-78fd-11ea-80fd-8ce9bf745221.png)

After logging back in:
![image](https://user-images.githubusercontent.com/12309371/78734711-d2633f00-78fd-11ea-95ec-b32f740cc804.png)

## Steps to Reproduce the Problem

1. Disable Health Scaling by Exp.
2. Log out of the world with at least 3 levels.
3. Log back in.

Edit: I'll test to see if setting the configs to 0 health gain will stop the problem for now
Edit2: Ok, so setting it to 0 doesn't work, however, you can set it to require 999 levels, effectively locking it out.

**Comment by Cyborgmas** [comment]
huh strange, and you said that making levels give 0 hp does not work ? how so ? how many hearts do you get in that case

**Comment by Qsandas** [comment]
If I set the value to 0, it resets on game startup to the default 1 per 3 levels.

**Comment by Cyborgmas** [comment]
Oh yeah my bad i did design it that way. Only way to deactivate is via config, so gonna fix that bug.

**Comment by Cyborgmas** [comment]
So closed the 1.15.2 version of the bug, it is a quick fix but sadly am out of time currently. Expect a fix in the next day or so

**Comment by Cyborgmas** [comment]
Fixed in 2.5.4
