### ISSUE TITLE
Backport Heart Crystals giving extra max health to pets to 1.12

### ISSUE THREAD

**Issue by NyanMC** [SilentChaos512/ScalingHealth#252]
## Version

any should work, i personally use 1.12 but i know the frequently updated versions are currently 1.14 and 1.15 so it's up to all of you for which versions this applies to if you do take this suggestion

## What Should Be Added or Changed?

the ability to use a heart container on a pet by shift-right clicking them

## Why Should This Be Done?

i personally find it extremely annoying that the max health of a pet is tied to the difficulty of the world when they first spawned and that you can't upgrade their health in any way. this means that if you're overly attached to one of your pets, you need to start leaving them inside when their max health is 50 and the max health of everything else is 500, especially if damage also scales. i understand if you decide not to do this for some other reasons, but it would be nice if you could consider it.

**Comment by Cyborgmas** [comment]
I have already added this in 1.14+! Going to leave the issue up for 1.12 for an eventual (but very unlikely) backport!

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
