### ISSUE TITLE
Difficulty can go below minValue

### ISSUE THREAD

**Issue by WindFox** [SilentChaos512/ScalingHealth#253]
## Versions
- **Scaling Health**: 3.0.2+51
- **Silent Lib**: 4.6.0+48
- **Forge**: 31.1.41
- **Modpack**: Mangocraft
- **Optifine Installed**: No

## Expected Behavior
Difficulty not drop below minValue.

## Actual Behavior
I checked and had a difficulty of -103 while the minValue is set to 0.0

## Steps to Reproduce the Problem
1. Set onPlayerDeath = "difficulty - 10.0"
2. Die a whole bunch in a row.
3. Wonder why the meter wont move even after using cursed hearts.
4. Check playerdata.
5. Shocked pikachu face.

**Comment by Cyborgmas** [comment]
fixed it is up on curse
