### ISSUE TITLE
hearts increasing, dont know why?

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#254]
## Versions

- **Scaling Health**: 1.15.2-3.0.3+52
- **Silent Lib**: 1.15.2-4.6.0+48
- **Forge**: 31.1.44/45
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior

The hearts not to increase

## Actual Behavior

so this is a bit weird.  I started a new world, spawned some zombies in, killed them, got 7 xp levels.
I loaded the world and I gained 2 extra hearts
this happened on 2 brand new survival worlds

Ive set xpAddHealth to False and cannot figure out why im gaining hearts? Is there a config option Im missing?

## Links/Images

- (Link or file)
- (Another link or file, if needed)

## Steps to Reproduce the Problem

1. create a new world, spawn some mobs, kill them
2. reload the world a couple of times
3. hey Presto, extra hearts

**Comment by Cyborgmas** [comment]
Same as #251 gonna have to fix that. You can disable it by setting the xp level requirement to 999 in game_settings.toml (dont put the one in common.toml to false)

**Comment by Cyborgmas** [comment]
Fixed in 3.0.4
