### ISSUE TITLE
Compatibility issue with gokiStats mod

### ISSUE THREAD

**Issue by malomaster** [SilentChaos512/ScalingHealth#255]
## Versions

- **Scaling Health**: 1.3.42+147 for 1.12.2
- **Silent Lib**: 3.0.14+168
- **Forge**: 1.12.2-14.23.5.2847
- **Optifine Installed**: Yes 

## Problem description

As you may know, "gokiStats" mod increase player's stats trough upgradeable "skills" — damage, max health, run, mine, chop, swim, smelt speed, resistance to damage dealt by mobs, fire, explosion, fall and so on. And there is an issue — if you try to level up "Health" skill to increase player's MaxHealth with your "Scalable health" mod active, your mod just blocks any player's MaxHealth manipulation, so "Health" skill from "gokiStats" just become useless. And I think this problem also may appears with other mods that manipulates player's MaxHealth.
So can you somehow allow other mods to modify player's MaxHealth?

**Comment by Cyborgmas** [comment]
Sadly i do not dev the 1.12 version so this bug won't be adressed any time soon

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
