### ISSUE TITLE
1.15.2 Purple Fire for Blight Mob

### ISSUE THREAD

**Issue by xd4rkzghost01** [SilentChaos512/ScalingHealth#256]
## Versions

- **Scaling Health**: ScalingHealth-1.15.2-3.0.3+52
- **Silent Lib**: SilentLib-1.15.2-4.6.0+48
- **Forge**: forge-1.15.2-31.1.46
- **Modpack**: N/A (I build it myself but all mod are from Curseforge)
- **Optifine Installed**: Yes, _preview_OptiFine_1.15.2_HD_U_G1_pre13_ along with 
_OptiForge-MC1.15.2-0.1.8_ and _MixinBootstrap-1.0.2_

## Expected Behavior

Blights mob can spawn and have particles effect and a nice purple fire around them.

## Actual Behavior

Blights mobs still spawn, have particles effects BUT the nice purple fire dont appear. I can't find where in the config, common or the client where to edit it. Im pretty sure that a behavior with Optifine but even in with NBTExplorer i can't find what cause the issue.

## Links/Images

- I know its not clear but you can barely see a particle on the creeper in front of me. (and the one on the back is a blight too but i cant get near or ill die loll)
![2020-04-18_19 34 57](https://user-images.githubusercontent.com/63568312/79676967-b2fbca00-81b9-11ea-8953-3a5d60720d3b.png)

-  This is the last logfiles
[2020-04-18-3.log](https://github.com/SilentChaos512/ScalingHealth/files/4498148/2020-04-18-3.log)

- This is the ScalingHealth files i have (Edit in .txt to be load here)
[Client_file.txt](https://github.com/SilentChaos512/ScalingHealth/files/4498199/Client_file.txt)
[Common_files.txt](https://github.com/SilentChaos512/ScalingHealth/files/4498200/Common_files.txt)
[games_settings_files.txt](https://github.com/SilentChaos512/ScalingHealth/files/4498201/games_settings_files.txt)

### Mods List
![2020-04-18 (2)](https://user-images.githubusercontent.com/63568312/79677288-a4afad00-81bd-11ea-824a-1d53d3979415.png)

**Comment by Cyborgmas** [comment]
Ah, yes this is normal, hopefully you did not spend too much time debugging this. Rendering changed in 1.15 and i still can not get the rendering to work. This was included in the changelog so take a look at those from time to time (i put usefull stuff in their, for real :D)

**Comment by Cyborgmas** [comment]
It is done!
