### ISSUE TITLE
Upon death, extra hearts are added from the mod Spice of Life

### ISSUE THREAD

**Issue by Camawama** [SilentChaos512/ScalingHealth#257]
#Versions

- Scaling Health: ScalingHealth-1.15.2-3.0.3+52.jar (latest)
- Silent Lib: SilentLib-1.15.2-4.6.0+48.jar (latest)

- Forge: forge-31.1.44
- Modpack: My own modpack https://www.curseforge.com/minecraft/modpacks/vanilla-plus-by-cama
- Optifine Installed: No

 Expected Behavior
I should be able to die without gaining hearts

## Actual Behavior
Whenever I die, the amount of extra hearts I have from the spice of life mod duplicates and I gain even more hearts

## Steps to Reproduce the Problem

1. Run my modpack (Vanilla Plus)
2. Eat some new foods so you gain extra hearts
3. /kill (as many times as you want)
4. Observe the fact that you now have more permanent hearts

**Comment by Cyborgmas** [comment]
So for now you can use the commands to set your hp correctly ( /sh_health)

**Comment by Camawama** [comment]
I run a server for friends and everyone is constantly dying so it may be hard to keep track. I will definitely be using this mod if compatibility is added for Spice of Life though. I told my friends no matter what I'll get it working

**Comment by Camawama** [comment]
I should also mention that the mod is not currently installed on the Modpack for this very reason which makes me wonder if I even should have linked my Modpack there. Sorry about the confusion!

**Comment by Camawama** [comment]
Any update on this? Sorry to be a bother but I really can't wait to add this mod to the Modpack!

**Comment by Cyborgmas** [comment]
Not much, will get around to it eventually, have some other projects to work on

**Comment by Camawama** [comment]
Sounds good, thank you

**Comment by Cyborgmas** [comment]
Should be fixed in latest

**Comment by Camawama** [comment]
thank you!
