### ISSUE TITLE
[1.15.2] setOnDeath doesn't lose X heart(s) when dying

### ISSUE THREAD

**Issue by mr-poyo** [SilentChaos512/ScalingHealth#258]
## Versions

- **Scaling Health**:  ScalingHealth-1.15.2-3.0.3+52.jar
- **Silent Lib**: SilentLib-1.15.2-4.6.0+48.jar
- **Forge**: 31.1.49
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

Lose 1 heart on death until minHealth value.

## Actual Behavior

In the config file I have it set to setOnDeath = "maxHealth - 2" with a maxHealth of 60, but when I die I am gaining 2147483648 hearts (thus maxHealth).

## Links/Images

- https://imgur.com/su8ANxY
![ScalingHealth-1](https://user-images.githubusercontent.com/11811815/80291347-bc6fce00-8787-11ea-8b21-6c058b80edbc.PNG)

- https://imgur.com/kz4iL5n
![ScalingHealth-2](https://user-images.githubusercontent.com/11811815/80291355-cb568080-8787-11ea-9bab-ddc7eff98dd7.PNG)
- game_settings.toml: https://pastebin.com/xYx3cnVR

## Steps to Reproduce the Problem

1. /sh_health set @p 24 
2. /kill

**Comment by Cyborgmas** [comment]
So you seem to have set crystal increase to 0 in your config... could you set it to 1 and tell me if it works then?

**Comment by mr-poyo** [comment]
That seemed to have fixed it! 

I set it to 0 as I was trying to disable the use of the heart crystal. I'm trying to make a command-block reward where you can only gain hearts through /sh_health add and then lose said heart(s) when you die.

But after testing, I can just make the exp requirement for using the Heart Crystal 999. Thank you!!
