### ISSUE TITLE
Cats don't have scaling damage

### ISSUE THREAD

**Issue by mxnmnm** [SilentChaos512/ScalingHealth#259]
Version - 1.12.2 (not sure if this would apply to later versions also as well)

## What Should Be Added or Changed?
Cats should have their damage scale up. Currently rats from the rats mod get scaled up damage-wise and it ends up with rats easily killing cats.

## Why Should This Be Done?
It doesn't make sense for a cat to get rekt by a plain, old, nonupgraded rat.

**Comment by Cyborgmas** [comment]
I would think it is possible to add any mob to the damage scaling. Since this is 1.12, I won't be fixing this issue. There is always a possibility in the future that Silent checks these at some point

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
