### ISSUE TITLE
1.15.2 Getting Random Health

### ISSUE THREAD

**Issue by xd4rkzghost01** [SilentChaos512/ScalingHealth#260]
## Versions

- **Scaling Health**: ScalingHealth-1.15.2-3.0.3+52
- **Silent Lib**: SilentLib-1.15.2-4.6.0+48
- **Forge**: forge-1.15.2-31.1.50
- **Modpack**: N/A
- **Optifine Installed**: Yes, preview_OptiFine_1.15.2_HD_U_G1_pre13 along with
OptiForge-MC1.15.2-0.1.8 and MixinBootstrap-1.0.2

## Expected Behavior
Starting with 20 health (10heart) and get health by gaining heart container.

## Actual Behavior
As i play everything is normal. Im leveling, getting exp. and heart container. 
BUT Sometimes, when i log off and re-log in, i gained 2-3 "perma-heart" (call them like this ^^') and sometimes when i sleep trought a night im getting like 4-5 health. Can't find a solution. Look pretty similar to the issue #202 but even if i change some (or a lot) of numbers in the config files, it does nothing.
Help ?

## Links/Images
Cant really post a screenshot. But theres my mod list
![Mods](https://user-images.githubusercontent.com/63568312/80322303-2b820c80-87f2-11ea-90a6-b161f8755e7a.png)

## Steps to Reproduce the Problem (Log and config files)
From Scaling Health
[client.txt](https://github.com/SilentChaos512/ScalingHealth/files/4536417/client.txt)
[common.txt](https://github.com/SilentChaos512/ScalingHealth/files/4536418/common.txt)
[game_settings.txt](https://github.com/SilentChaos512/ScalingHealth/files/4536419/game_settings.txt)
My latest Log
[latest.log](https://github.com/SilentChaos512/ScalingHealth/files/4536429/latest.log)

**Comment by ghost** [comment]
this seems to be a duplicate of #254 and #251 

Although this issue has been _fixed_ in v3.0.4, I can confirm that it has **NOT** been fixed

I changed the `common.toml` file `xpAddHealth = false`, created a new world, gave myself 14 levels of xp, logged out, logged in and gained several new hearts.  This should not have happened

Clean install, new configs, 1 config value change
Forge 31.1.61
ScalingHealth 1.15.2-3.0.4+52

**Comment by xd4rkzghost01** [comment]
Oh Fwaaaak. I just see im dumb. I have done these change last week but i re-download ScalingHealth and it "refresh" my config files. Just correct the "bug" by applying 999 lvl requirment to exp/health.
