### ISSUE TITLE
Still gaining hearts on login with config set to false

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#261]
## Versions

- **Scaling Health**: 304+52
- **Silent Lib**: 460+48
- **Forge**: 31.1.61
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior

Dont gain hearts on login

## Actual Behavior

Although this issue has been _fixed_ in v3.0.4, I can confirm that it has NOT been fixed

I changed the common.toml file xpAddHealth = false, created a new world, gave myself 14 levels of xp, logged out, logged in and gained several new hearts. This should not have happened

Clean install, new configs, 1 config value change

## Steps to Reproduce the Problem

0. change common.toml config xpAddHealth = false
1. create a world, give yourself some xp levels
2. log out/log in to the world
3. gain hearts

**Comment by Cyborgmas** [comment]
rip, worked for me before, will check again what I messed up

**Comment by Cyborgmas** [comment]
Fixed it then unfixed it, confirm that 3.0.5 works and I will close this issue

**Comment by ghost** [comment]
yep - it seems you got it - did a quick test working fine

fairly sure it does it on 1.14 as well

thank you
