### ISSUE TITLE
Mainted hearts earned even after losing XP on death

### ISSUE THREAD

**Issue by Kizwiz** [SilentChaos512/ScalingHealth#263]
Please add a setting in the config file that will allow for players to keep their hearts after dying and losing/using their XP.

**Comment by Cyborgmas** [comment]
If you are the same person on discord, I already said no. Heart crystals are a trade off you lose xp and gain permanent hp. Otherwise, it would be way too overpowered and there would be no drawback. You can already do a lot of overpowered stuff in the config files.
