### ISSUE TITLE
Mobs have crazy HP Regen

### ISSUE THREAD

**Issue by DannyRancit** [SilentChaos512/ScalingHealth#265]
I'm currently playing 1.14.4 and at the moment, I'm having issues with mobs having crazy health regen. For example, if a zombie has 40hp and i hit it down to 25 hp, it will go right back up to 40hp in under a second. Even when i was at 0 difficulty, it was doing this. Basically if i can't 1 shot the mob, i cant kill the mob period. Any help or suggestions?

**Comment by Cyborgmas** [comment]
Nope, but could you take the time filling out the Bug template? It is easier to get all the info, thanks.

**Comment by Cyborgmas** [comment]
This was an issue in an older version. Could you confirm that using the latest version of SH works and thebug no longer applies? if the bug persists, please fill out the template and provide the information I need to debug properly.
