### ISSUE TITLE
Infinite loading when opening Minecraft

### ISSUE THREAD

**Issue by LittleExxGames** [SilentChaos512/ScalingHealth#266]
## Versions

- **Scaling Health**: 1.15.2-3.0.5+52
- **Silent Lib**: 1.15.2-4.6.1+49
- **Forge**: 1.15.2 forge-31.1.74
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

To load so I can play

## Actual Behavior

It loads all the mods, then at the very end, it fades to the menu that would show up when you press esc in a world. Also, half a second later fades back to the last loading thing, loads it all over again, fades into the menu, and repeats that infinitely. Also when it is reloading it does some weird multiword shadow thing.

## Links/Images

![SecondTimeLoading](https://user-images.githubusercontent.com/52461238/81126319-2dd21e00-8ef8-11ea-8d92-7d8a651a7e73.JPG)
![Wierd](https://user-images.githubusercontent.com/52461238/81127353-2e1fe880-8efb-11ea-8719-d45a18faf578.JPG)

## Steps to Reproduce the Problem

So I managed to click the disconnect button before it tried loading again and it tried to save a nonexistent world and crashed as expected(lol). The mod list i am using is in the crash report. 
https://gist.github.com/LittleExxGames/36ba3b9ab1c0776995355ef96580b510

Also, the first time I downloaded scaling health with the previously working mod pack, it would crash and have this crash report with Forbidden and Arcanus. 
https://gist.github.com/LittleExxGames/7b80d02541855f2c2ee59a227cc45ce8

I reinstalled the whole mod pack without Forbidden and Arcanus and now it creates the issue I am having now. Forbidden and Arcanus and scaling health work fine together when alone. I don't know what other mod that gets put into the mix causes this to happen. This is the weirdest thing I have seen with experience of about 4 years of modded Minecraft.

**Comment by Cyborgmas** [comment]
Ha well, weird or not we have to debug it. Small problem, you made the logs downloadable, could you instead use a website. (Gist is probably the best)

Here's a list of some paste sites and their size limits:
    https://gist.github.com/: 100MB Requires member (Free)
    https://pastebin.com/: 512KB as guest, 10MB as Pro ($$$) 
    https://hastebin.com/ 400KB
    https://paste.ee/: 1MB as guest, 6MB as member (Free)
    https://paste.gg/: 15MB

**Comment by LittleExxGames** [comment]
Changed them to links to the gist.github.com

**Comment by Cyborgmas** [comment]
could you retry this without the phosphor mod?

**Comment by LittleExxGames** [comment]
No change.

**Comment by LittleExxGames** [comment]
I found the mod that was causing the weird issue. I disabled the mod simply trophies and it got past the infinite loading. Now I got a new problem with scaling health. XD
![NewError](https://user-images.githubusercontent.com/52461238/81364549-29963400-90a3-11ea-880c-4953d03583ea.JPG)
Latest log:
https://gist.github.com/LittleExxGames/4ca7ee4e50bb6d6ed6d6b9d9acd24542

Don't know if I should make this a new issue.

**Comment by Cyborgmas** [comment]
hmm could you check your configs? seems like a typo was in them but that should be corrected and not cause issue. Even better would be to delete all the .toml files of scaling health (save them in a txt doc if you tweaked them)

**Comment by Cyborgmas** [comment]
If that does not work try as well removing the mod apothasm

**Comment by LittleExxGames** [comment]
Resetting the config worked and now everything is working great. Thank you

**Comment by Cyborgmas** [comment]
If you don't mind, could you now retry with the trophies mod? if it bugs again I would say its correct to assume it is that mod the main cause. You could then report the bug on their page.

**Comment by LittleExxGames** [comment]
Well, it ended up working after reinstalling simply trophies so I guess my problems have all disappeared... I have all the same mods with the same versions as when it was not working but now it all workes fine.

**Comment by Cyborgmas** [comment]
okay, perfect. Will be keeping this open then, I think the crash got ignored for some reason with the other mods installed. The question is why heh

**Comment by Cyborgmas** [comment]
closing this actually. too much work D:
