### ISSUE TITLE
Levels and Expierence Points for configuration options

### ISSUE THREAD

**Issue by JextheNBguy** [SilentChaos512/ScalingHealth#269]
## Version

- 1.14x

## What Should Be Added or Changed?

- XP levels and individual XP points are used to affect the scaling of both Health and Damage. The user can choose it to scale with Current XP or Total XP. Current XP will decrease if the player loses XP or Levels. Whereas Total XP will always increase and not decrease unless there are conditions if conditions are added to the configuring process for this feature. The user may also set a threshold at which Health and Damage scale. So for example Levels could increase Health and Damage scaling every 5 levels gained or currently achieved. And XP points could increase Health and Damage scaling every 500 points. That way the scaling is consistent vs inconsistent. Lastly the user can decide weather Health, Damage or both get scaled.

## Why Should This Be Done?

- A new method for scaling both Health and Damage. Leveling and gaining XP is also a frequent thing that happens in the game.

**Comment by Cyborgmas** [comment]
Will not be adding this, permanent stats are to be gained from heart crystals, XP stats is lost on death
