### ISSUE TITLE
Blight &/or Difficulty mob blacklist reset at startup

### ISSUE THREAD

**Issue by SissyTrashQueen** [SilentChaos512/ScalingHealth#272]
A quick search didn't give me any results about this bug, so I'm posting it, sorry if this has already been noticed. I only saw issue #236 and it isn't the same.

## Versions
ScalingHealth-1.15.2-3.0.6+53

- **Scaling Health**: 3.0.6+53
- **Silent Lib**: 4.6.1+49
- **Forge**: 31.1.98
- **Optifine Installed**: NO

## Expected Behavior
Everytime I put a non vanilla mob in the blight blacklist &/or difficulty blacklist on the config, it gets deletes the next time I start Minecraft. The blight blacklist tag also doesn't seem to work through a datapack, I tried even tho I don't know if it should work.

## Actual Behavior
I'm trying to blacklist flies from the Project: Vibrant Journeys mod (& other passive/environmental mobs, but let's focus on the fly) and the blacklists get resetted to default during the Forge startup.

![blight_blacklist_tag](https://user-images.githubusercontent.com/55768134/82460977-e024ec00-9a87-11ea-95ac-e2d5f8b97046.png)

Using a datapack, putting a lot of mobs I don't want a blight of, yet I still see the blight dies alert of it.

![2020-05-20_11 48 14](https://user-images.githubusercontent.com/55768134/82461214-29753b80-9a88-11ea-838b-37c031a2e40c.png)

I can put other passive vanilla mobs on the blacklists, like squids or skeleton horses, these are never deleted.

![image](https://user-images.githubusercontent.com/55768134/82461827-d3ed5e80-9a88-11ea-983b-0ae025f4382e.png)

Yet the second I put something from any mod, the blacklist resets to default and it deletes the mobs that aren't there by default.

**Comment by Cyborgmas** [comment]
ah i think i know why. I confirm that the name is in the registry but by that time only vanilla's are populated huh... the tag was never really implemented I think. but that is actually a much better way ... 
i will try to implement the system via tags. Sorry for any confusion/annoyance !

**Comment by Cyborgmas** [comment]
Fixed in latest. see changelog on cf for tag names
