### ISSUE TITLE
Config File Difficulty Modifier "onPlayerSleep" Not Working

### ISSUE THREAD

**Issue by Nafen-F** [SilentChaos512/ScalingHealth#273]
- **Scaling Health**: 3.0.6
- **Silent Lib**: 4.6.1
- **Forge**: 31.1.89
- **Modpack**: More Explore Pack
- **Optifine Installed**: Yes

## Expected Behavior
When the input is changed from "difficulty" to "difficulty-5.0", the difficulty bar should decrease by five after the player sleeps.

## Actual Behavior
When the input is changed from "difficulty" to "difficulty-5.0" for the onPlayerSleep modifier, in the game_settings config file, there is no effect in-game. This problem persists when the value is simply changed to '0' as well. This same method works for onPlayerDeath, though. 

## Steps to Reproduce the Problem

1.Modify the "onPlayerSleep" variable in the game_settings config file
2.Run the game and sleep in a bed
3.

**Comment by Cyborgmas** [comment]
It worked fine for me, could you retry with the same SH jar but not in a modpack?

**Comment by Nafen-F** [comment]
I tried it alone and it works alright. It's in a pack with 33 other mods, so one of them is bound to mess with the sleep settings. There are sleeping bags in one of the mods, ExplorerCraft, so maybe that mod creates its own way of sleeping?

**Comment by Cyborgmas** [comment]
No idea. If you can test it alone with just SH and that mod to try and isolate the bug it would be appreciated

**Comment by Nafen-F** [comment]
OK, I was able to isolate it. Turns out it was the Quark mod and its library Autoreg that was causing the problem. https://www.curseforge.com/minecraft/mc-mods/quark

**Comment by Nafen-F** [comment]
I figured out the issue. There's an option in the Quark config file called "Improved Sleeping." If you change that to false, the difficulty modifier works fine. the improved sleeping changed the way sleeping worked so SH couldn't detect it I guess.
