### ISSUE TITLE
Scaling Health incompatible with Classic Bar

### ISSUE THREAD

**Issue by Geezt435** [SilentChaos512/ScalingHealth#274]
## Versions
Version 1.12.2

Scaling Health:1.3.40
Silent Lib: 3.0.13
Forge:14.23.5.2847
Optifine Installed

Scaling Health can't be connected with the Classic Bar's design:
![Screenshot (123)](https://user-images.githubusercontent.com/46617557/82629331-f8c90980-9c21-11ea-960d-63f046fd6b8f.png)

To reproduce
1. Instals both mod, Classic Health mod and Classic Bar
2. Go to the survival world
3. See health bar and try to use the health+ item

**Comment by Cyborgmas** [comment]
In 1.14+ there is a config option to deactivate SH heart rendering. Not sure if it is in 1.12 too though.
If it is not, sadly I do not dev for 1.12 so won't be able to fix this issue

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.

**Comment by Geezt435** [comment]
Oh 1.16.5 will comes out, guess I just have to update it lol
