### ISSUE TITLE
Scaling health 1.14.4 With Spice of life carrot it sets removes hearts on death when config is set not to

### ISSUE THREAD

**Issue by Manachron** [SilentChaos512/ScalingHealth#276]
## Versions
- **Scaling Health**: 2.5.6+54 1.14.4
- **Silent Lib**: 4.4.0+44 1.14.4
- **Forge**: 28.2.16 1.14.4
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Respawn with difficulty resetting and nothing else happening

## Actual Behavior
when you die it subtracts 7 heart crystals when the config is not set to it can cause your max health to be set to 0 making it so every time you respawn you die

## Links/Images
https://media.giphy.com/media/XD354NiVRfvZHlmTXl/giphy.gif

## Steps to Reproduce the Problem

1. install Spice of life carrot
2. die 
3. respawn

**Comment by Manachron** [comment]
sorry about bad english

**Comment by Cyborgmas** [comment]
Please complete the bug issue template. Also SOL bugs are known currently I think i fixed them though. Maybe only for 1.15

**Comment by Manachron** [comment]
ok I think I did it right

**Comment by Cyborgmas** [comment]
Will not be addressing 1.14 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
