### ISSUE TITLE
Monthly Reset Not Working

### ISSUE THREAD

**Issue by Weymouth87** [SilentChaos512/ScalingHealth#277]
## Versions

- **Scaling Health**: 1.12.2 - 1.3.42+147
- **Silent Lib**: 1.12.2-3.0.13+167
- **Forge**: 14.23.5.2854
- **Modpack**: Snake's Modded Survival (Twitch Launcher)
- **Optifine Installed**: Yes but this pack issue is server based, without optifine included in the pack.

## Expected Behavior
The difficulty of each player to reset at the beginning of the month as stated in the config file.

(Description here)

## Actual Behavior
No reset occured.

(Description here)

## Links/Images
https://pastebin.com/pKENHAGH < Config File Setup

## Steps to Reproduce the Problem

1. Set reset option in config to monthly.
2. Wait for a new month to tick by.
3. See if reset happened.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
