### ISSUE TITLE
When Removing, Health is still massive?

### ISSUE THREAD

**Issue by mcjojo3** [SilentChaos512/ScalingHealth#278]
## Versions

- **Scaling Health**: ScalingHealth-1.15.2-3.0.7+54.jar
- **Silent Lib**: SilentLib-1.15.2-4.6.1+49.jar
- **Forge**: 31.2.9
- **Modpack**: N/A
- **Optifine Installed**: Yes

## Expected Behavior

The Health bar to go down to only 20 Health when removing the mod.

## Actual Behavior

The health stays the same and the player hearts cover a large portion of the screen

## Links/Images

I fell like it's pretty nicely explained even without extra links or images.

## Steps to Reproduce the Problem

1. Install mod
2. Get extra health
3. Remove mod

**Comment by mcjojo3** [comment]
bump?

**Comment by Cyborgmas** [comment]
Not a bug, since SH uses a vanilla mechanic known as attribute modifiers. Since these are vanilla, they can stay in the game no problem. 
To remove your HP you can use the commands in scalinghealth for that (before removing ofc)
