### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by vintagedon** [SilentChaos512/ScalingHealth#28]
The mod is dumping some serious log spam on my server.  Currently, an 8 hour run produces about 160MB of log.

I do not have debug mode on in the config (I haven't touched it; the file is default), and they aren't error logs, but what look like debug logs.  There don't seem be any configs about logs except for that one line about debug mode.

You can find a small sample of the log here:
https://pastebin.com/yNzwPcML

**Comment by SilentChaos512** [comment]
Debug line I forgot to remove, sorry. It's fixed in the next version. Please leave this issue open for now.

**Comment by dawgun** [comment]
I went to write same, thanks for fix.

**Comment by vintagedon** [comment]
No need to apologize ... stuff happens.  Just appreciative that you've responded quick and it's an easy fix.  Thanks man!
