### ISSUE TITLE
Health from xp now working properly

### ISSUE THREAD

**Issue by Jepzti** [SilentChaos512/ScalingHealth#280]
## Versions

- **Scaling Health**:ScalingHealth-1.12.2-1.3.42+147.jar
- **Silent Lib**: SilentLib-1.12.2-3.0.14+168.jar
- **Forge**: 1.12.2 14.23.5.2854
- **Modpack**: N/A 
- **Optifine Installed**: Yes 

## Expected Behavior
Gain health depending on what xp level you are at on my server

## Actual Behavior
It works completely fine on single player on the debug overlay it shows "health from xp" and "scaling health health modifier" but when I enable the debug overlay when I'm on my server it just says "Unknown synced attribute modifier" and then "scaling health health modifier". It shows my extra health properly from being a high level but once I take damage my health resets back to 20 and sometimes the debug overlay says there is no modifiers and then goes back to just saying "scaling health health modifier" and thats it and my health tries to go back to more health but resets back to 20. I already deleted any other mod that could've affected the health modifier like cyclic or dungeon tactics. client and server both have the same config. 

## Links/Images

Single-Player debug overlay:
https://imgur.com/K4REk0j
Multi-Player debug overlay:
https://imgur.com/CW5xJpp
Multi-Player taking damage(Resets health when hurt) debug overlay:
https://imgur.com/XAjfsvM
Multi-Player trying to regen debug overlay:
https://imgur.com/dj2mpMm
Multi-Player fully regained health but reset again debug overlay:
https://imgur.com/3PFwHAH
## Steps to Reproduce the Problem

1. Just get hurt and health resets

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.

**Comment by Jepzti** [comment]
Bro that was last year lmao
