### ISSUE TITLE
1.15.2 Passive/neutral mobs are blight

### ISSUE THREAD

**Issue by Giintaras** [SilentChaos512/ScalingHealth#281]
- Scaling Health: **ScalingHealth-1.15.2-3.0.9+54**
- Silent Lib: **SilentLib-1.15.2-4.6.4+56**
- Forge: **31.2.21**
- Modpack: **N/A** 
- Optifine Installed: **No**

## Expected Behavior

I was expecting to have blight effect only on hostile mobs.

## Actual Behavior

Was editing difficulty of the world, set to max 10 and made that killing villager add 10 and edited the chance of blight spawn. However, I still have a lot of blight mobs that are neutral from vanilla game (Iron golem) or neutral mobs from other mods (Guard villagers, better animals plus, see screenshots attached). 

Would it be possible to edit config in a way that only specific mobs can become blight? (whitelist) or disable specific entities from becoming blight? (blacklist)

## Links/Images

Iron golem blight - https://prnt.sc/t8goie
Guard Villagers mod - https://prnt.sc/t8gqf1
Better animals plus mod - https://prnt.sc/t8gqn9

**Comment by Cyborgmas** [comment]
There is a blight blacklist tag yes. I put by default vanilla passive mobs but ofc you can add more. Any modded entity wont be accounted for as well. The name of the entity_type tag is blight_exempt. If you do not know hot to modify a tag, you can search the vanilla wiki for info.

**Comment by Giintaras** [comment]
I will, thank you for a quick response! 

Edit: Sorry if it was innapropriate to post this as a bug.. Just thought that there are more people like me who are familiar with editing config and be done with the mod configuration :/ And its going to sound dumb.. but how do I do this, edit tag or add them? Im trying to search for it, but I'm just super basic when it comes down to these things..

Edit2: Nvm, I found out. Need to open the Scaling Health.jar itself and edit .json file inside data/scaling health/tags/entity types. Edit blight_exempt.json in there. Thank you @Cyborgmas
