### ISSUE TITLE
Health reset when traveling to a dimension

### ISSUE THREAD

**Issue by EmberAnimus** [SilentChaos512/ScalingHealth#282]
## Versions

- **Scaling Health**: 2.5.5
- **Silent Lib**: 4.4.0
- **Forge**: 28.2.0
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/light-tech-and-magic-pack/relations/dependencies 
- **Optifine Installed**: Yes on clients, no on server. 

## Expected Behavior

When traveling between dimensions health should remain unaffected. 

## Actual Behavior

When traveling between dimensions in Singleplayer or Multiplayer one of the following happens:

- Health value is reset to default health

- Health value is visually changed to default health, but upon gaining another heart (or in some cases taking damage) it fixes itself

## Links/Images

None

## Steps to Reproduce the Problem

1. Go through a portal (end or nether)
2. Health is reset

**Comment by EmberAnimus** [comment]
This issue occurs in 1.14.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 or 1.14 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
