### ISSUE TITLE
Healthbar count resetting randomly.

### ISSUE THREAD

**Issue by Veritius** [SilentChaos512/ScalingHealth#283]
## Versions
147 and 145 don't work. Haven't tried any other versions.

- **Scaling Health**: ScalingHealth-1.12.2-1.3.42+147.jar
- **Silent Lib**: SilentLib-1.12.2-3.0.14+168.jar
- **Forge**: forge-1.12.2-14.23.5.2854
- **Modpack**: N/A (I will be uploading this modpack at some point)
- **Optifine Installed**: Yes

## Expected Behavior
I expect the healthbar to remain at the correct level of hearts for the amount of heart containers consumed.

## Actual Behavior
The bar resets to 20 points, or 10 hearts, at 1 row, seemingly randomly.

## Links/Images
Here is my modlist.
![image](https://user-images.githubusercontent.com/45957058/87513081-786fd380-c6bb-11ea-9b33-034c47813118.png)
![image](https://user-images.githubusercontent.com/45957058/87513104-7f96e180-c6bb-11ea-954b-a1209c2cf474.png)

## Steps to Reproduce the Problem

1. Install the mods I have installed.
2. Run the game.
3. Try it out.

**Comment by Veritius** [comment]
Modpack: https://www.dropbox.com/s/163ja92k49ac3fo/IdiotsAnonymousModpack.zip?dl=0

**Comment by Hamna76** [comment]
I have been facing the exact same problem in RLCraft. My health resets to 10 hearts (20 hp) randomly after some time or when I re-log.

**Comment by BoatTK** [comment]
Has anyone found a solution?

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
