### ISSUE TITLE
Weird behavior redux

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/ScalingHealth#284]
## Versions
- **Scaling Health**: ScalingHealth-1.12.2-1.3.42+147.jar
- **Silent Lib**: SilentLib-1.12.2-3.0.14+168.jar
- **Forge**: forge-14.23.5.2847
- **Modpack**: custom currently. can provide twitch export.
- **Optifine Installed**: Yes.

## Expected Behavior/Actual Behavior

I appear to have come across an old bug that was flagged as can't reproduce previously with very similar activation.

https://github.com/SilentChaos512/ScalingHealth/issues/145

it occurs in this pack idea I've been working on which i could probably provide a twitch export of for testing. it happens with a difficulty increase per kill of 0.1 currently. sometimes my mobs are dieing but instantly getting full health and continuing on despite counting as dieing and dropping them items as normal.

it registers them as dieing, even giving death messages in the cases of champions and others but no other console things appear. just business as usual. When it occurs the mob will play it's death sound etc but they are immediately healed or somehow respawned on the spot, sometimes glitching out while "Dead"/flashing red like as if they had gone into negative health and not died properly, but normally after the second kill they're done properly (or I just never got unlucky enough to have it happen double).

it occurs on stuff like the soul mod's mobs that spawn on player death with your items etc which sometimes causes you to get back double your stuff cause both mob instances will drop items. but I first had it occur when batting around lycanite elementals while trying to test it's progression.

heres a log for the recent testing session so you can atleast get an idea of the scale of the mods involved and take a poke around. but during the occurences of it happening nothing troubling etc occurs on console/in log.
[latest.log](https://github.com/SilentChaos512/ScalingHealth/files/4978583/latest.log)

meanwhile, I'll try it with some stuff when the difficulty increase isn't set or is something lower instead and see what happens.

**Comment by Darkmega18** [comment]
HMMMMmmmm... now it's playing heisenbug. >_>'

loaded in, with the setting still up. then tweaked it down to zero, got nothing. tweaked it back up, stayed gone. don'tcha love it? :1234:

**Comment by Darkmega18** [comment]
![image](https://user-images.githubusercontent.com/8104689/88492106-b5a56100-cfeb-11ea-9d8d-a7da737dd16d.png)
finally. theres one doing. was just fighting mobs with the the taoism weapons.

not sure on the trigger, but seems to occur more readily on vanilla mobs.

strangely also happening more often than not against grimoire of gaia minotaurs too, minus the red glitching. not sure if it's related to the amount of overkill dealt to finish the mob or something but found that curious.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.12 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.

**Comment by Darkmega18** [comment]
ehh, if this is the weird immortality glitch thing from ages ago cause of reducing difficulty than increasing it, I guess it's fine... I just did away with that idea and that pack didn't really get finished either. which is unfortunate. no idea if it happens in most recent anymore though.
