### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Yourname942** [SilentChaos512/ScalingHealth#285]
**Environment**
Minecraft: 1.15.2
Forge: 31.2.36
Scaling Health: 3.0.9+54
Silent Lib: 4.6.6+59
Modpack: [Here ](https://drive.google.com/file/d/126bE2LKzqLVMNnAcr4jx_lkD2Cm08wpR/view?usp=sharing)
Optifine Installed: No

**Expected Behavior**
There should be no errors from your mod when all I did was create a new world and enter it.

**Actual Behavior**
I receive parsing errors loading custom advancements from your mod.

**Latest log** [Here](https://gist.github.com/Yourname942/41b2a7d4b9aac14ea7416df2fb18c19a#file-latest-log-6-55pm-8_16_20)

**Highlighted Log Section** [Here](https://gist.github.com/Yourname942/41b2a7d4b9aac14ea7416df2fb18c19a#file-latest-log-6-55pm-8_16_20-L4678-L4767)

**Steps to Reproduce the Problem**
1. Select Play in Twitch App
2. Select Play in Minecraft Launcher
3. Create a new world
4. Enter world
5. Exit Minecraft

**Comment by Cyborgmas** [comment]
There is a lot more errors than SH in the log. If the error can be reproduced with much less errors (ie only SH) it will more informative

**Comment by Cyborgmas** [comment]
Will not be addressing 1.15 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
