### ISSUE TITLE
server crash Ticking entity 1.16.3

### ISSUE THREAD

**Issue by tindin** [SilentChaos512/ScalingHealth#286]
## Versions

- **Scaling Health**: 1.16.3-4.0.0
- **Silent Lib**:1.16.2-4.8.0+60
- **Forge**: 1.16.3-34.0.8
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
no to crash randomly

(Description here)

## Actual Behavior
ticking entity crash 

(Description here)

## Links/Images
https://pastebin.com/uQBynW4b

## Steps to Reproduce the Problem
happens at random times when playing

**Comment by tindin** [comment]
the crash seems to mainly happen with creepers

**Comment by Cyborgmas** [comment]
could you remove lost trinkets? and see if the issues arises still? because the impression im getting is that they are causing it somehow.

**Comment by tindin** [comment]
still happens with lost trinkets gone but doesnt happen with scaling health gone

**Comment by Cyborgmas** [comment]
could you post the new debug.log then, when the crash occured without lost trinkets?

**Comment by tindin** [comment]
seem you are right.  after a fresh world with out lost trickets your mod works
