### ISSUE TITLE
Blights stats do not increase 

### ISSUE THREAD

**Issue by Paparogue** [SilentChaos512/ScalingHealth#288]
## Versions

- **Scaling Health**: ScalingHealth-1.16.3-4.0.0+0.jar
- **Silent Lib**: SilentLib-1.16.3-4.8.1+61.jar
- **Forge**: forge-1.16.3-34.1.23.jar
- **Modpack**: N/A (Custom)
- **Optifine Installed**: No

## Expected Behavior

Blights having double stats (health and damage or at least health) blightModifier = 2.0

## Actual Behavior

They don't have anything increased

## Links/Images

- Pic: https://i.gyazo.com/98bc620de3b3c18fe2c29f6bd5e391ba.png
- Config1: https://pastebin.com/raw/3Jt0WVLx
- Config2: https://pastebin.com/raw/hFqDUJ6k

## Steps to Reproduce the Problem

1. Always not working

**Comment by Cyborgmas** [comment]
BlightModifiers only multiplies the bonus gained from difficulty, so if 10 hp is gained from a level 100 zombie, a blight level 100 zombie will gain 20 hp. (approximately, there might be some discrepancie with config options).
But at difficulty = 0, there is no change in hp or dmg, only potion effects.
