### ISSUE TITLE
NullPointerException at net.silentchaos512.scalinghealth.event.PetEventHandler.onLivingUpdate

### ISSUE THREAD

**Issue by Paparogue** [SilentChaos512/ScalingHealth#289]
## Versions

- **Scaling Health**: ScalingHealth-1.16.3-4.0.0+0.jar
- **Silent Lib**: SilentLib-1.16.3-4.8.1+61.jar
- **Forge**: forge-1.16.3-34.1.23.jar
- **Modpack**: N/A (Custom)
- **Optifine Installed**: No

## Expected Behavior

Server not crashing.

## Actual Behavior

Eventually at some point the Server crashes due to a Nullpointer.

## Links/Images

https://pastebin.com/raw/fpPxWSbL

## Steps to Reproduce the Problem

1. Randomly while walking around

**Comment by Cyborgmas** [comment]
this is only the crash report i would prefer the full debug.log please.
also please test:
1) try and see if it crashes without ice and fire (if it does, please post the generated debug.log here)
2) check if the server has properly generated the configs

**Comment by kukeiko** [comment]
had the same issue, config files look ok, here is the debug log http://kukeiko.at/minecraft/debug.zip

i tried setting regenDelay for pets in game_settings.toml to 0.0 but the issue still occurred.

**mods:**

AutoRegLib-1.6-47.jar
caelus-forge-1.16.4-2.1.0.0.jar
cc-tweaked-1.16.4-1.94.0.jar
cofh_core-1.16.3-1.0.4.jar
collective-1.16.4-1.53.jar
colytra-forge-1.16.4-5.1.0.0.jar
curios-forge-1.16.4-4.0.3.0.jar
elevatorid-1.16.4-1.7.8.jar
Gobber2-1.16.4-2.3.40.jar
jei-1.16.4-7.6.0.58.jar
JRFTL+[1.16.4]-1.2.jar
mcw-bridges-1.0.4-mc1.16.4.jar
NastyMobs-1.16.3-1.0.0.7.jar
OptiFine_1.16.4_HD_U_G5.jar
OptiForge-MC1.16.4-0.4.3.jar
Quark-r2.4-277.jar
quiver-2.1-1.16.4.jar
RoRmod-1.16.4-1.1.2-Forge.jar
ScalingHealth-1.16.3-4.0.0+0.jar
SilentLib-1.16.3-4.9.0+63.jar
sisser-1.7.jar
stackrefill_1.16.4-1.1.jar
thermal-1.16.3-1.0.5.jar
torohealth-1.16.4-forge-2.jar
trashcans-1.0.3-mc1.16.4.jar
Xaeros_Minimap_20.28.1_Forge_1.16.4.jar
XaerosWorldMap_1.11.3_Forge_1.16.4.jar

**Comment by Cyborgmas** [comment]
The only way i can see this happening is that the config is not present... but it is being checked each tick so uncertain how it could just disappear

**Comment by Cyborgmas** [comment]
The config has been moved to a datapack system so this is no longer accurate
