### ISSUE TITLE
Health reset to const calculation incorrect when net max health is higher then configured

### ISSUE THREAD

**Issue by No3371** [SilentChaos512/ScalingHealth#290]
1. Get max health
2. Get higher max health from other modifiers (ex: other mods)
3. /kill
4. Result hp: Max health -20 (My resetOnDie: "20")
5. /kill
6. Result hp: 20

Edit: The other modifiers get reset to 0 when player dies.
(As long as it's under max_health configured in scaling-health config file, the reset works correctly)

**Comment by Cyborgmas** [comment]
Closing because there is no version info, if this is still an issue please reopen one and conform to the template
