### ISSUE TITLE
Cant turn off gaining health thru exp

### ISSUE THREAD

**Issue by nexus140** [SilentChaos512/ScalingHealth#294]
## Versions

- **Scaling Health** ScalingHealth-1.16.3-4.0.0+0
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63
- **Forge**: 1.16.4-forge35.1.11
- **Modpack**: N/A 
- **Optifine Installed**: Yes 

## Expected Behavior
 when i go to the config game setting scroll all the way down i changed  #On hp increase, how much hp is gained - to 0 thinking that would turn off the exp hp gain feature

(Description here)

## Actual Behavior
when i go to load up the mod the settings go back to normal

(Description here)

## Links/Images

- https://hastebin.com/isacihivum.yaml
- (Another link or file, if needed)

## Steps to Reproduce the Problem

1. go to game setting config change #On hp increase, how much hp is gained to 0
2.close and save changes to config load up minecraft 
3. once finished loading up go back to the config folder and reopen scroll back down to see that the setting went back to normal

**Comment by Cyborgmas** [comment]
This is now done in a separate file, the server config file
