### ISSUE TITLE
1.16.4 - Timeout while Connecting to a Server

### ISSUE THREAD

**Issue by DeliciousTea** [SilentChaos512/ScalingHealth#295]
So I'm putting together a modpack and I'd really love to use Scaling Health. Unfortunately, I'm getting some errors when connecting to a server I've set up. Basically, these errors get thrown and then the last one gets repeated endlessly until I cancel joining the server. This is on the client only, the server seems to continue on just fine while this is occurring. After removing Scaling Health, everything works just fine. I even tried removing the configs just to check if it was some issue with formatting.

https://hastebin.com/fomoqesalu.properties

Thanks!

**Comment by DeliciousTea** [comment]
Just an update on this, it seems to be some kind of conflict with the Reliquary mod? I'm not at all sure what is going on here but I thought I'd let you know. Removing either scaling health or reliquary allows connecting to a server just fine. They both also seem to work fine in single player. Very confusing.

**Comment by Cyborgmas** [comment]
Reliquary is doing something weird here 
<https://github.com/P3pp3rF1y/Reliquary/blob/1.16.x/src/main/java/xreliquary/items/MobCharmRegistry.java#L87-L90>
they are creating an entity a bit too early and then SH is trying to load a tag but too early. I'll see a bit more if this can be fixed on SH's side. You can also try submitting a bug report to them and link this issue.
