### ISSUE TITLE
AFK Difficulty in config won't stay negative number.

### ISSUE THREAD

**Issue by Xenopsych** [SilentChaos512/ScalingHealth#297]
Minecraft Version 1.16.4

- **Scaling Health**: 1.16.3-4.0.1+1
- **Silent Lib**: 1.16.3-4.9.0+63
- **Forge**: 35.1.4
- **Modpack**: custom 88 total
- **Optifine Installed**: yes

game_settings Config for AFK Difficulty doesn't save when I change the value to a negative number.

This is what the config says:

[difficulty.afk]
		#Multiplier for changePerSecond when the player is not moving. A negative value will then decrease difficulty.
		multiplier = 0.5
		#Time in seconds before afk change kicks in
		time = 30.0
		#If true, a comment will appear to notify when you are considered afk
		message = true

This is what I want:

[difficulty.afk]
		#Multiplier for changePerSecond when the player is not moving. A negative value will then decrease difficulty.
		multiplier = -0.5
		#Time in seconds before afk change kicks in
		time = 30.0
		#If true, a comment will appear to notify when you are considered afk
		message = true

After saving what I want and starting up minecraft the config always converts the negative afk multiplier back to a positive 0.5

**Comment by Cyborgmas** [comment]
Config file moved to datapacks and I removed the possibility of a negative number (so its not a bug anymore, its intended)
