### ISSUE TITLE
Slime entity children do not scale proportionately down in health from their parent.

### ISSUE THREAD

**Issue by mopsyd** [SilentChaos512/ScalingHealth#30]
Some glitchiness occurs with slime/magma cube mobs. It seems that the smaller slimes health tracks according to the adult version instead of scaling down proportionately like the vanilla mechanic. I fought one magma cube with 250 health, which broke down into about 30+ of the smallest which also had 250 health each, and it took about 45 minutes to kill the full lot of them, which gets extremely tedious pretty fast. Perhaps adding some mechanic for slime entities that force health to be represented as half of the original parent entity for the sub-entities might address this.

Applies to vanilla slimes, magma cubes, tinkers construct slimes, and seemingly any other entity using the slime type.

**Comment by SilentChaos512** [comment]
Minecraft version? Seems fine on 1.12, but all versions should be the same for this kind of issue. Any config changes, to either file?
