### ISSUE TITLE
A config/other way to remove items from chest loot tables

### ISSUE THREAD

**Issue by notWaterGuy12** [SilentChaos512/ScalingHealth#302]
## Version
1.16

## What Should Be Added or Changed?
An option to remove crystal/heart drops from chest loot tables

## Why Should This Be Done?
From messing around with loot tables, I cannot find a way to remove this mod's items from chest loot tables. It would be nice to have a easy way to disable it or a method to remove them from chest loot in general. I am currently using a very janky method and would like to streamline the process a bit.

**Comment by phyne** [comment]
We really need this. Can't seem to edit anything related to the chest loot tables.

**Comment by Cyborgmas** [comment]
Yeah that is "normal", I am waiting for a Forge PR to be able to do this cleanly.

**Comment by SilentChaos512** [comment]
One option is to put the added loot entries into their own loot tables and "inject" them into the existing ones. The injection tables can be customized normally with data packs, or even disabled with a config. Silent Gear does this, although it doesn't have any config options, just the loot tables: https://github.com/SilentChaos512/Silent-Gear/blob/1.16.x/src/main/java/net/silentchaos512/gear/init/LootInjector.java

(I think I adapted the idea from Quark or Botania, can't remember.)

**Comment by Cyborgmas** [comment]
Seems like a neat way, thanks. Should be done in the weekend

**Comment by Schummel-8** [comment]
What's the current state of this issue?
Would be nice to know if there will be an update in the near future.
