### ISSUE TITLE
Unable to Find Config file

### ISSUE THREAD

**Issue by smaurine82** [SilentChaos512/ScalingHealth#304]
## Version
 16.5

- 1.x

## What Should Be Added or Changed?
 I would like there to be config options accessible through the config button under mods, but it is greyed out. I know that it works with one other mod I have. I haven't been able to find the cofig file for adjusting the max difficulty level and I have looked in every folder. I did find the cofig file to make it so farm animals aren't included, which is nice (i.e., I semi know what I'm doing). 

- (Description)

## Why Should This Be Done?

If the config was fixed to either have in in-game menu or to work with the forge config menu option, I would be able to tweak the settings much more easily and like your mod more. 

- (Description)
Thank you for considering my suggestion.

**Comment by Cyborgmas** [comment]
So yeah the config menu is not a "bug" per se, I need to create it from scratch (which i can do but requires time)
However the config should be in the config folder and named game settings.toml

**Comment by smaurine82** [comment]
Could you tell me the path to get there? Here is a snapshot of my file directory. 
![1](https://user-images.githubusercontent.com/77517741/104822427-a3201d80-57ff-11eb-9449-59a1778ae243.JPG)

Within  the net folder I found a config folder, but all the the files are .class files.

**Comment by Cyborgmas** [comment]
How did you get there ... the config folder should be in your .minecraft folder

**Comment by Cyborgmas** [comment]
the game_settings.toml was moved to datapacks, as for the client configuration you can use the Configured mod to add a menu
