### ISSUE TITLE
[1.15.2 Server] Crashing error 137 

### ISSUE THREAD

**Issue by Cwoodyard** [SilentChaos512/ScalingHealth#310]
## Versions

- **Scaling Health**: 3.0.9+54
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.45
- **Modpack**: Potion Shop Madness (curseforge v1.0.7) 
- **Optifine Installed**: No (on client side but not server) 

## Expected Behavior

Server not to crash when applying potion effect an user log-on

## Actual Behavior

Intermitten: 
Will apply potion effects and when user logs on, server will crash with error 137

## Links/Images

[debug.log](https://github.com/SilentChaos512/ScalingHealth/files/5922210/debug.log)
[latest.log](https://github.com/SilentChaos512/ScalingHealth/files/5922213/latest.log)

## Steps to Reproduce the Problem

1. Run pack as a server
2. Play for a bit and let other users logon
3. Either it will randomly crash or will crash on user logon.

**Comment by Cyborgmas** [comment]
Will not be addressing 1.15 issues, sorry for any inconvenience, I hope you will continue playing on the 1.16.5 version which I will be maintaining.
