### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Cosmophobe** [SilentChaos512/ScalingHealth#313]
## Versions

- **Scaling Health**: 4.0.3+3
- **Silent Lib**: 4.9.1+64
- **Forge**: 36.0.15
- **Modpack**: custom
- **Optifine Installed**: Yes

## Expected Behavior
Walking around as normal

## Actual Behavior
Game randomly crashes because of Ticking Entity while walking around

## Links/Images
https://gist.github.com/Cosmophobe/2b8f4a7a85c7770365be51959dac8cdd

## Steps to Reproduce the Problem
1. Walk around
2. Crash

**Comment by Cyborgmas** [comment]
the file you sent has no errors pertaining to scaling health whatsoever. There isn't event a crash in it.

**Comment by Cosmophobe** [comment]
> the file you sent has no errors pertaining to scaling health whatsoever. There isn't event a crash in it.

https://pastebin.com/AHJK4ng0 

Here's the crash report I got.

**Comment by alentoghostflame** [comment]
Dropping these off for Cosmophobe, here's the debug.log file.
https://gist.github.com/alentoghostflame/d3f5f1a2b0f6d10ce40c322cc331c6d7
[debug.log](https://github.com/SilentChaos512/ScalingHealth/files/5992280/debug.log)

**Comment by Cyborgmas** [comment]
Fixed on discord
