### ISSUE TITLE
Health config

### ISSUE THREAD

**Issue by ShootToKillSTK** [SilentChaos512/ScalingHealth#318]
For 1.16.4/5

Ability to take away health when player dies
- Promotes not dying even more/great difficulty balancing with health increasing allowed, also makes the 'lowest health a player can have' option do something lol

Apologizes if this is already a thing, but I don't think so or I'm really blind

**Comment by kubistonek** [comment]
it is a thing

**Comment by MarkValhezia** [comment]
should be added!

**Comment by Cyborgmas** [comment]
This is indeed possible, there is the `player.health.setOnDeath` config which takes in an EvalEx expression. You can set it to "maxHealth - 2" for example and it will reduce your max hp by 2 each time you die. Other questions about this should go on curse or preferable on discord
