### ISSUE TITLE
Underground Biomes Construct compatability (1.10.2)

### ISSUE THREAD

**Issue by DoragonKeiyou** [SilentChaos512/ScalingHealth#32]
Ore doesn't seem to be spawning in stone that generates from UBC.  Chances are the ore only checks against vanilla stone when placing for generation, and since almost the whole world is covered in non-vanilla stone, unless I travel to find a vanilla stone under-biome, I never see the ore.  Is there anyway it can check for the ore dictionary for stone, rather than just vanilla stone?

Also, I could be extremely unlucky so far and it's eluded me, but the only spot I've seen it is in the description above.

**Comment by SilentChaos512** [comment]
I just tried the mod, and found heart crystal ore in basalt. The default config for Scaling Health makes them spawn one vein in about 3 out 7 chunks, so they are rare.

**Comment by DoragonKeiyou** [comment]
Must be bad luck for me then.
