### ISSUE TITLE
Config Change Whilst In-World Destroys Game

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#326]
## Versions

- **Scaling Health**: ScalingHealth-1.16.4-4.0.3+3.jar
- **Silent Lib**: SilentLib-1.16.3-4.9.1+64.jar
- **Forge**: 36.0.45
- **Modpack**: `N/A (Currently Private)` 
- **Optifine Installed**: Yes 

## Expected Behavior

Should be able to edit and save mod configs without the game going nightmare-mode.

## Actual Behavior

Game crashes and if caught by NotEnoughCrashes, appears completely and nightmarishly corrupted.

## Links/Images

[Crash Report](https://hatebin.com/burlpitpjb)
[Latest.log](https://hatebin.com/sdobqskqrc)

![image](https://user-images.githubusercontent.com/24266948/110193495-53b5af80-7e88-11eb-8561-c73fb82543bb.png)
![image](https://user-images.githubusercontent.com/24266948/110193500-57e1cd00-7e88-11eb-9201-1ff868b4542b.png)

## Steps to Reproduce the Problem

1. Install all my mods.
2. Start the game and enter a world.
3. Attempt to change a Scaling Health config setting (in my case `difficulty.meter.position.offsetY` in `client.toml`).
4. `6th March, 2021 "Nightmare Voxel" incident`

**Comment by Camawama** [comment]
That is terrifying. Idk why, but corrupt games are creepy. Remind me of old console cartridge tilt bugs...equally as creepy.
