### ISSUE TITLE
Game crashes when Creeper explodes or if you switch into creative with Blood Magic mod

### ISSUE THREAD

**Issue by Luckyday84** [SilentChaos512/ScalingHealth#327]
## Versions

- ScalingHealth-1.16.5-4.0.5+5
- silent-lib-1.16.3-4.9.6
- bloodmagic:1.16.4-3.1.0-15
- Forge-36.1.1
- **Modpack**: N/A 
- **Optifine Installed**: No 
-
(Description here)

Game crashes when Creeper explodes or if you switch into creative with Blood Magic mod installed
Its a know issue - https://github.com/WayofTime/BloodMagic/issues/1795
https://pastebin.com/86hbiCvR

## Steps to Reproduce the Problem

1. Make a fresh Minecraft instance with  Forge-36.1.1, BloodMagic-1.16.4-3.1.0-15, silent-lib-1.16.3-4.9.6 and ScalingHealth-1.16.5-4.0.5+5
2. In game let a Creeper explode or swap to creative mode and the game will hard crash.

**Comment by Cyborgmas** [comment]
https://github.com/WayofTime/BloodMagic/issues/1795#issuecomment-802046611
