### ISSUE TITLE
Conflict with Tinker's construct

### ISSUE THREAD

**Issue by MrDarkLoader** [SilentChaos512/ScalingHealth#329]
## Versions
Minecraft 1.16.5

- **Scaling Health**: 4.0.5+5 
- **Silent Lib**: 4.9.6 
- **Forge**: 36.1.3
- **Modpack**: My own, private
- **Optifine Installed**: No 
- **Tinker's construct**: 3.0.2.73
- **Mantle**: 1.6.79
## Actual Behavior
Game crashes when creeper explodes

## Links/Images
https://pastebin.com/A4ckWGws
## Steps to Reproduce the Problem

1. Spawn a creeper
2. Wait for explode
3. Crash

**Comment by SilentChaos512** [comment]
Starting to think the creeper issue might be worth investigating further.

**Comment by Random832** [comment]
Someone on discord the other day had this same bug with Unique Enchantments. Something about the way Scaling Health's GLM is applied causes LootingLevelEvent to be called with a null DamageSource.

I want to clarify that I confirmed that creeper explosions do not normally cause a null DamageSource [they also don't seem to cause looting checks at all unless the creeper kills another entity, which doesn't *seem* to have been the case] so there's no reason to think that mods should account for a null here, even though Blood Magic added a null check on their end when this was affecting them.

**Comment by Anesca38** [comment]
Second this. 

Minecraft 1.6.5
Forge 36.1.4
Modlist : 
* FerriteCore (Forge)
* Just Enough Items (JEI)
* Structurize
* Akashic Tome
* Apotheosis
* AppleSkin
* Ars Nouveau
* AutoRegLib
* Biomes O' Plenty
* Blood Magic
* Botania
* Citadel
* Clumps
* Construction Wand
* CraftTweaker
* Create
* Curio of Undying (Forge)
* Curios API (Forge)
* Eidolon
* Enchanted Book Redesign
* Fast Leaf Decay
* FastWorkbench
* GeckoLib
* Guide-API Village and Pillage
* Ice and Fire: Dragons
* Immersive Engineering
* JEITweaker
* JourneyMap
* Just Enough Resources (JER)
* Mantle
* MineColonies
* Morpheus
* Mouse Tweaks
* Nature's Aura
* Nature's Compass
* Neat
* Optifine.net
* Patchouli
* Placebo
* Rats
* Resourceful Bees
* Shutup Experimental Settings!
* Silent Lib (silentlib)
* Spice of Life: Carrot Edition
* Storage Drawers
* The One Probe
* The Twilight Forest
* Tinkers Construct
* Torchmaster
* Vampirism - Become a vampire!
* Vampirism Integrations
* Waystones

Deleted ScalingHealth, works perfectly fine without it.

**Comment by Cyborgmas** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/7714#issuecomment-817207015 
real issue was reported on the forge github, forge opinion seems to be the error is not null checking the dmg source. Ill try and see if i can do something on my side for the crashes though.
