### ISSUE TITLE
Chat spam [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [SilentChaos512/ScalingHealth#33]
I have your mod installed on a server, but there is a lot of spam chatting when killing the fire mobs. How are entities death messages disabled?
I still want to see player deaths.

**Comment by SilentChaos512** [comment]
You mean the blights? There was supposed to be a config for that, but it looks like it's not being loaded properly.

**Comment by HeberonYT** [comment]
I do not know if they are plagues.
But every time someone kills a mob that lets loose hearts appears that in the chat, and it's annoying because there are too many mobs.

minecraft: 1.10.2
version: ScalingHealth-1.11.2-1.0.8-52.jar

![0fd3aedbe2b55705e9003c4402c5072887e4e3f9bb7b019252 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/13698597/27897272-caf4839c-61e4-11e7-8cd4-efe5315cc052.png)
