### ISSUE TITLE
Config option to drop shards instead of whole crystals.

### ISSUE THREAD

**Issue by Nexus345** [SilentChaos512/ScalingHealth#332]
-- Version
 1.16.5

--What Should Be Added or Changed?
Config option to allow mobs to drop shards instead of whole hearts, and to configure drop rates in general. This applies for power stones too.

--Why Should This Be Done?
This option was in the 1.12.2 version and felt very balanced as you could disable ore generation and source crystals from more difficult milestones like blight or boss defeats. It's harder to balance exp gain from a whole mod list rather than one drop from one mod. Plus some other mods add HP now so it is too easy to get HP when easy mobs can drop whole hearts.

-Thanks for your time.

**Comment by najlitarvan** [comment]
use the datapacks, you can configure it there

**Comment by Darkmega18** [comment]
> 
> 
> use the datapacks, you can configure it there

how...? where...? _(new into the whole datapacking thing from playing 1.12.2 most of the time and only just getting into tinkering with 1.16.5 stuffs.)_

**Comment by najlitarvan** [comment]
1. look on the minecraft wiki
2. look at the json itself it ussually tells you if you read it properly
3.  ask on discord not here

**Comment by Darkmega18** [comment]
I was doing that anyway, but thats not helpful of you. _*sigh*_ cause I don't even know what I'm looking for in relation to doing the thing. :V but I guess I gotta just go tinker. >_>

**Comment by najlitarvan** [comment]
ask in discord i can explain it there better

**Comment by Darkmega18** [comment]
god you reply quick. I barely got to edit my thoughts.

**Comment by najlitarvan** [comment]
ask on discord
