### ISSUE TITLE
Gamestages break every other difficulty setting (1.12.2)

### ISSUE THREAD

**Issue by TheComputerizer** [SilentChaos512/ScalingHealth#335]
## Versions

- **Scaling Health**: 1.12.2-1.3.42+147
- **Silent Lib**: 1.12.2-3.0.14+168
- **Forge**: 14.23.5.2855
- **Modpack**: [Dimension Hopper](https://www.curseforge.com/minecraft/modpacks/dimensionhopper)
- **Optifine Installed**: No 

## Expected Behavior

The difficulty to be allowed to increased when a gamestage is set

## Actual Behavior

I have 1 single gamestage set to allow a hard mode with my pack, but I have found with that line there, difficulty does not otherwise increase, which is rather game breaking in my case

- (Link or file)
-  My [config](https://pastebin.com/2e03Jrqh)

## Steps to Reproduce the Problem

Add a gamestage to the config

**Comment by najlitarvan** [comment]
1.12 is not supported, and this will not be fixed
