### ISSUE TITLE
Ability to turn off heart crystals and power crystals from both ore and chest loottables

### ISSUE THREAD

**Issue by Mr-Syntax** [SilentChaos512/ScalingHealth#337]
I am running this mod together with PlayerEx

i have  turned of the ability to increase your max hp with hearts but they still appear in chest and sometimes mobs drop them.

so my request is either that there be a config to stop them spawning, or that turning the ability to use them off automatically stops them from spawning

**Comment by najlitarvan** [comment]
use datapacks it's written in those
