### ISSUE TITLE
How to adjust amount of health gained by heart crystal on server?(1.16.4+)

### ISSUE THREAD

**Issue by Jetprism** [SilentChaos512/ScalingHealth#339]
So i found a file name "game-setting" in scaling health folder in config. But no matter what i did,it still give 1 heart for 3 exp. Where did i go wrong?

I copied everything i changed into this 
[game_setting.txt](https://github.com/SilentChaos512/ScalingHealth/files/6491778/game_setting.txt)

**Comment by najlitarvan** [comment]
please include versions and other health mods

**Comment by Jetprism** [comment]
im using version 4.1.1+7,the other health mod are Unhealthy Dying and LevelHeart

**Comment by najlitarvan** [comment]
is it the newest version?

**Comment by Jetprism** [comment]
yes it is

**Comment by najlitarvan** [comment]
it is driven by datapacks now discord includes a basic datapack, would recomend getting a mod for loading datapacks

**Comment by Jetprism** [comment]
can you make it clear?

**Comment by najlitarvan** [comment]
datapacks are used to configure it now

**Comment by Jetprism** [comment]
can i have the link ?

**Comment by najlitarvan** [comment]
https://discord.gg/fNAu9ZNV

**Comment by Jetprism** [comment]
tysm!
