### ISSUE TITLE
[Ticking Entity Crash] Potential incompatibility with Bloodmagic

### ISSUE THREAD

**Issue by Shandoo94** [SilentChaos512/ScalingHealth#343]
## Versions

- **Scaling Health**: 4.0.5+5
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.16
- **Bloodmagic**: 3.1.0-15
- **Modpack**: https://pastebin.com/vkdXWDvE
- **Optifine Installed**: Yes

## Expected Behavior
no crash

## Actual Behavior
When a creeper explodes it becomes a ticking entity and crashes the game
When removing scaling health the crash does not occur

## Links/Images
Crashlog: https://pastebin.com/HWc1Q2fJ

## Steps to Reproduce the Problem

1. Spawn Creeper
2. Stand near it an let it explode
3. Crash the game

**Comment by Shandoo94** [comment]
also mentioned in https://github.com/WayofTime/BloodMagic/issues/1808

**Comment by Cyborgmas** [comment]
This has been fixed in the latest beta versions of SH, and it has already been fixed in teh blood magic code, the author just needs to push a release on CF
