### ISSUE TITLE
Invisible mobs

### ISSUE THREAD

**Issue by Cybze** [SilentChaos512/ScalingHealth#345]
## Versions

- **Scaling Health**: 4.1.1
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.23
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Normal mobs

## Actual Behavior

All the mobs (friendly and hostile) are invisible. (They have the invisible potion effect, it's not just a graphic glitch/bug)

## Links/Images

- (Link or file)
- (Another link or file, if needed)

## Steps to Reproduce the Problem

1. Set difficulty to hard
2.
3.

**Comment by Cyborgmas** [comment]
4.1.2. fixes this
