### ISSUE TITLE
Token Enchanter Exp Bread takes away hearts when you gain exp regardless of settings.

### ISSUE THREAD

**Issue by ExiledMiner04** [SilentChaos512/ScalingHealth#347]
## Versions

- **Scaling Health**: 1.16.5-4.1.1+7
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1
- **Modpack**: My List: JEI 1.16.5-7.7.0.98, AppleSkin-mc 1.16.2-forge-1.0.14, silent-gear-1.16.5-2.6.25, SilentMechanisms-1.16.3-1.0.1+77, silents-gems-1.16.3-4.0.4, token-enchanter-1.16.3-1.0.4, torohealth-1.16.4-forge-2, Xaeros_Minimap_21.9.0.1_Forge_1.16.5, XaerosWorldMap_1.14.1_Forge_1.16.5
- **Optifine Installed**: No 

## Expected Behavior

Exp bread to not take away hearts when eaten and you gain exp. In fact, when "Heart gain is affected by Exp" option is set to on, Heart count should go up not down.

## Actual Behavior
Give yourself exp by commands or give yourself exp bread via JEI or by commands ( you need 3 level to us a heart by default), eat the bread, then use a heart, then give exp or use bread again and watch your hearts get reduced.

## Links/Images

latest.log
- https://pastebin.com/ejyYK9eP
- (Another link or file, if needed)

## Steps to Reproduce the Problem

1. have exp to use a heart crystal by any means necessary
2. use heart crystal
3. try to regain exp by any means (using exp bread or commands to give exp/levels) but killing mobs, this does not affect it.
4. watch hearts drop back to vanilla count of 10 (containers will still exist as earned).
5. using a new heart crystal will heal you back to existing hearts + the new one added for some reason.

**Comment by Cyborgmas** [comment]
Fixed in 4.1.4
