### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Lequals18** [SilentChaos512/ScalingHealth#350]
## Versions

- **Scaling Health**: 4.1.5+11
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 1.16.5
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/hardcorerevitalised (the mod is taken out for the latest version so that servers could be playable.) There is also a server file.
- **Optifine Installed**: No 

## Expected Behavior
Being able to connect to the server after clicking join

## Actual Behavior
I press connect to server and instantly get an error

## Links/Images

https://ibb.co/str9yVZ (error message)

Server 
https://pastebin.com/V6Kb85nZ 

Client
https://pastebin.com/4r12HeJk

## Steps to Reproduce the Problem

try to connect to the modded server with scaling health installed.

**Comment by Diversion98** [comment]
Has this been fixed cause i have this problem as well with 4.1.5+11?

**Comment by Likeabozz123** [comment]
> Has this been fixed cause i have this problem as well with 4.1.5+11?

Same as well, not sure this has been fixed.

**Comment by Diversion98** [comment]
> > Has this been fixed cause i have this problem as well with 4.1.5+11?
> 
> Same as well, not sure this has been fixed.

Looking at other issues, I think the dev is not active anymore :/

**Comment by Likeabozz123** [comment]
> > > Has this been fixed cause i have this problem as well with 4.1.5+11?
> > 
> > 
> > Same as well, not sure this has been fixed.
> 
> Looking at other issues, I think the dev is not active anymore :/

Seems it was conflicting with improved mobs

**Comment by Diversion98** [comment]
> > > > Has this been fixed cause i have this problem as well with 4.1.5+11?
> > > 
> > > 
> > > Same as well, not sure this has been fixed.
> > 
> > 
> > Looking at other issues, I think the dev is not active anymore :/
> 
> Seems it was conflicting with improved mobs

damn that sucks :/
Cause i wanted to use scaling health to decide the difficulty (option in improved mobs)
