### ISSUE TITLE
Config file might be hard to understand

### ISSUE THREAD

**Issue by SGZ-Creations** [SilentChaos512/ScalingHealth#363]
* Versions
Minecraft: 1.16.5 

Scaling Health: 4.0.5+5
Silent Lib: 4.9.6
Forge: 36.2.0
Modpack: ATM6 + custom added mods to pack. custom are not on list won't works so these are the custom on image:
![image](https://user-images.githubusercontent.com/59801736/127107578-46d1dfb3-a9f6-4642-ab7a-1a498072abd5.png)

* Expected Behavior + Actual Behavior:
Hey. I started a game while doing so I saw the difficulty in game increase. So I went to look for config in game, but only option was by files. So I started reading trough changed all the thing I wanted to change as of planning a server where it can't have health increase because the save will be unplayable when mobs reaches a specific health value. Since they won't die of fire damage because of to much health during the day and that cause it lag out.
Tho back to the config. I changed the part about mobs health increase. Then when I was about to start up the save it only come to this point on Image: (1) and stood there for about 5-15 min before giving up thinking it was corrupted. So I started a new save saw that hearts was still the same as on #362 look for any solution about post #362. Sadly I couldn't find much but still changed something that again made the same hang on load. Just for 3-8h instead of 5-15 min. and even after that it still was stuck loading on save. And today {27/07/21} I noticed on a new save that the config file (game_setting.toml) was partially changed back to it's defaults by just loading the modpack it is placed in/on. Images: (2) Before changes not 100% default + not all settings. Image: (3) After putting the setting I want to play with (4) after launching the pack again + reload of file in use warning.
 
* Links/Images
1. 
![image](https://user-images.githubusercontent.com/59801736/127109012-c3115d80-36cf-41ae-a4a2-43eb73a64ce9.png)
2.
![image](https://user-images.githubusercontent.com/59801736/127111142-0add490c-9eed-4c39-82b4-64cb751deb38.png)
3.
![image](https://user-images.githubusercontent.com/59801736/127114812-74d0ab7c-007f-40ac-a9ee-e6cf36147c48.png)
4.
![image](https://user-images.githubusercontent.com/59801736/127115146-515a0770-522d-4d53-bb46-465eb4303c65.png)
![image](https://user-images.githubusercontent.com/59801736/127115215-ae360e6b-5a9b-4d12-8000-fc694b2dbf8a.png)

* Steps to Reproduce the Problem:
The images +The total explanation about issue hopefully gives u the answer u need.

* End note:
Might have fond some fix and got to understand the file better but I'll post to be 100% sure that what might be an issue get's solved and what's not an issue is just dropped.

**Comment by Mr-Syntax** [comment]
if you edit the files even while being in the minecraft menu some of them will instantly make a copy that you are editing instead, try sorting your folder by file extension and see if there are any backup file extension related to scaling health, delete them + close minecraft completely -> edit the config and save -> run minecraft

alternately if this isent working, create a blank pack and copy all the mods and configs into that folder and edit i there then it has to work!

but i just found some settings in the config that are straight up not working so that might be what your experiencing

**Comment by SGZ-Creations** [comment]
> if you edit the files even while being in the minecraft menu some of them will instantly make a copy that you are editing instead. 

Answer: have been aware since before the post.

Tho my issue where that i edited numbers that still changed after logging out, changing the file then logging back in still 
it changed back. automatically 
 Exampel 1
![image](https://user-images.githubusercontent.com/59801736/138294463-51393f13-f895-4810-86f8-ed1fe8cbbef7.png)

Exsampel 2
![image](https://user-images.githubusercontent.com/59801736/138294559-02e05f4c-c05a-480c-97a4-bedce37190b3.png)
