### ISSUE TITLE
java.lang.ClassCastException: class net.silentchaos512.scalinghealth.objects.potion.BandagedEffect (Initializing game)

### ISSUE THREAD

**Issue by Coraline77447** [SilentChaos512/ScalingHealth#364]
## Versions

- Minecraft: 1.17.1
- Scaling Health: 5.0.0+0
- Silent Lib: 5.0.0.
- Forge: 37.0.22
- Optifine Installed: No (Not compatible with forge 1.17 yet) 

- Crash Report: https://pastebin.com/7nqiPxpM

-Log: [latest.log](https://github.com/SilentChaos512/ScalingHealth/files/6924082/latest.log)

**Comment by Cyborgmas** [comment]
thats just because you are using forge version 37.0.22 (or upwards)
use the version below for now, ill update it to work on newer forge
