### ISSUE TITLE
Bug: Scaling Heath - Loading world

### ISSUE THREAD

**Issue by Yelioz** [SilentChaos512/ScalingHealth#38]
### Versions

Minecraft Version: 1.11.2-forge1.11.2-13.20.1.2454
Scaling Health Version: ScalingHealth-1.11.2-1.0.8-52
Silent Lib Version: SilentLib-1.11.2-2.2.6-66

### Expected behavior

- Create a new survival world using this mod

### Actual behaviour

-When I create a new world does not load me, it stays in loading world

### Steps to reproduce the problem

Screenshots:
https://i.gyazo.com/16761d143df7829b32db90202005d8b0.png
https://i.gyazo.com/880ba4c11298f72804b4c2ac7693632a.png

[logs.docx](https://github.com/SilentChaos512/ScalingHealth/files/1247501/logs.docx)

**Comment by SilentChaos512** [comment]
You have the latest Silent Lib, but Scaling Health is outdated. Try 1.2.0-68 (yes, it does work on 1.11.2).
