### ISSUE TITLE
common toml file not populating anywhere

### ISSUE THREAD

**Issue by RoyalXerxes** [SilentChaos512/ScalingHealth#385]
## Versions
ScalingHealth-1.18.1-6.0.0+0

- **Scaling Health**: ScalingHealth-1.18.1-6.0.0+0
- **Silent Lib**: silent-lib-1.18-6.0.0
- **Forge**: 39.0.59
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior
common toml file populates config files on server.

## Actual Behavior
common toml file no where to be found, only server toml.

## Steps to Reproduce the Problem

1.  Install mod
2.  Start Server
3.  Common toml not generated.

**Comment by Cyborgmas** [comment]
There is no common config, there is only the server & client configs + datapack options.
