### ISSUE TITLE
(1.12.2) frequent freezing made by flan's mod and scaling health (maybe)

### ISSUE THREAD

**Issue by rebarakuk** [SilentChaos512/ScalingHealth#386]
## Versions

- **Scaling Health**: 1.3.42 + 147
- **Silent Lib**: 3.0.14 + 168
- **Flan's mod**: 5.10.0
- **Forge**: 14.23.5.2860
- **Modpack**: N/A 
https://drive.google.com/drive/folders/1RpU6QXYAI3T9MmnC8wd3kURnpIWhsnYc?usp=sharing
(just a mod list made by me)

- **Optifine Installed**: Yes, but... 
No log file. just frequent freezing and no matter

## Expected Behavior

freezing doesn't happen

## Actual Behavior

frequent freezing happens

## Links/Images

- (Link or file)
- (Another link or file, if needed)

## Steps to Reproduce the Problem

1. Flan's mod and other mods make mobs have armors.
2. Maybe they make armor overlapping or something, and I only want armors of flan's mod
3. So, I want scaling health mod to have more config of blight mob's equipment to make them not armored.

**Comment by Cyborgmas** [comment]
1.12 is not being maintained and won't receive updates

**Comment by rebarakuk** [comment]
It wasn't the conflict of scaling health and flan's mod.
Structures from Ancient warfare 2 decreased tps for some seconds.
