### ISSUE TITLE
No ore Generated

### ISSUE THREAD

**Issue by SireTeddy** [SilentChaos512/ScalingHealth#387]
## Versions

- **Scaling Health**: 6.0.0+0
- **Silent Lib**: 6.0.0
- **Forge**: 39.0.79
- **Modpack**: Another Quality 3 version 1.7 
- **Optifine Installed**: No 
-
## Actual Behavior
When i active the ore Gen on serverconfig, and delete removeore config on startup script, ores don't be generated (i test on a server with Randomport mod to generate new chunks)

## Links/Images
[features]
	#Enable player bonus hp by crystals.
	crystalsAddHealth = true
	#Enable player bonus hp by xp.
	xpAddHealth = false
	#Enable player regen hp by crystals.
	crystalsRegenHealth = true
	#Enable pet add hp by crystals.
	crystalsAddPetHealth = true
	#Enable player add damage by crystals.
	crystalsAddDamage = true
	#Enable ore gen of health crystals. Still drops as loot.
	hpCrystalsOreGen = true
	#Enable ore gen of power crystals. Still drops as loot.
	powerCrystalsOreGen = true
	#Mobs will gain bonus health with difficulty.
	mobHpIncrease = true
	#Mobs will gain bonus damage with difficulty.
	mobDamageIncrease = true
	#Enable player damage scaling.
	playerDamageScaling = true
	#Enable mob damage scaling.
	mobDamageScaling = false
	#Enable difficulty system. If disabled, everything will have 0 difficulty.
	enableDifficulty = true
	#Enable blights. If disabled, no blights will spawn.
	enableBlights = true

## Steps to Reproduce the Problem

1.enable oregen on serverconfig
2.disable removeore on startserver script
3.look into the caves on spectator with night vision to see (on this case don't see) any power/health ore crystal

**Comment by Cyborgmas** [comment]
Fixed it in 6.1.0
