### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks mod

### ISSUE THREAD

**Issue by Baggytrousers27** [SilentChaos512/ScalingHealth#389]
Scaling Health (scalinghealth) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

ScalingHealth-1.18.2-6.0.1+1
silent-lib-1.18-6.0.0
Forge 40.0.18

No Optifine

[Crashlog](https://pastebin.com/q6hY5SP7)

**Comment by CDAGaming** [comment]
Bump, still present in .32

**Comment by CDAGaming** [comment]
Fixed in pr I've made CC @SilentChaos512 for merge

**Comment by Cyborgmas** [comment]
Was fixed in 6.2.0
