### ISSUE TITLE
HAHAHA i'm still laughing a little

### ISSUE THREAD

**Issue by ShaCraft** [SilentChaos512/ScalingHealth#39]
Server thread/INFO [Scaling Health]: Blight Squid drowned... again

### Versions

Minecraft Version: 1.XX
Scaling Health Version: 12.0-68
Silent Lib Version: 1.20.2.2.2.6-66

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by SilentChaos512** [comment]
That's a special death message I added for the ever-so-bright squids. So, not really a bug, but I'm glad I'm not the only one who thought it was funny. If you want to prevent squids from becoming blights, you can add "Squid" (with a capital 'S') to the blight blacklist.
