### ISSUE TITLE
Health continues to Regenerate while doNaturalRegeneration is false. No setting the remove the regen. 

### ISSUE THREAD

**Issue by krlsmnk** [SilentChaos512/ScalingHealth#395]
## Versions

- **Scaling Health**: ScalingHealth-1.18.2-6.2.0+2.jar
- **Silent Lib**: silent-lib-1.18.2-6.2.0.jar
- **Forge**: 40.1.0
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Health to not increase over time

## Actual Behavior
Health returns over time

## Links/Images
N/A

## Steps to Reproduce the Problem
1. Start a new world. Set doNaturalRegeneration to false
2. Jump off something and break your leg
3. Wait a few seconds. Health returns
4. Ensure doNaturalRegeneration is still set to false. It is.

**Comment by krlsmnk** [comment]
I see that this appears to be intentional?
In the file: 
event/PlayerBonusRegenHandler.java
You're subscribing a regen function to the player's tick function. 
Any way we can get an option to disable that?

**Comment by Cyborgmas** [comment]
Didnt put an option, regen will be disabled according to the gamerule.

**Comment by krlsmnk** [comment]
> Didnt put an option, regen will be disabled according to the gamerule.

Did you update/ change anything? Because that doesn't appear to be working.

**Comment by Cyborgmas** [comment]
I did this on my computer for now, itll be in the next update on CF
