### ISSUE TITLE
Mob Health not scaled

### ISSUE THREAD

**Issue by Blabliblubpaul** [SilentChaos512/ScalingHealth#397]
## Versions

- **Scaling Health**: 1.18.2-6.2.0+2
- **Silent Lib**: 1.18.2-6.2.0
- **Forge**: 1.18.2-40.1.16
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

The mob Health to rise with higher difficulty

## Actual Behavior

nothing happens
## Steps to Reproduce the Problem

1.play the game
2.
3.

My datapack:
[sh_mechanics.zip](https://github.com/SilentChaos512/ScalingHealth/files/8652131/sh_mechanics.zip)

**Comment by Cyborgmas** [comment]
This was due to the tag being inverted https://github.com/SilentChaos512/ScalingHealth/issues/394 so it should be fixed
