### ISSUE TITLE
Bug: Server crash when non-player entity kills blight

### ISSUE THREAD

**Issue by wise-io** [SilentChaos512/ScalingHealth#40]
### Versions
Minecraft Version: 1.12.1
Scaling Health Version: 1.2.0-68
Silent Lib Version: 2.2.7-85

### Expected behavior
- My wolf kills blighted enemy.
- Scaling Health announces: "Wisecompany's pet has killed blighted cow."

### Actual behaviour
- Server crashes when blighted enemy killed by my tamed wolf.

### Steps to reproduce the problem
1. Tame a wolf
2. Let wolf kill blighted entity
3. Server crash
4. Profit

### Crash Log
[crash-2017-09-04_18.40.39-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/1275654/crash-2017-09-04_18.40.39-server.txt)

**Comment by SilentChaos512** [comment]
Should be a relatively easy fix. I'll do my best to get this out tomorrow. Sorry for the inconvenience.

**Comment by wise-io** [comment]
No inconvenience, thanks for the great mod!
