### ISSUE TITLE
[Suggestion] Override Absorption in HUD

### ISSUE THREAD

**Issue by resinate** [SilentChaos512/ScalingHealth#41]
enable/disabling overlapping hearts?

i like how u have custom color hearts but when i use them i have absorption mod enabled and it creates many rows of hearts. i just wanna use overlapping hearts with custom colors

**Comment by SilentChaos512** [comment]
They should overlap by default. Must be an effect of the other mod. Just so we're clear, it's Natural Absorption on Minecraft 1.10.2?

**Comment by resinate** [comment]
yep actually i had far better idea
what if u made new UI for hearts and asborption lol
like this

[xxxxxxxxxxxxxxxxxxxxxxx] [250/1000]
[xxxxxxxxxxxxxxxxxxxxxxx] [250/1000]

this little idea would open the door to some amazing RPG modpacks

if u have discord we can better, i can show u the screen or even show u on my stream

**Comment by SilentChaos512** [comment]
See #115 for progress on this
