### ISSUE TITLE
ServerSide Only - I cannot add additional health

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/ScalingHealth#43]
### Versions

Minecraft Version: 1.12.1
Scaling Health Version: ScalingHealth-1.12-1.2.0-68
Silent Lib Version: SilentLib-1.12-2.2.7-85

### Expected behavior

- Adds additional health

### Actual behaviour

- Heals but doesn't add health

### Steps to reproduce the problem

Not yet sure just looking for people who may be expirencing a similar issues.

**Comment by SilentChaos512** [comment]
Could be caused by another mod that's also trying to set player health. Have you added any new mods recently?

**Comment by P3rf3ctXZer0** [comment]
Yeah but none I am aware that add health changes.

**Comment by P3rf3ctXZer0** [comment]
Okay it seems to be Dungeon Tactics messing with health.

**Comment by P3rf3ctXZer0** [comment]
I was wrong it is more complex I will show you modlist and maybe you can point something out.

Name                                  	Date modified     
[1.12] SecurityCraft v1.8.2.3-hotfix.jar	9/16/2017 1:57 PM 
AbyssalCraft-1.12-1.9.4-pre-4.jar     	9/16/2017 1:57 PM 
ActuallyAdditions-1.12.1-r119.jar     	9/16/2017 2:35 PM 
architecturecraft-1.12-1.20.jar       	9/11/2017 2:31 PM 
AutoRegLib-1.3-13.jar                 	9/6/2017 8:41 PM  
Baubles-1.12-1.5.1.jar                	9/9/2017 2:30 PM  
BedBugs-1.12-1.0.1.jar                	9/15/2017 2:53 PM 
betterunderground-1.0.2.jar           	9/15/2017 2:53 PM 
BiblioCraft[v2.4.3][MC1.12.0].jar     	9/9/2017 2:30 PM  
bigbeautifulbuttons-1.12.1-1.1.2.jar  	9/9/2017 2:30 PM  
BiomesOPlenty-1.12-7.0.0.2291-universal.jar	9/6/2017 8:41 PM  
BlockArmor-1.12-2.4.8.jar             	9/11/2017 6:36 PM 
Botania r1.10-347.jar                 	9/9/2017 2:30 PM  
Chameleon-1.12-4.1.3.jar              	9/9/2017 9:26 AM  
Chisel-MC1.12-0.0.14.18.jar           	9/13/2017 10:58 PM
chiselsandbits-14.7.jar               	9/6/2017 8:41 PM  
ColossalChests-1.12-1.6.5.jar         	9/6/2017 8:41 PM  
CosmeticArmorReworked-1.12.1-v1.jar   	9/6/2017 8:41 PM  
CraftTweaker2-1.12-4.0.6.jar          	9/8/2017 7:40 PM  
CTM-MC1.12-0.2.2.7.jar                	9/13/2017 10:58 PM
cucumber[1.12]-1.0.2.jar              	9/6/2017 8:41 PM  
Currency-1.12.0-1.2.0.jar             	9/6/2017 8:41 PM  
CyclopsCore-1.12-0.10.17.jar          	9/6/2017 8:41 PM  
Dark Roleplay Core Alpha-0.3.2.jar    	9/16/2017 2:35 PM 
Dark Roleplay Medieval-0.2.1.2.jar    	9/16/2017 2:35 PM 
DeathCounter-1.12.1-1.0.0.jar         	9/9/2017 9:26 AM  
DeathQuotes-1.2.0-mc1.12-forge.jar    	9/16/2017 1:57 PM 
DimensionRules-MC1.12-1.1.jar         	9/9/2017 11:25 AM 
ExtraBitManipulation-1.12-3.2.1.jar   	9/6/2017 8:41 PM  
flatcoloredblocks-mc1.12-6.5.jar      	9/6/2017 8:41 PM  
Floricraft-1.12-4.2.2.jar             	9/16/2017 1:57 PM 
foamfix-0.8.0-1.12-law.jar            	9/15/2017 4:33 PM 
forestry_1.12.1-5.5.5.193.jar         	9/15/2017 11:26 AM
FTBLib-4.1.3.jar                      	9/15/2017 11:26 AM
FTBUtilities-4.1.3.jar                	9/15/2017 11:26 AM
furniture-4.1.5-1.12.jar              	9/9/2017 2:30 PM  
GardenStuff-1.12-2.1.0.jar            	9/11/2017 2:31 PM 
HardcoreDarkness-MC1.12-1.9.jar       	9/16/2017 1:57 PM 
HideNames-1.12-1.4.jar                	9/16/2017 1:57 PM 
InventoryTweaks-1.63+beta.108.jar     	9/6/2017 8:41 PM  
itorch-1.2.0.jar                      	9/9/2017 2:30 PM  
IvToolkit-1.3.3-1.12.jar              	9/6/2017 8:41 PM  
jei_1.12.1-4.7.8.94.jar               	9/9/2017 9:14 PM  
jeibees-0.9.0.4-mc1.12.1.jar          	9/9/2017 9:26 AM  
journeymap-1.12.1-5.5.0b4.jar         	9/8/2017 7:40 PM  
KeepingInventory-1.12.1-2.3.jar       	9/6/2017 8:41 PM  
Mantle-1.12-1.3.1.21.jar              	9/6/2017 8:41 PM  
mcjtylib-1.12-2.4.4.jar               	9/6/2017 8:41 PM  
metamorph-1.1.3-1.12.jar              	9/15/2017 4:33 PM 
minecolonies-universal-1.12.1-0.8.3861.jar	9/16/2017 2:35 PM 
mod_list.json                         	9/6/2017 8:41 PM  
modtweaker-4.0.2.jar                  	9/9/2017 9:26 AM  
morebeautifulbuttons-1.12.1-1.6.0.13.jar	9/9/2017 2:30 PM  
morebeautifulplates-1.12.1-1.0.2.jar  	9/9/2017 2:30 PM  
MTLib-3.0.0.jar                       	9/9/2017 9:26 AM  
multibeds-1.12.0-1.4.2.jar            	9/9/2017 9:26 AM  
MultiMine-1.12.1.jar                  	9/16/2017 1:57 PM 
multistorage-1.12.0-1.4.1.jar         	9/9/2017 10:51 AM 
mysticalagradditions[1.12]-1.2.4.jar  	9/6/2017 8:41 PM  
mysticalagriculture[1.12]-1.6.3.jar   	9/6/2017 8:41 PM  
Natura-1.12-4.3.0.17.jar              	9/6/2017 8:41 PM  
NaturesCompass-1.12-1.5.0.jar         	9/16/2017 1:57 PM 
NetherPortalFix_1.12.1-5.3.9.jar      	9/6/2017 8:41 PM  
NoMoreRecipeConflict-0.9(1.12).jar    	9/6/2017 8:41 PM  
NotEnoughIDs-1.5.4.1.jar              	9/6/2017 8:41 PM  
OptiFine_1.12.1_HD_U_C5.jar           	9/8/2017 7:55 PM  
OverpoweredInventory-1.12-2.3.1.jar   	9/6/2017 8:41 PM  
Pam's HarvestCraft 1.12.1c.jar        	9/11/2017 2:31 PM 
Plants-1.12-1.2.0.jar                 	9/11/2017 2:31 PM 
plustic-6.3.1.0.jar                   	9/6/2017 8:41 PM  
Pokecube Mobs-2.14.8.jar              	9/11/2017 2:31 PM 
Pokecube Revival-6.11.2.jar           	9/6/2017 8:41 PM  
Pokecube_Core-6.21.3.jar              	9/12/2017 7:07 PM 
prefab-1.3.0.9.jar                    	9/15/2017 11:26 AM
Quark-r1.3-110.jar                    	9/16/2017 2:35 PM 
RecurrentComplex-1.4.5.jar            	9/6/2017 8:42 PM  
recycler-1.4.8-1.12.0.jar             	9/6/2017 8:42 PM  
rftools-1.12-6.13.jar                 	9/6/2017 8:42 PM  
rftoolsdim-1.12-5.05.jar              	9/10/2017 10:20 AM
rustic-0.4.3.jar                      	9/12/2017 10:27 AM
ScalingHealth-1.12-1.2.0-68.jar       	9/6/2017 8:42 PM  
SeedCopy-1.9-3.0.5.jar                	9/9/2017 11:25 AM 
ServerPropertiesLAN-2.4.jar           	9/8/2017 11:43 AM 
SGExtraParts-1.12-1.3.2-27.jar        	9/6/2017 8:42 PM  
shetiphiancore-1.12.0-3.5.2.jar       	9/8/2017 11:42 AM 
SignPicture-1.12.1-2.8.1-universal.jar	9/9/2017 2:30 PM  
SilentLib-1.12-2.2.7-85.jar           	9/6/2017 8:42 PM  
SilentsGems-1.12-2.4.7-221.jar        	9/16/2017 4:03 PM 
SimpleDimensions-MC1.12-1.3.1.jar     	9/9/2017 10:51 AM 
SimplyConveyors-4.0.4.jar             	9/16/2017 1:57 PM 
StorageDrawers-1.12.1-5.3.2.jar       	9/9/2017 9:26 AM  
StorageDrawersExtras-1.12-3.1.0.jar   	9/16/2017 1:57 PM 
structpro-4.0-1.12.1.jar              	9/6/2017 8:42 PM  
TConstruct-1.12-2.7.3.30.jar          	9/6/2017 8:42 PM  
terraqueous-1.12.0-1.4.3.jar          	9/16/2017 2:35 PM 
theoneprobe-1.12-1.4.18.jar           	9/6/2017 8:42 PM  
thut_wearables-3.1.0.jar              	9/6/2017 8:42 PM  
thutcore-5.11.0.jar                   	9/6/2017 8:42 PM  
thuttech-6.0.5.jar                    	9/12/2017 6:41 PM 
TinkersComplement-1.12.1-0.2.0.jar    	9/6/2017 8:42 PM  
TinkerToolLeveling-1.12-1.0.2b.jar    	9/6/2017 8:42 PM  
TombManyGraves-1.12-4.0.1.jar         	9/16/2017 2:35 PM 
topaddons-1.12-0.15.1.jar             	9/6/2017 8:42 PM  
torojimaBuildHelper-1.0.0.jar         	9/9/2017 10:51 AM 
TrashSlot_1.12.1-8.4.6.jar            	9/15/2017 2:53 PM 
TreeChopper-1.12.1-1.2.3.jar          	9/13/2017 10:58 PM
upsizer-mc1.12.1-4.0.jar              	9/9/2017 10:51 AM 
ViesCraft-1.12.0-5.0.6.jar            	9/16/2017 1:57 PM 
Wopper-1.12-r5.jar                    	9/16/2017 1:57 PM 
worldedit-forge-mc1.12-6.1.8-dist.jar 	9/9/2017 9:26 AM  
Xtones-1.12-1.0.6-9.jar               	9/8/2017 11:35 AM 
YABBA-1.12-1.0.2.jar                  	9/15/2017 11:26 AM

**Comment by SilentChaos512** [comment]
Nothing really sticks out in the list. I tried using some of the ones I'm less familiar with, but still had no issues adding an extra 60 hearts.
Is there a limit to how many hearts it will let you gain, or does it just not work at all now? Does setting your health with the "/scalinghealth health" command do anything?

**Comment by P3rf3ctXZer0** [comment]
It doesn't seem to work no.

**Comment by P3rf3ctXZer0** [comment]
@SilentChaos512 so I played single player even with lan and it works fine... your thoughts?

**Comment by P3rf3ctXZer0** [comment]
I figured it out - config conflict the configs didn't match. Maybe make it so server config always takes priority?

**Comment by P3rf3ctXZer0** [comment]
Okay wrong its still very broken ...

**Comment by P3rf3ctXZer0** [comment]
Okay after a lot of trial and error it appears the culprit is some leftover files from the tough as nails mod. As I am not a coder I am going to give you the old world files. Maybe you can make some sense of it.

**Comment by P3rf3ctXZer0** [comment]
http://63.251.42.198/TGGRS-Old.rar
http://63.251.42.198/mods-old.rar

**Comment by P3rf3ctXZer0** [comment]
Okay ... I am sick of this bug.

**Comment by P3rf3ctXZer0** [comment]
Okay so I can increase initial health value only the heart crystals don't work.

**Comment by SilentChaos512** [comment]
I'll try downloading those files later and see what I can find out.

**Comment by SilentChaos512** [comment]
Can't seem to download those files, I time out trying to connect to the host.

So, maybe a shot in the dark, but I added some extra debug info. If you enable Debug Mode in the config, it will now show all attribute modifiers being applied to your health. You may need to adjust your GUI scale or window size to fit all the text on screen. If anything other than the Scaling Health modifier shows up, send me a screenshot. Jar file included below.

One more question: when you use the heart containers, does it play the XP orb "ding" sound, or the burp sound (end of eating food)?

Be sure to extract the jar from the zip: [ScalingHealth-1.12-1.2.2-71_debug-iss43.jar.zip](https://github.com/SilentChaos512/ScalingHealth/files/1326308/ScalingHealth-1.12-1.2.2-71_debug-iss43.jar.zip)

**Comment by P3rf3ctXZer0** [comment]
Burp

Just downloading now. I will start testing.

**Comment by P3rf3ctXZer0** [comment]
@SilentChaos512 I have some bad news ... the Jar you gave me does not quite work ... basically by itself it generates no config - it also ignores the old config.

**Comment by SilentChaos512** [comment]
You extracted it from the zip, right?

**Comment by P3rf3ctXZer0** [comment]
![2017-09-23 11_22_20-mods](https://user-images.githubusercontent.com/10351221/30775896-8dc7c99c-a051-11e7-98de-d947b610a338.png)

**Comment by P3rf3ctXZer0** [comment]
I have been beta'ing for you how long; "Number one tech rule before panicking - Is it plugged in?" so yes ;)

**Comment by SilentChaos512** [comment]
That's weird, it's generating the config/scalinghealth folder and its contents for me.

**Comment by P3rf3ctXZer0** [comment]
... ... ... why me (>.<)
![2017-09-23 11_30_00-mods-testing](https://user-images.githubusercontent.com/10351221/30775967-a525c8ae-a052-11e7-84c8-f57889b8ba3f.png)
![2017-09-23 11_30_10-mods-testing](https://user-images.githubusercontent.com/10351221/30775968-a5261d86-a052-11e7-8711-f5811c8bb6df.png)
![2017-09-23 11_30_26-mods-testing](https://user-images.githubusercontent.com/10351221/30775969-a526a4ea-a052-11e7-9820-34372cd295e9.png)

**Comment by P3rf3ctXZer0** [comment]
GOD DAMMIT - WRONG FOLDER TREE LOOK!!! <- Punches Self in Face
![2017-09-23 11_36_39-30775969-a526a4ea-a052-11e7-9820-34372cd295e9 png png image 1688 x 964 pixels](https://user-images.githubusercontent.com/10351221/30776023-7fc9ddec-a053-11e7-8be3-e7d071d16f34.png)

**Comment by P3rf3ctXZer0** [comment]
@Thutmose can you please enlighten us? I know you have dealt with Sanity checks etc that prevent this kind of problem. Why does his mod keep getting trumped?

**Comment by SilentChaos512** [comment]
Provide a full server log for me? Maybe there's some clue in there.

**Comment by P3rf3ctXZer0** [comment]
Where is the debug file log located?

**Comment by P3rf3ctXZer0** [comment]
![2017-09-23 13_43_46-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/30776079-d00ca23e-a054-11e7-95c9-f33a13506db1.png)

**Comment by SilentChaos512** [comment]
Doesn't look like anything else is applying modifiers. Do you actually have 50 hearts like it suggests?

**Comment by P3rf3ctXZer0** [comment]
I don't think so. I have 3 sets of hearts.

**Comment by P3rf3ctXZer0** [comment]
also there is not supposed to be a cap.

**Comment by P3rf3ctXZer0** [comment]
I think I figured something out the debug menu spazzed out and for a single frame I caught this
![2017-09-23 13_56_54-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/30776153-750dd716-a056-11e7-8e7e-5c2bb8618de2.png)

**Comment by SilentChaos512** [comment]
I'm seeing that too when connected to a server, so probably nothing to worry about. The value and id are correct.
So are you still hearing a burp when trying to use heart containers? Normally that would mean either your current max health is greater than your "Max Health" config or "Hearts Increase Max Health" is set to false.

**Comment by P3rf3ctXZer0** [comment]
... ... ... 
![2017-09-23 12_09_58-_ main cfg c__users_administrator_appdata_roaming_ minecraft_1 12 2_config_scal](https://user-images.githubusercontent.com/10351221/30776260-28fd44cc-a058-11e7-9f30-1ccad12f5e45.png)

**Comment by SilentChaos512** [comment]
OK, could you send me your mods/configs and a bugged world? The links above don't work for me.

**Comment by P3rf3ctXZer0** [comment]
....

**Comment by P3rf3ctXZer0** [comment]
I am so sorry for wasting our time ...
![2017-09-23 14_28_42-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/30776420-f9712586-a05a-11e7-9439-dea81e4f93e4.png)
It was such a simple fix.

**Comment by SilentChaos512** [comment]
Don't worry about it, I should have thought to check the config sooner.

**Comment by resinate** [comment]
u guys are aware of cyclics heart cans right?

**Comment by SilentChaos512** [comment]
I've heard of them, do they cause any issues?

**Comment by SilentChaos512** [comment]
Just tested the Cyclic hearts. Seems like they modify the player's health directly, instead of setting a modifier. So Scaling Health just reverses the effect. I don't think there's anything I can do, Cyclic should be using attribute modifiers.

**Comment by P3rf3ctXZer0** [comment]
@SilentChaos512 I don't use cyclic. Also doesn't it make more sense for the op to make a new topic?

**Comment by SilentChaos512** [comment]
Probably not worth fixing anyway. Both systems accomplish the same thing, so it's up to the user to decide which to disable.
