### ISSUE TITLE
Crash - Serverside 1.12.1 (Mod Interaction - Scaling Health and MetaMorph)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/ScalingHealth#44]
### Versions
-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1229501208 bytes (1172 MB) / 2780594176 bytes (2651 MB) up to 8520204288 bytes (8125 MB)
	JVM Flags: 8 total; -Xms1g -Xmx8g -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=40 -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSScavengeBeforeRemark -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 68
FML: MCP 9.41 Powered by Forge 14.22.1.2481 123 mods loaded, 123 mods active

Scaling Health Version: | UCHIJAAAA | scalinghealth | 1.2.0 | ScalingHealth-1.12-1.2.0-68.jar | None 
Silent Lib Version: | UCHIJAAAA | silentlib | 2.2.8 | SilentLib-1.12-2.2.8-88.jar | None 

### Expected behavior

- No crash

### Actual behaviour

- Crashing

### Steps to reproduce the problem

https://github.com/mchorse/metamorph/issues/73

**Comment by SilentChaos512** [comment]
That one's definitely my fault.

**Comment by mchorse** [comment]
Thanks! 👍
