### ISSUE TITLE
Huuuge lags ( Minecraft 1.12.2 with lots of mods, 500 or more, I think )

### ISSUE THREAD

**Issue by Kasia1403** [SilentChaos512/ScalingHealth#447]
As above and even Chunk Pregenerator mod doesn't help. And also I don't know how to configure properly this mod.

**Comment by SilentChaos512** [comment]
Sorry, can't help you with that. 1.12.2 is no longer being worked on. And that is way too many mods for you to be able to point to one specific mod without providing any evidence.
