### ISSUE TITLE
Suggestion - Seperate Health System

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/ScalingHealth#45]
Alright so @SilentChaos512 you know we have been dealing with a stupid bug 
here https://github.com/SilentChaos512/ScalingHealth/issues/43 ... what if you created a completely seperate health system that is like regenerative armor called "aura" It can use a star meter 
![de119a9ab38b1180a6f7ee76145951f5--christmas-stencils-christmas-templates](https://user-images.githubusercontent.com/10351221/30768709-f3c08b12-9fc0-11e7-90a8-044a5a3892cf.jpg)
instead of hearts. I think whatever is preventing health in some cases could be fixed simply by adding a unique (damage absorption) you could even still make it cost hunger. I am just tired of your awesome mod being blocked by anything that affects the base health system. Please consider my thoughts.

**Comment by P3rf3ctXZer0** [comment]
https://i.pinimg.com/736x/de/11/9a/de119a9ab38b1180a6f7ee76145951f5--christmas-stencils-christmas-templates.jpg

**Comment by SilentChaos512** [comment]
An interesting idea, but it could still cause problems. For example, you
can damage a player without it firing any events, bypassing any other
systems a mod may add. I'd call that bad practice, but I'm sure someone has
done that. I'll keep it in mind, but right now I'll just try to track down
the culprit of this issue.
