### ISSUE TITLE
Health can't go infinite

### ISSUE THREAD

**Issue by andr9528** [SilentChaos512/ScalingHealth#47]
Minecraft Version: 1.12.1
Scaling Health Version: 1.12-1.3.0-73
Silent Lib Version: 1.12-2.5.2-226

I where expecting to be able to get infinite health as my config is set to 0 which means infinite (according to the config description), but...
When i reached 103.4 lines of hearts it stopped increasing my health when i used the canisters.
For some time i had Botania's Odins Ring equipped, but i have taken that off, but canisters still don't work. Even tho i don't get hearts, the canisters are still being used up so somthing is being called but not running correctly. 
Calculating out my health to actual health that i have behind the scene then i have 2068 health, which happens to be precisely 2048 + the 20 that the player starts with, i do not know if this is relevant but it is a little weird. Setting my health to 2048 with the command gets me to the exact same point where health do not want to increase anymore regardless of if it is done with command or cannister, neither work at that point. Perhaps you limit it to 2048 additional health somewhere in the code? even tho the configs say infinite...

I am unsure how to replicate it other then getting a large amount of health, im 99% sure it has nothing to do with the Odins ring, as i made a new world (test world) where the issues also was present without even touching the Ring.

I got 16 stacks of hearts, and growing, waiting on this issue to cease existing :)

**Comment by SilentChaos512** [comment]
Vanilla Minecraft has hardcoded caps on entity attributes (like max health). Scaling Health allows you to change this, but it's in the ASM config instead of the normal one (config/scalinghealth/asm.cfg). The vanilla cap is 1024, Scaling Health changes it to 2048 by default. Just remember that changing this value also changes the max health cap for mobs.

**Comment by andr9528** [comment]
well i feel dump now for not locking in that one file. but still thank you
time to get max int health! :)
