### ISSUE TITLE
Exclude fake players from level increase on players ?

### ISSUE THREAD

**Issue by tgstyle** [SilentChaos512/ScalingHealth#48]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.0-73
Silent Lib Version: 2.2.9-89

### Expected behavior
Right now if a player is in range of a fake player i.e. mob killer such as Draconic Evolution's Mob Grinder, they still level up. Is this intended?

Maybe add a built in black list for fake players? Should be easy to distinguish the two.

**Comment by SilentChaos512** [comment]
So difficulty is increasing as if another real player was in the area?

**Comment by tgstyle** [comment]
That is correct.

**Comment by SilentChaos512** [comment]
I would call that a bug, but it could be an interesting optional feature as well. Like adding a penalty for using mob grinders, should a pack maker choose to do so. But that should definitely be disable by default.

**Comment by SilentChaos512** [comment]
I'm not having any luck getting the Draconic Evolution mob grinder to actually affect difficulty. It's accumulating difficulty with kills, but the area difficulty stays the same. Mind sending me a screenshot with Scaling Health's debug mode enabled?

**Comment by tgstyle** [comment]
Interesting results after turning on debug mode. It appears you may be right that it has nothing to do with DE, I thought it may be the case as my difficulty kept increasing when I was doing nothing. However there was always a grinder actively killing mobs. So I assumed (bad me) it was the cause. However after turning debug mode on it just showed the difficulty is constantly increasing while just standing still. I tried a server and singleplayer, is this intended?

Screens from server.
![2017-10-09_17 19 04](https://user-images.githubusercontent.com/5832709/31362659-e4f12412-ad16-11e7-9f09-5a2232459165.png)
![2017-10-09_17 19 03_2](https://user-images.githubusercontent.com/5832709/31362661-e71ae00c-ad16-11e7-9892-21e9b1eacf84.png)

Screens from singleplayer.
![2017-10-09_17 22 14](https://user-images.githubusercontent.com/5832709/31362667-eee9f5b6-ad16-11e7-993a-b718c3f260a6.png)
![2017-10-09_17 22 29](https://user-images.githubusercontent.com/5832709/31362668-f060007a-ad16-11e7-8e85-bb9f8ceebdbe.png)


Edit: Screen 2 on the server shows "no modifiers! that should not happen" message too.

**Comment by SilentChaos512** [comment]
By default, difficulty does increase slowly over time and killing mobs has no effect. That can be tweaked in the config.

**Comment by tgstyle** [comment]
Ah I see that now, thought I covered the config pretty well. However the idea you have of penalizing players for mob grinders could be a good result of this =)

**Comment by tgstyle** [comment]
So after installing the new version, the server console is spammed with the blacklist mob entries, debug is disabled.

[11:28:52] [Server thread/INFO] [STDOUT]: [net.silentchaos512.lib.util.LogHelper:debug:31]: Cave Spider is blacklisted!

**Comment by SilentChaos512** [comment]
Huh, could have sworn I disabled debug lines in release builds.
(edit) Fixed in 1.3.1b. Build is compatible with 1.3.1, so updating both client and server is not necessary (if applicable).
