### ISSUE TITLE
Ability to change heart texture?

### ISSUE THREAD

**Issue by tetsune** [SilentChaos512/ScalingHealth#5]
I have a texture pack on and it changes to look of player health GUI (like most packs, I think?) and I've been working pretty hard to streamline all of my textures, but there doesn't seem to be a way to change the color/look of the overlaying heart texture (like Tinker's Construct did back in 1.7.10)

Is there a way to add this option?
Unless this is an option already, just please point me to a place to fix it c:

**Comment by SilentChaos512** [comment]
The heart textures themselves are [found here](https://github.com/SilentChaos512/ScalingHealth/blob/master/resources/assets/scalinghealth/textures/gui/hud.png). Currently, there's no way to change the colors, but I plan to fix that soon. But color changes will likely be done in the mod's config file.

How did TCon handle heart colors, by the way? I never really used that mod much.

**Comment by tetsune** [comment]
Got it to work! 
I'm not sure code-wise how TCon did their hearts retextured. It's not in the latest version (since 1.8.9 I think? Don't remember) But I know it was in the 1.7.10 and 1.6.4 versions they had the heart levels. Maybe check out their repository?
