### ISSUE TITLE
IG mod config not working

### ISSUE THREAD

**Issue by BadLucKWyvern** [SilentChaos512/ScalingHealth#50]
### Versions

Minecraft Version: 1.11.2
Scaling Health Version: 1.12-1.2.2-70
Silent Lib Version: 1.11.2-2.2.6-66

### Expected behavior

In game config mod option working

### Actual behaviour

currently... clicking on confing send me back to the game

### Steps to reproduce the problem

1. Press echap
2. Click mod option
3. looking for scaling health mod
4. click on config

**Comment by SilentChaos512** [comment]
Could you also send me a copy of your config file, please?

**Comment by BadLucKWyvern** [comment]
here's files from config folder called "scalinghealth"

2017-10-16 7:06 GMT+02:00 SilentChaos512 <notifications@github.com>:

**Comment by SilentChaos512** [comment]
I guess e-mail attachments don't get sent to GitHub, I don't see them. But I do remember there was a bug like this in one version. If your config files for SH have been around for a while, you might try deleting them and starting with a fresh copy.
