### ISSUE TITLE
Feature request - sleep punishment

### ISSUE THREAD

**Issue by m1jordanallen** [SilentChaos512/ScalingHealth#53]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: TBD
Silent Lib Version: TBD

### Expected behavior (requested behavior)

I am and have been using this mod in some hardcore packs. Including in a remake of madpack 2 (making it for the original creator). We would love to have a mechanic that would punish sleeping. Back in the day we used to set sleep to increase a certain amount of difficulty as to punish those who sleep. I would love to see that as a config in this mod. Yes, we could just disable sleeping, but this was a much more fun mechanic.

Thanks for considering and keep up the great work with the mod. It's quickly become a personal favorite.

**Comment by SilentChaos512** [comment]
Sounds like a great idea! What do you think would work best, just a configurable amount added each time the player sleeps?

Note to self: I believe I need to use PlayerWakeUpEvent for this.

**Comment by m1jordanallen** [comment]
Configurable amount would be amazing.  :D
