### ISSUE TITLE
Difficulty Meter Issue & Request

### ISSUE THREAD

**Issue by Preminenc3** [SilentChaos512/ScalingHealth#54]
The Difficulty Meter does not scale with the clients GUI.

Request: 

- Can you have RPG-Hud compatibility with thirst and temperature?
- Can you add a config to remove the health amount next to the hearts, I am using RPG-Hud and so I have no use for it.

**Comment by SilentChaos512** [comment]
1. It already changes with the GUI Scale setting.
2. What do you mean? Is Scaling Health preventing the other mod from working correctly?
3. That config already exists. Set "Health Text Style" under the client category to "DISABLED".

**Comment by Preminenc3** [comment]
Sorry for the late reply.
1. Sorry it was something off on my part
2. It does not conflict with the mod RPG-Hud, but when using the mod it changes the default MC Hud, and I just was hoping you and the creator of RPG-Hud could create some sort of compatibility so it would look more concise.
3. Thank you, I did not see that I am blind lol.
