### ISSUE TITLE
Heart Shard Recipe Missing

### ISSUE THREAD

**Issue by Punkalyn** [SilentChaos512/ScalingHealth#55]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.3-79
Silent Lib Version: 2.2.13-94

### Expected behavior

- Heart Shards can be crafted into Heart Containers

### Actual behaviour

- No recipe found for heart shards in JEI, or vanilla minecraft recipes.

### Steps to reproduce the problem

1. Config used below:

# Configuration file

main {
    # Draws random stuffs on the screen! And maybe does some other things.
    B:"Debug Mode"=false

    client {
        # Replace vanilla heart rendering.
        B:"Custom Heart Rendering"=true

        # The time (in ticks) to show the difficulty meter whenever it pops up. [range: 0 ~ 2147483647, default: 160]
        I:"Difficulty Meter Display Time"=160

        # Determines the color of the text next to your hearts. GREEN_TO_RED displays green at full health, and moves to red as you lose health. WHITE will just be good old fashioned white text. Set to PSYCHEDELIC if you want to taste the rainbow. [default: GREEN_TO_RED]
        S:"Health Text Color"=GREEN_TO_RED

        # Determines what the text next to your hearts will display. DISABLED will display nothing, ROWS will display the number of remaining rows that have health left, and HEALTH_AND_MAX will display your actual health and max health values. [default: ROWS]
        S:"Health Text Style"=ROWS

        # The colors for each additional row of hearts. The colors will loop back around to the beginning if necessary. Use hexadecimal to specify colors (like HTML color codes). [default: [bf0000], [e66000], [e69900], [e6d300], [99e600], [4ce600], [00e699], [00e6e6], [0099e6], [0000e6], [9900e6], [d580ff], [8c8c8c], [e6e6e6]]
        S:"Heart Colors" <
            bf0000
            e66000
            e69900
            e6d300
            99e600
            4ce600
            00e699
            00e6e6
            0099e6
            0000e6
            9900e6
            d580ff
            8c8c8c
            e6e6e6
         >

        # Sets position of the difficulty meter. Negative numbers anchor it to the right side of the screen. [range: -2147483648 ~ 2147483647, default: 5]
        I:"Position X"=5

        # Sets position of the difficulty meter. Negative numbers anchor it to the bottom of the screen. [range: -2147483648 ~ 2147483647, default: -30]
        I:"Position Y"=-30

        # Show the difficulty meter. Usually, it is displayed for a few seconds occasionally.
        B:"Render Difficulty Meter"=true

        # Render the difficulty meter at all times.
        B:"Render Difficulty Meter Always"=false

        # If difficulty is set to change when the player sleeps, they will be warned when they get in bed.
        B:"Warn When Sleeping"=true
    }

    player {

        health {
            # Allow Scaling Health to modify the player's health. Set to false if you have another mod that modifies player health, and you would like that mod to handle health modifications instead. With this option set to false, heart containers will not work, nor will the '/scalinghealth health' command.
            B:"Allow Modified Health"=true

            # The amount of health (in half hearts) the player will lose each time they die. [range: -2.14748365E9 ~ 2.14748365E9, default: 0.0]
            S:"Health Lost on Death"=55

            # The maximum amount of health (in half hearts) the player can reach. Zero means unlimited. [range: 0 ~ 2147483647, default: 0]
            I:"Max Health"=60

            # Allows players' health to be reset at certain frequencies.
            #   NONE - Do not do regular resets.  Weekdays (SUNDAY, MONDAY, etc.) - Reset on this day of the week. If the player does not play on this day, they will be reset the next time they log in.
            #   DAILY - Reset if the last time the player logged in was a different day.  MONTHLY - Reset if the last time the player logged in was a different month (everyone resets on the first of the month). [default: NONE]
            S:"Reset Time"=NONE

            # The amount of health (in half hearts) the player starts with. [range: 2 ~ 2147483647, default: 20]
            I:"Starting Health"=20
        }

        regen {
            # The number of ticks between each bonus regen tick (a half heart being healed). [range: 0 ~ 2147483647, default: 100]
            I:Delay=100

            # The number of ticks after being hurt before bonus regen activates. [range: 0 ~ 2147483647, default: 400]
            I:"Delay (Initial)"=400

            # Bonus health regen will be enabled. Vanilla regen is not changed in any way, this just adds extra healing!
            B:"Enable Bonus Regen"=true

            # The maximum food level at which bonus regen will be active. [range: 0 ~ 20, default: 20]
            I:"Food Max"=20

            # The minimum food level at which bonus regen will be active. [range: 0 ~ 20, default: 10]
            I:"Food Min"=20
        }

    }

    fake_players {
        # If enabled, fake players will be able to get heart container drops when killing mobs. Disabling should prevent at least some mob grinders from getting heart drops.
        B:"Can Generate Hearts"=false

        # If enabled, fake players can accumulate difficulty in the same way as real players. Enabling this could act as a sort of penalty for using mob grinders.
        B:"Have Difficulty"=false
    }

    mob {
        # A multiplier for extra attack strength all mobs will receive. Set to 0 to disable extra attack strength. [range: 0.0 ~ 3.4028235E38, default: 0.1]
        S:"Damage Modifier"=0.1

        # The chance that an extra potion effect will be applied to any hostile mob. Note that this effect requires the mob to have a certain amount of "difficulty" left after it has been given extra health and damage. So entering 1 won't guarantee potion effects. [range: 0.0 ~ 1.0, default: 0.375]
        S:"Potion Chance (Hostiles)"=0.375

        # The chance that an extra potion effect will be applied to any passive mob. Note that this effect requires the mob to have a certain amount of "difficulty" left after it has been given extra health and damage. So entering 1 won't guarantee potion effects. [range: 0.0 ~ 1.0, default: 0.025]
        S:"Potion Chance (Passives)"=0.025

        # Additional XP (as percentage) per point of difficulty. For example, if this is 0.01, a mob will drop 2x (+1.0x) XP at 100 difficulty and 3x (+2.0x) at 200 [range: 0.0 ~ 1.0, default: 0.01]
        S:"XP Boost"=0.01

        health {
            # Allow hostile mobs (monsters) to spawn with extra health based on difficulty.
            B:"Allow Hostile Extra Health"=true

            # Allow peaceful mobs (such as animals) to spawn with extra health based on difficulty.
            B:"Allow Peaceful Extra Health"=true

            # The minimum extra health a mob will have per point of difficulty. For example, at difficulty 30, a mob that normally has 20 health would have at least 50 health. [range: 0.0 ~ 3.4028235E38, default: 0.5]
            S:"Base Health Modifier"=0.5

            # The minimum extra health a peaceful will have per point of difficulty. Same as "Base Health Modifier", but for peaceful mobs! [range: 0.0 ~ 3.4028235E38, default: 0.25]
            S:"Base Health Modifier Peaceful"=0.25

            # Mobs listed here will never receive extra health, and will not become blights. There is also a separate blacklist for blights, if you still want the mob in question to have extra health. [default: ]
            S:Blacklist <
             >

            # Mobs will not gain extra health or become blights in these dimensions. Integers only, any other entries will be silently ignored. [default: ]
            S:"Dimension Blacklist" <
             >

            # Describes how extra mob health is applied. This will not change the health of mobs that already exist!
            #   ADD - Adds a value based on difficulty to the mob's health, ignoring the mob's default health.
            #   MULTI - Multiplies the mob's health instead of adding a flat value. For example, endermen
            #     will always have around twice the health of zombies with this option.
            #   MULTI_HALF - Multiplies the mob's health, but the value is reduced for higher-health mobs.
            #   MULTI_QUARTER - Same as MULTI_HALF, but the scaling factor is even less. [default: MULTI_HALF]
            S:"Scaling Mode"=MULTI_HALF=
        }

        blights {
            # The amplifier level on the speed potion effect applied to blights. [range: 0 ~ 99, default: 8]
            I:"Amplifier Speed"=8

            # The amplifier level on the strength potion effect applied to blights. [range: 0 ~ 99, default: 2]
            I:"Amplifier Strength"=2

            # Mobs listed here will never become blights, but can still receive extra health. There is also a blacklist for extra health. [default: [minecraft:wither], [minecraft:villager], [minecolonies:citizen]]
            S:Blacklist <
                minecraft:wither
                minecraft:villager
                minecolonies:citizen
             >

            # If enabled, no bosses can become blights. If you need more control, use the Blacklist instead.
            B:"Blacklist All Bosses"=true

            # Determines the chance of a mob spawning as a blight. Formula is blightChanceMulti * currentDifficulty / maxDifficulty [range: 0.0 ~ 3.4028235E38, default: 0.0625]
            S:"Blight Chance Multiplier"=0.0625

            # Should blights have the fire resistance potion effect?
            B:"Fire Resist"=true

            # Blight's fire will be set to ride the blight. This will make the fire follow the blight more smoothly and prevent it from bobbing. Disable if you are having issues.
            B:"Fire Rides Blights"=false

            # Should blights have the invisibility potion effect?
            B:Invisibility=false

            # Let all players know when a blight dies in chat.
            B:"Notify Players on Death"=true

            # The duration (in ticks) of the potion effects applied to blights. The effects are refreshed frequently, so this value doesn't matter in most cases... except for the lingering potion effects left by blight creepers. Set to -1 for infinite time. [range: -1 ~ 2147483647, default: 6000]
            I:"Potion Duration"=6000

            # Blight creepers will also be supercharged (like when they are struck by lightning).
            B:"Supercharge Creepers"=true

            # The multiplier applied to the amount of XP dropped when a blight is killed. [range: 0.0 ~ 1000.0, default: 10.0]
            S:"XP Multiplier"=10.0

            equipment {
                # The chance of an additional armor piece being given. Every blight receives a helmet, then has this probability of receiving a chestplate. If it gets a chestplate, it has this probability of receiving leggings, etc. [range: 0.0 ~ 1.0, default: 0.5]
                S:"Armor Piece Chance"=0.5

                # The chance that a blight will receive equipment in their hands (swords, etc.) They only get a chance at an offhand item if a main hand item is selected. Depending on the mods you have installed, there may not be any hand equipment to chose from. [range: 0.0 ~ 1.0, default: 0.5]
                S:"Hand Piece Chance"=0.5

                # The highest commonly-occuring equipment tier for blights. This goes from 0 to 4 inclusive. For armor, the defaults (tiers 0 to 4) are leather, gold, chainmail, iron, and diamond. [range: 0 ~ 4, default: 1]
                I:"Highest Common Tier"=1

                # The chance that a higher tier will be selected for a blight. A common tier is chosen first, then it has a few chances to increase. [range: 0.0 ~ 1.0, default: 0.095]
                S:"Tier Up Chance"=0.095
            }

        }

        ##########################################################################################################
        # potion
        #--------------------------------------------------------------------------------------------------------#
        # Potion effects applied to non-blights.
        ##########################################################################################################

        potion {
            # The potion effects that mobs can spawn with. You can add effects from other mods if you want to, or remove existing ones. Each line has 3 values separated by commas: the potion ID, the minimum difficulty (higher = less common), and the level (1 = level I, 2 = level II, etc). [default: [minecraft:strength,30,1], [minecraft:speed,10,1], [minecraft:speed,50,2], [minecraft:fire_resistance,10,1], [minecraft:invisibility,25,1], [minecraft:resistance,30,1]]
            S:"Mob Potions" <
                minecraft:strength,30,1
                minecraft:speed,10,1
                minecraft:speed,50,2
                minecraft:fire_resistance,10,1
                minecraft:invisibility,25,1
                minecraft:resistance,30,1
             >
        }

    }

    pets {
        # The number of ticks between regen ticks on pets. Set to 0 to disable pet regen. [range: 0 ~ 72000, default: 600]
        I:"Regen Delay"=600
    }

    items {
        # If enabled, heart crystal shards will drop instead of heart containers. [default: false]
        B:"Drop Shards Instead of Containers"=true

        # The chance of a hostile mob dropping a heart canister when killed. [range: 0.0 ~ 1.0, default: 0.01]
        S:"Heart Drop Chance"=0.01

        # The chance of a passive mob (animals) dropping a heart canister when killed. [range: 0.0 ~ 1.0, default: 0.001]
        S:"Heart Drop Chance (Passive)"=0.0

        # The maximum number of heart canisters that a blight will drop when killed. [range: 0 ~ 64, default: 2]
        I:"Hearts Dropped by Blight Max"=4

        # The minimum number of heart canisters that a blight will drop when killed. [range: 0 ~ 64, default: 0]
        I:"Hearts Dropped by Blight Min"=1

        # The maximum number of heart canisters that a boss will drop when killed. [range: 0 ~ 64, default: 6]
        I:"Hearts Dropped by Boss Max"=6

        # The minimum number of heart canisters that a boss will drop when killed. [range: 0 ~ 64, default: 3]
        I:"Hearts Dropped by Boss Min"=3

        # The amount of health that will be restored when using a heart container. [range: 0 ~ 2000, default: 4]
        I:"Hearts Health Restored"=0

        # If set to false, hearts will no longer increase the player's maximum health, but can still be used for healing.
        B:"Hearts Increase Max Health"=true
    }

    difficulty {
        # Defines how the area difficulty is determined when spawning a mob.
        #   AVERAGE - The average difficulty level of all nearby players.
        #   WEIGHTED_AVERAGE - Similar to average, but closer players have a greater impact on difficulty.
        #   MIN_LEVEL - The lowest difficulty level of all nearby players.
        #   MAX_LEVEL - The highest difficulty level of all nearby players.
        #   DISTANCE_FROM_SPAWN - Based on the mob's distance from spawn.
        #   DISTANCE_FROM_ORIGIN - Based on the mob's distance from the origin.
        #   DISTANCE_AND_TIME - Mix of DISTANCE_FROM_SPAWN and WEIGHTED_AVERAGE. [default: WEIGHTED_AVERAGE]
        S:"Area Mode"=WEIGHTED_AVERAGE

        # If a player sleeps through the night, add this much difficulty. Set to a negative number to subtract from the difficulty instead. [range: -1000.0 ~ 1000.0, default: 0.0]
        S:"Difficulty Added When Sleeping"=25.0

        # The amount of difficulty added per unit distance from the origin/spawn, assuming "Area Mode" is set to a distance-based option. Negative numbers will decrease difficulty over distance. [range: -1000.0 ~ 1000.0, default: 0.0025]
        S:"Difficulty Per Block"=0.0

        # The difficulty gained for each boss mob killed. Set to 0 to disable. Negative numbers cause difficulty to decrease with each kill. [range: -1000.0 ~ 1000.0, default: 0.0]
        S:"Difficulty Per Boss Kill"=-15.0

        # The difficulty gained for each hostile mob killed. Set to 0 to disable. Negative numbers cause difficulty to decrease with each kill. [range: -1000.0 ~ 1000.0, default: 0.0]
        S:"Difficulty Per Kill"=-0.05

        # Adds this much extra difficulty per additional player in the area. So, area difficulty will be multiplied by: 1 + group_bonus * (players_in_area - 1) [range: -10.0 ~ 10.0, default: 0.05]
        S:"Group Area Bonus"=0.05

        # Difficulty added per second is multiplied by this if the player is not moving. [range: 0.0 ~ 100.0, default: 0.7]
        S:"Idle Multiplier"=0.7

        # The amount of difficulty added each second. In Difficult Life, the option was named per tick, but was actually applied each second. Negative numbers will decrease difficulty over time. [range: -1000.0 ~ 1000.0, default: 0.0011574074]
        S:"Increase Per Second"=0.0011574074

        # The difficulty a player loses on death. Entering a negative number will cause the player to gain difficulty instead! [range: -1000.0 ~ 1000.0, default: 0.0]
        S:"Lost On Death"=0.0

        # The maximum difficult level that can be reached. Note that values beyond 250 are not tested, and extremely high values may produce strange results. [range: 0.0 ~ 3.4028235E38, default: 250.0]
        S:"Max Value"=250.0

        # Allows players' difficulty to be reset at certain frequencies.
        #   NONE - Do not do regular resets.  Weekdays (SUNDAY, MONDAY, etc.) - Reset on this day of the week. If the player does not play on this day, they will be reset the next time they log in.
        #   DAILY - Reset if the last time the player logged in was a different day.  MONTHLY - Reset if the last time the player logged in was a different month (everyone resets on the first of the month). [default: NONE]
        S:"Reset Time"=NONE

        # The distance from a newly spawned mob to search for players to determine its difficulty level. Set to 0 for unlimited range. [range: 0 ~ 32767, default: 160]
        I:"Search Radius"=160

        # The starting difficulty level for new worlds. [range: 0.0 ~ 3.4028235E38, default: 0.0]
        S:"Starting Value"=0.0
    }

    network {
        # The number of ticks between update packets. Smaller numbers mean more packets (and more bandwidth and processing power used), but also less client-server desynconfig. [range: 1 ~ 1200, default: 20]
        I:"Packet Delay"=20
    }

    world {

        heart_crystal_ore {
            # The maximum number of extra veins created by distance from spawn. [range: 0.0 ~ 1000.0, default: 3.0]
            S:"Extra Vein Cap"=3.0

            # The number of extra possible veins per chunk away from spawn. The default value will reach the cap at 50,000 blocks from spawn. [range: 0.0 ~ 1.0, default: 9.6E-4]
            S:"Extra Vein Rate"=9.6E-4

            # The highest y-level the ore can be found at. Must be greater than Min Height [range: 0 ~ 255, default: 35]
            I:"Max Height"=35

            # The lowest y-level the ore can be found at. Must be less than Max Height [range: 0 ~ 255, default: 10]
            I:"Min Height"=10

            # The base number of heart crystal shards dropped by the ore. Fortune III can double this value at most. [range: 1 ~ 64, default: 1]
            I:"Quantity Dropped"=1

            # The size of each vein. [range: 0 ~ 10000, default: 6]
            I:"Vein Size"=6

            # The number of veins per chunk. The fractional part is a probability of an extra vein in each chunk. [range: 0.0 ~ 10000.0, default: 0.42857143]
            S:"Veins Per Chunk"=0.42857143
        }

    }

}

zzlastversion {
    I:last_build=79
}

**Comment by SilentChaos512** [comment]
Reproducible in a clean instance with latest Forge. A recipe shows up in JEI, it just has no ingredients. What Forge version are you using?

**Comment by Punkalyn** [comment]
forge-1.12.2-14.23.0.2552-installer-win.exe

**Comment by SilentChaos512** [comment]
Looks like 2552 fixed some kind of recipe bug. I guess that's what broke my recipe. At least one recipe is broken in Silent's Gems too.

**Comment by Punkalyn** [comment]
Thanks for the quick responses~ You and your mod are fantastic and I hope forge didn't break it too badly xD
