### ISSUE TITLE
Difficulty "Struggle"

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/ScalingHealth#57]
This is an enhancement/idea for the mod to hopefully improve it and add some options to the gameplay attached to it and give some ideas to modpacks. (specifically I was thinking in my own these could be nice features as a sort of "struggle" effect)

1. The ability to make the killing of specific mobs make the difficulty add or subtract an amount. Basically a config that lets you put in entity names of mobs then an amount next to it that let you specify mobs that will either increase or decrease the difficulty when defeated by players. This amount could also specify a set amount and then a multiplier which multiplies said change for if the mob is a blight and it is defeated.

Example:

Minecraft:Zombie.1,-20

(this would be a zombie increases dif by 1 when it's killed. but a blight decreases by 20. if you wanted a skeleton to only increase or decrease when it's a blight the first number would remain zero, but the second number could be like 15.)

2. Items in the mod that can be used to increase or decrease the difficulty ingame which can be enabled and disabled.
plus the ability to specify useable items that when used will increase or decrease the difficulty. Such as the curse pearl thingies from Quark that allow mobs to spawn around you anywhere.

3. The ability to specify dimension numbers and a multiplier for difficulty gain or loss while in that dimension. (could create something like, difficulty goes up while on overworld and nether. goes up 50% faster in the end, but while in some other custom dimension difficulty doesn't change or goes down instead.

Please consider these. :)

**Comment by SilentChaos512** [comment]
Thanks, those are some great ideas! They should all be relatively easy to
implement too.

**Comment by Darkmega18** [comment]
Do you also have the ability to have something pick up on "time skipped" via sleeping and have it apply a multiplier or negative multiplier in a way? cause I remember difficulty life could penalize people for sleeping, which is kinda what I want to do also if possible. :3

**Comment by SilentChaos512** [comment]
A sleep config was added recently (#53). It adds a configurable amount each time the player sleeps through the night.

**Comment by Darkmega18** [comment]
:O well, I know what I'll be changing up tonight. but yeah, please and thank you on my ups and downs by specific mobs configurables request. :) although, do blights count as bosses? cause I notice you've got a blanket version already in the mod with mob kills and boss kills increase/decrease rates. Or are blights just highly overpowered normal mobs?

**Comment by SilentChaos512** [comment]
Blights are not bosses, just buffed up standard mobs. As far as I know, there's no way to tell Minecraft that you want a standard mob to be a "boss". Only certain entity classes are bosses (the dragon, wither, etc.)

I didn't realize I was missing a difficulty per blight kill config. Adding that now. Also working on item 1 in your list right now. I plan to implement all of them, just been very busy lately.

**Comment by Darkmega18** [comment]
Yeah, I didn't think you had a way to tell them as different and were just ultra buffed super units. Even if they do move like the flash and hit like Thor. lol But alright cool, glad I brought it up then.
and ok, that should be cool. So I should possibly go through better questing's mob list to pick up what their registered names are so I can think of what I can make that causes difficulty spikes or maybe difficulty drops. :D

**Comment by Darkmega18** [comment]
Is there a possible ETA on when I can possibly expect to get item use difficulty changes or not yet? Since I was reminded of it when a couple of my testers for my pack asked if there was a way to get the difficulty down incase they keep dieing (that doesn't involving killing blights/bosses, since thats mostly only how to get it down on my side).

By default I think you should make a "cursed heart" and "Enchanted Heart" which can't be crafted naturally but can be configured by modpack authors using their selected crafting recipe tweaker mod to add them in.

When cursed heart is used it should charge the player with ender particles then release a burst of dark particles from the player that increase difficulty based on the configuration. While the enchanted heart should infuse you with enchanting particles and decrease the difficulty based on config atleast as a base for those who are lazy and/or don't have many useable consumeable items that can be used for difficulty purposes.

**Comment by SilentChaos512** [comment]
I'll try to get that out tonight/tomorrow.

**Comment by Darkmega18** [comment]
Wonderful. :D Thanks again. :)

**Comment by SilentChaos512** [comment]
Difficulty changers will be usable in 1.3.6, but need some polishing. No special effects yet, just right-click and it instantly consumes. I'm marking the build as a beta. Should be available for download within the hour.

**Comment by Darkmega18** [comment]
got the hearts and the fix for the entity lists! so hopefully the toroquest mobs work. Awesome, legendary even. Thanks!
