### ISSUE TITLE
Null Pointer Exception: Ticking Entity

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#58]
### Versions

Minecraft Version: 1.12
Scaling Health Version: 1.3.4
Silent Lib Version: 2.2.13

Every time I create a world, I get the error java.lang.NullPointerException: Ticking entity
at net.silentchaos512.scalinghealth.utils.EntityMatchList.contains(EntityMatchList.java:26)

[crash-2017-11-26_08.22.33-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/1545172/crash-2017-11-26_08.22.33-server.txt)

**Comment by SilentChaos512** [comment]
Seems like you uploaded the wrong crash report.

**Comment by ZalxMage** [comment]
[crash-2017-12-09_17.34.57-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/1545934/crash-2017-12-09_17.34.57-server.txt)

**Comment by ghost** [comment]
[crash-2017-12-09_17.34.57-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/1545939/crash-2017-12-09_17.34.57-server.txt)
Sorry

**Comment by SilentChaos512** [comment]
Could you upload your config file as well, please?

**Comment by ghost** [comment]
renamed from .cfg to .txt

[asm.txt](https://github.com/SilentChaos512/ScalingHealth/files/1546258/asm.txt)
[main.txt](https://github.com/SilentChaos512/ScalingHealth/files/1546259/main.txt)
