### ISSUE TITLE
Suggestion: Difficulty scaling with lunar phases.

### ISSUE THREAD

**Issue by BeardStroker** [SilentChaos512/ScalingHealth#59]
I have been using a really cool mod called Astral Sorcery that makes you pay more attention to the moon phases, and I like the thought of mobs growing stronger during certain lunar stages. Either the classic "during the full moon the monsters come out" or since mobs dislike light so much, gradually  getting stronger, and peaking during the new moon. 

Not sure if it's possible, but thought I'd suggest it :)

**Comment by SilentChaos512** [comment]
Interesting idea, I'll give it some thought.

**Comment by Darkmega18** [comment]
This seems like a tasty addition I could get behind. possibly a list in the config for the different phases that the player can set up? sorta like hardcore darkness where you can set in a list how much sky light there is (usually zero in no moon, to around 0.3 of max light level during a full moon).

I'd suggest possibly an interaction of each phase being set to a multiplier which multiplies the current damage, health etc per difficulty by an amount based on the current moon phase in dimensions specified in another config to tell it which dimensions should be affected by moon difficulty in the case of having other dimensions or a mod like Just enough dimensions allowing you to make other overworld style dims.

:D

**Comment by SilentChaos512** [comment]
Added for next version. You can set a multiplier for each of the eight moon phases. The feature is disabled by default.
