### ISSUE TITLE
Blacklist mobs

### ISSUE THREAD

**Issue by bondgb** [SilentChaos512/ScalingHealth#6]
Would love the ability to blacklist mobs and be able to disable scaling for passive mobs.

**Comment by SilentChaos512** [comment]
There are configs to disable extra health for hostile and peaceful mobs separately (mob > health > Allow Hostile/Peaceful Extra Health), but it looks like they aren't working. I'll look into fixing that.

The next version of the mod will add blacklists for extra health and blights. It's already been implemented (f3145869ca19175e0aadf8aa79e37d73e6329527).

**Comment by Willy1123** [comment]
hi, I am at mc 1.20.1 with forge 47.3.0, and I am trying to find the config to add CustomNPCs-Unofficial mod to the blacklist so the NPC can't have blights effect, but I can't find it, where can I modify it? Ty

**Comment by SilentChaos512** [comment]
@Willy1123 There should be tags for marking entities as exempt from difficulty or becoming blights.

**Comment by Willy1123** [comment]
ooh, I saw it. This config is only by datapack, right?
