### ISSUE TITLE
Suggestion:  Morpheus Support

### ISSUE THREAD

**Issue by DoragonKeiyou** [SilentChaos512/ScalingHealth#60]
Currently the server mod Morpheus allows a configurable amount of people (default is 50%) to sleep in the overworld and skip to the next day instead of having everyone online be asleep, but if this sleep is triggered in this manner, the difficulty that could be added or subtracted is bypassed.

**Comment by SilentChaos512** [comment]
Does this happen only for those who didn't actually sleep, or everyone?

**Comment by DoragonKeiyou** [comment]
It happens for no one:

Player A and Player B are online.

Player A sleeps and fulfills the "50% needed to count as sleep for the whole server".

Player A wakes up and their difficulty does not change.  Player B did nothing but stand still, so no change would happen anyway.

**Comment by DoragonKeiyou** [comment]
It functions as intended, thanks!
