### ISSUE TITLE
Difficulty by mob doesn't seem to be working

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/ScalingHealth#61]
### Versions

Minecraft Version: 112.2
Scaling Health Version: ScalingHealth-1.12-1.3.5-82
Silent Lib Version: SilentLib-1.12-2.2.16-97

        # Lets you set difficulty changes for individual mobs. Each line has 3 values separated by spaces: entity ID, standard kill change, blight kill change. For example, entering "minecraft:zombie 0.1 -20" will cause zombie kills to add 0.1 difficulty, but killing a blight zombie will remove 20 difficulty instead. [default: ]
        S:"Difficulty Per Kill By Mob" <
            toroquest:toroquest_sentry 5 20
            toroquest:toroquest_village_lord 200 500
            toroquest:toroquest_guard 5 20
            mca:villagermca 10 50
            minecraft:villager 10 50
         >

should be making kills on the sentries and guards etc make difficulty go up.

### Actual behaviour

I kill them in singleplayer and in creative. no change. world does have 0.5 multiplier currently. but that should still be a 2.5 increase.

Am I just doing it wrong? I got the full entity id from out of better questings entity list and copied them exactly. MC villager works. but toroquest's stuff doesn't. MCA villagers don't work either. Although I'm not sure if thats related to that they don't show up properly in the quest book cause they've got so many different permutations of looks and stuff.

seems to possibly not parse other mods stuff sometimes. since my blacklist for HP works for toroquest mobs it seems. but it's not working for the MCA villagers cause they have a bit more than 50 health now although I told them to have 40. :V

**Comment by SilentChaos512** [comment]
Looks like matching for mod entities in general is broken. Should be easy enough to fix. Sorry it took me a couple days to get back to you.

**Comment by Darkmega18** [comment]
Hey thats fine, stuff happens, people get busy. There was a issue for someone not having scaling work at all for some mobs, so that might be worth a look at too since that seems related to this issue too.
