### ISSUE TITLE
[Suggestion] Add players difficult level to Scoreboard

### ISSUE THREAD

**Issue by Discomanco** [SilentChaos512/ScalingHealth#62]
Currently on our 1.12 expert server we show players Deaths on the Online List.
Was given the suggestion of setting it to Difficulty Level instead, which I thought was a nice idea, but it seems like it's not supported. Or at least I couldn't find the Objectives name for it.
It may exist, but I currently can't Tab through the objective options, since there's too many for the client to handle, so it crashes.

**Comment by SilentChaos512** [comment]
I doubt there's any way to do that right now, I'll see what I can do. I've never done objectives before.

**Comment by SilentChaos512** [comment]
Uploading version 1.3.6 as a beta, should be available to download sometime soon. The scoreboard criteria is "scalinghealth:difficulty" (minus the quotes). I haven't had much time to test it, so I'm leaving the issue open for now.
