### ISSUE TITLE
{Suggestion] Quest scaled difficulty

### ISSUE THREAD

**Issue by Sabrewulf** [SilentChaos512/ScalingHealth#63]
Can you add a feature for detect how many quest from HQM and BQ was completed and scale the health based on it?
I'm a slow player so i usually take to much time for build, actually i see some modpack using your mod to difficulty by time, would be nice if it be controlled by player progression.

**Comment by SilentChaos512** [comment]
Might be better to have a way for quests to increase difficulty themselves. I'm not too familiar with how the quest mods work, so this will take some research to decide what's best.
