### ISSUE TITLE
Difficulty isn't raising custom mobs from other mods hp.

### ISSUE THREAD

**Issue by Wrethic** [SilentChaos512/ScalingHealth#64]
### Versions

Minecraft Version: 1.12.1
Scaling Health Version: 1.12.1.3.5-82
Silent Lib Version: 1.12-2.2.16-97

### Expected behavior

- AbyssalCraft, Forestry, Embers, Lycanite Mobs, Natura, and Roots are all installed on my server along with scaling health, and expecting their damage and health to increase with difficulty.

### Actual behaviour

- No scaling health on external mod mob entities.

### Steps to reproduce the problem

1. Install external mods to server
2. Connect with config at higher base difficulty
4. Profit

**Comment by SilentChaos512** [comment]
Everything seems normal to me. A couple of things:
1. What about vanilla mobs?
2. What are you using to check mob health?
3. What difficulty values have you tried? Have you tried changing it with the "/scalinghealth difficulty" command? Try large numbers like 100, for instance.
4. Make sure you check freshly spawned mobs.

Forgive me if any of those seem obvious, I just want to make sure we're on the same page.

**Comment by Wrethic** [comment]
Okay did some digging to try to see what truly is the issue here. 
1. All vanilla aggressive mobs are scaling properly
2. Checking mob health is WAILA
3. I've tried 100 200 300 and 0
4. Killall commanded to test out difficulties.

- Update - Seems to be something to do with non-aggressive mobs (pigs, cows) : Anything in this category is not scaling right even after config options changing to favor it. Problem is lycanite uses non-hostile mobs that attack when provoked and classifies them with animals. So those non-aggressive mobs are sitting on a set amount of hearts no matter what difficulty changes, along with chococraft chocobos and all minecraft farming animals. The aggressive lycanite mobs are scaling properly. Same goes with other mods that use these different aggression systems. Do you know of any mods that can overlap your scaling health on the animals?

Edit* Looks like lycanite has custom configs for certain mobs, but not all. The ones without seem to be scaling properly. Is there a way this could be overwritten or anything? It may mainly be lycanite, but my neutral animals still aren't scaling.

**Comment by SilentChaos512** [comment]
I do remember Lycanites mobs having trouble in the past. It sets health in
a weird way, if I remember correctly. I'll look into this when I get home
from work.
Peaceful mobs were still scaling correctly last time I checked. Try a fresh
config file (copy the main.cfg to another folder, delete the original.)

**Comment by Wrethic** [comment]
I wouldn't know how to re-create the problem, but it seems generating the world over again fixed the issue of neutral mobs. Lycanite will probably have to be looked at more closely.

**Comment by m1jordanallen** [comment]
I am currently using the same versions across the board aside from I am in MC version 1.12.2.  And lycanite mobs among all other modded mobs are properly increasing in health. Lycanite is up to date if that helps.  Also been using these mods together since inception of both mods in 1.12.    Never ran into this.

Currently running forge 2582
