### ISSUE TITLE
[Suggestion] Daily loss of Health

### ISSUE THREAD

**Issue by Xaikii** [SilentChaos512/ScalingHealth#65]
Currently the configs are able to reset DAILY (rl) if I understood it right, would it be able to add a config that a player will lose every MC Day a configurable amount of health and if Health reaches =<0 the player dies and get revived with a the starting health Value.

Note:
I am not sure if this is the right format since the pregenerated one was for issues

**Comment by SilentChaos512** [comment]
Removing the template for feature suggestions is fine, it's more of a guide for bug reports.

So, we need:
- [ ] An option to reset every Minecraft day.
- [ ] A config to specify an amount to subtract from health, instead of doing a total reset.
- [ ] A config to kill the player if their max health would become zero.

**Comment by Xaikii** [comment]
Not directly a reset every Minecraft Day.

I mean it is a good a option if somebody wants that the mobs are pretty strong at night and weak at day time, I was thinking about every Minecraft Day losing/adding 2 Difficulty

**Comment by SilentChaos512** [comment]
Right, I understood. I want to make MC day resets an option, but I'll also add configs to make the resets reduce the value by some amount instead of a complete reset. That's what makes the most sense to me, since the mod already a system that modifies health/difficulty at certain intervals.

**Comment by mikemorana** [comment]
I had the idea to have gradually diminishing health and came in to suggest it. I, for one, am excited to see this feature added. I feel like it gives the hearts continued value after hitting a cap. You've gotta keep killin' if you wanna maintain your health cap. Very balancing feature, imo! MC day resets and zero-kills are brilliant too.
