### ISSUE TITLE
[Suggestion] Blight taking no Damage by Fake Players

### ISSUE THREAD

**Issue by Xaikii** [SilentChaos512/ScalingHealth#66]
Well the Title says already everything :')

And the reason is simple to prevent mob farming, if Blight are not able to die from the farms they'll overflow the Farm and negate the effectiveness of Mob Farms(Unless the Player kills them manually).

**Comment by SilentChaos512** [comment]
Sounds good. Should be simple enough to do.

**Comment by Darkmega18** [comment]
They're usually armored enough that they're practically immune to most forms of spikes and stuff unless a player with some good equipment comes by and takes a poke at them. especially those witches, healing and being armored and enchanted up etc.
