### ISSUE TITLE
Blights go from reasonable damage to insta-kill randomly (1.12.2)

### ISSUE THREAD

**Issue by nikoptune** [SilentChaos512/ScalingHealth#68]
Title is the TL;DR. On occasion when fighting blights (with a whole lot of armor on me), they do reasonable amounts of damage most of the time, but after some time fighting them, the damage they deal goes from reasonable to instant-kill, even through the armor. It's very odd considering I also have scaled my health up quite a bit (currently I'm at 162 max).

**Comment by SilentChaos512** [comment]
Blights are more or less unchanged from Difficult Life. I think DL intended for blights to be run from in most cases. But I guess I encouraged blight-hunting by adding the heart drops... I would suggest reducing the strength amplifier in the blight configs. Still, I guess blights could use some testing and balancing.

**Comment by Darkmega18** [comment]
Agreed. Whenever I run into one in a dungeon, I'm pretty much fucked unless I can placed some blocks down to hamper it then run, or cheese it from somewhere. so in mine I atleast scaled down their speed so they don't practically teleport onto you and Dragonball Z you. :V

**Comment by SilentChaos512** [comment]
Should be enough options to work with now. Re-open if necessary.
