### ISSUE TITLE
[1.10.2] Incompatibility with health gains from Kingdom Keys Re:Coded

### ISSUE THREAD

**Issue by Alaberti** [SilentChaos512/ScalingHealth#7]
Kingdom Keys has a system where every few levels you gain 5 health, but when using it and your mod it seems your health system completely disregards the health changes from that mod. Is there a compat layer you two could work out or at least a config option from your side to turn off the health system?

Thanks!

(for your reference: http://wehavecookies56.co.uk/Kingdom-Keys-Re-Coded/)

**Comment by SilentChaos512** [comment]
I can add a config option to stop Scaling Health from altering player health, at least. I might be able to find a way to make the two mods compatible, but I don't have a lot of time right now.

**Comment by Alaberti** [comment]
The config works, I'll take it
