### ISSUE TITLE
Blight equipment seems pretty good

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/ScalingHealth#70]
![2018-01-10_19 23 25](https://user-images.githubusercontent.com/8104689/34762721-e268a4f8-f63c-11e7-970c-c20a00d45d8c.png)
Caption: "U fukin wot, m8?"

The enchantments go off the page for this blight's gear. I believe it came from a golden blight skelly that dropped into my grinder. My difficulty wasn't even that high. was only like 12 and then it went down to zero with his death.
Mod version is ScalingHealth-1.12-1.3.7-87.

**Comment by NielsPilgaard** [comment]
I've seen these over-enchanted items multiple times - The shear size of the NBT tag can cause crashes.

**Comment by Discomanco** [comment]
Also confirmed (co-developer with Niller).
If you hold enough of super-enchanted items, you run into problems such as

![](https://cdn.discordapp.com/attachments/396041096179744768/401022364030205952/image.png)

Really becomes a problem when you spot lots of these: 
![image](https://user-images.githubusercontent.com/4707702/34832513-8374fe16-f6ea-11e7-9609-d31199a24eac.png)

**Comment by SilentChaos512** [comment]
I'll get this fixed ASAP, probably later tonight.

**Comment by SilentChaos512** [comment]
Easier fix than I thought, 1.3.8 should be available soon.

**Comment by Darkmega18** [comment]
Ha, nice. but yeah, real soviet enchantments = wtf. glad I reported this one, cause as entertaining as it is to find such extreme loot, that i'm not even sure if it works or not, thats probably pretty nasty. I'd guess since the blight went down relatively easily and wasn't a god or anything it's just visual but deadly to the game itself.
