### ISSUE TITLE
Suggestion: Individual player exemption/blacklist for difficulty

### ISSUE THREAD

**Issue by shdwdrake8** [SilentChaos512/ScalingHealth#71]
Suggestion: Provide a player blacklist in the config for the difficulty.

Reason: I run a server that has the most casual AND hardcore players and some of them are not interested in being punished with higher difficulty for playing the game. A simple way to exempt them from difficulty in the config would be amazing.

Thank you.

**Comment by SilentChaos512** [comment]
Will do. I will probably make it treat exempt players as having zero difficulty, so it will average out if exempt and non-exempt players are in the same area.

**Comment by shdwdrake8** [comment]
Perfect, thanks for your willingness and quick response! Love your work.

**Comment by SilentChaos512** [comment]
Version 1.3.9 is uploading, should be available in a few minutes. Sorry it took me a while to get to this.
