### ISSUE TITLE
mob drops with tags

### ISSUE THREAD

**Issue by ShaCraft** [SilentChaos512/ScalingHealth#74]
### Versions

Minecraft Version: 1.12,2
Scaling Health Version: 1.3.8-88
Silent Lib Version: X.X.X

### Expected behavior

Mob drops items that stack with other items of the same type

### Actual behaviour

Mob drops are getting  tags " ()" added to the end of the drop making them not stack. 
Example:
minecraft:coal
minecraft:coal()

### Steps to reproduce the problem
kill a mob
collect drops

**Comment by SilentChaos512** [comment]
Not seeing this on my end. What led you to believe Scaling Health is at fault?
