### ISSUE TITLE
Distance + Time Difficulty scale not working as expected when distance is set to negative numbers

### ISSUE THREAD

**Issue by ItsKestrel** [SilentChaos512/ScalingHealth#75]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.12-1.3.5-82
Silent Lib Version: 1.12-2.2.16-97

### Expected behavior

- Difficulty to increase while remaining in one area, while decreasing when moving further from spawn.

### Actual behaviour

- Difficulty only increases, seemingly ignoring the distance modifier, and solely based on time.

### Steps to reproduce the problem

1. Set Area mode to Distance_And_Time
2. Set Difficulty Per Block to negative value (-10)
3. Set Increase Per Second to positive value (1)
4. Test shows that the difficulty only increases (about 1 per second) even while running (about 5 blocks per second)

**Comment by SilentChaos512** [comment]
Confirmed, and I see what the problem is.
