### ISSUE TITLE
Please add min-max damage amplifier

### ISSUE THREAD

**Issue by DBotThePony** [SilentChaos512/ScalingHealth#78]
Instead of randomFloat * maximalDamage, because at some point damage from melee mobs start to be based on wild randomness (some of zombies deal 4-6 hearts, some of them >40 hearts)

Also is it possible to implement ranged enemies damage scaling without "hacks"?

**Comment by SilentChaos512** [comment]
Will do. Kind of related issue here: https://github.com/SilentChaos512/ScalingHealth/issues/68.

I don't think there is any easy way to change ranged damage on mobs. I don't see any events, so I think it would require ASM.

(edit) Not sure how to best work in a minimum value. I might just be too tired at the moment. But I'll at least add a maximum config.
