### ISSUE TITLE
[Sugestion] Boolean config to Blacklist Passive Mobs from being blights.

### ISSUE THREAD

**Issue by Liryax** [SilentChaos512/ScalingHealth#79]
There is already a boolean config to do that with Boss Mobs, but I suggest to also have one for passive mobs. As Blights Mobs are supposed to be a powerful version of a regular mobs, it don't really make sense to see a Blights Bat or a Blight Cow in the world, and it also make a kind of too easy way to get Hearts Drop from them and to lower difficulty if we configured killing Blight with a negative difficulty modifier.
Even though they can be blacklisted one by one, it seems like a configuration that would be widely used and would avoid to perform this time consuming task to any other player as well, and avoid having to reconfigure the mod after adding a mod that add more passive mobs.

(Additionally, I think the Boss boolean Blacklist should also exist for the health modifier, even though there is only two of them, this would as well avoid having to reconfigure this mod after adding more bosses through other mods)

**Comment by SilentChaos512** [comment]
Also added a config to blacklist all hostile mobs from becoming blights, just for completeness. I'll have to upload the new version tomorrow, I'm out of time right now.
