### ISSUE TITLE
Feature request command to turn on and off.

### ISSUE THREAD

**Issue by mando222** [SilentChaos512/ScalingHealth#80]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.5.82
Silent Lib Version: 2.2.16-97

I am making a mod pack and it is story/quest driven.  We are using a questing mod that can run console commands.  One quest would "remove the curse" from the land (turn of dmg scaling).  Is there a way we could get a console command to do this?

**Comment by SilentChaos512** [comment]
Turn off just extra damage, or extra health on mobs too?

**Comment by mando222** [comment]
It would be both.  Something like a turn the effects of the mod on and off from console.

**Comment by SilentChaos512** [comment]
I decided to use a game rule for this. So you can use "/gamerule ScalingHealthDifficulty false" to turn off the difficulty system. I'll try to get the new version uploaded sometime today/tomorrow.
