### ISSUE TITLE
false health altering on login

### ISSUE THREAD

**Issue by Kenshij** [SilentChaos512/ScalingHealth#88]
### Versions

Minecraft Version: 1.12
Scaling Health Version: 1.12-1.3.11-91
Silent Lib Version: 1.12-2.2.16-97

### Expected behavior

- after login same health level, like logout

### Actual behaviour

- have over "max_health" entry, logout and the relog back to the world, health ist at "max_health" entry and not at the "health" entry saved and starts sucking hunger to go to previous "health" entry   

Have looked into the ntb data and manipulated it to track the source, its the "max_health" entry from this mod. If other mods alter the health this mod seems to set the health on login to its "max_health" entry instead of let them like it was, even the right health is saved in the "health" entry.

Please don't alter the health on login.

**Comment by SilentChaos512** [comment]
What other mods are affecting health?

**Comment by Kenshij** [comment]
in File 
ScalingHealth/common/net/silentchaos512/scalinghealth/event/ScalingHealthCommonEvents.java
      
Line 198 and 199 
if (health > maxHealth && maxHealth > 0)
        player.setHealth(maxHealth);

Function  public void onPlayerJoinedServer(PlayerLoggedInEvent event)

is the source of the problem in the code



Cyclic is such a mod, it has some own ntb data and an player attribute what gives bonus health on eating heath container from this mod.

**Comment by SilentChaos512** [comment]
It's generally best to only let one mod modify health. Cyclic in particular
is an issue because it alters health without attribute modifiers (at least
it did last I looked). So SH would likely override it even if that one line
was changed. I'll still take a look into this when I get home, see if
anything can be done.

**Comment by Kenshij** [comment]
After more testing and working on a workaround, its not cyclic ist another mod [Nutrient](https://github.com/WesCook/Nutrition/wiki/Nutrients), adds an buff Thoughness wich gives 20 healths, is registered in attribute modifiers.

Whats the purpose of hard setting the players health back to the mods own saved max health value on login, when the players health value is over the mods max value ? 
The player must have archived somehow to get over your modded max value and thats nor a problem nor a mistake. But its only my oppinion that the lines that prevent this are obsolate ^^''

**Comment by SilentChaos512** [comment]
It might be unneeded. I think that line is from the original Difficult Life
code. I mostly left the code alone, unless there was a need to change it.
