### ISSUE TITLE
Area Mode for 'Distance to Spawn' doesn't truly stop at the max cap value

### ISSUE THREAD

**Issue by Ghostrider231** [SilentChaos512/ScalingHealth#89]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.11-91
Silent Lib Version: 2.2.16-97

### Expected behavior

- Scaling should actually stop at the max cap value if the player is far enough from spawn, even when too far. Mobs should no longer receive any futher buffs whenever the player is far enough or way too far.

### Actual behaviour

- Being way too far from spawn renders any mobs unkillable (Sets their health to 0) and also makes them immune to projectiles. The Difficulty bar also bugs out by rolling back to 0. 

### Steps to reproduce the problem

1. Load a world, New or not.
2. Have Area Mode set to 'Distance to Spawn'.
3. Get away from the spawn as far as until the difficulty starts going from 250 to 0 abruptly.   (IE: /tp command inputting some absurdly huge number) (EX: /tp @p ~10000 ~ ~)
4. Find a mob, and then attack it.
5. Mobs will receive the damage, but won't lose any health. Arrows and any projectiles will phase right through them. (Any Mob HP Hud mods also shows me they have 0/0 health)

### Description

Apparently being way too far from the world spawn point actually makes mobs unkillable. And yes, I've tested this with and without other mods around and even with the default config provided. The same thing happens, except the default config happens closer. (Approximately, 46147 from spawn.)

**Comment by SilentChaos512** [comment]
Looks like the distance calculation is overflowing. Easy enough to fix. I'll also look for a way to fix the broken entities.
