### ISSUE TITLE
Weird Crash having to do with Chickens.

### ISSUE THREAD

**Issue by BritishMindslave** [SilentChaos512/ScalingHealth#9]
I recently added a couple mods on my world that had worked fine previously. Now I get this crash when I go to start up the world. I looked through the crash and it seems chickens are causing it, though I hadn't had this issue before. I don't think the two mods I recently added have anything to do with these particular mobs.

Can you peek at the code and tell me what I need to do to get my world working again?
[crash-2016-10-09_13.15.36-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/518462/crash-2016-10-09_13.15.36-server.txt)

**Comment by SilentChaos512** [comment]
I'm uploading a new build to CurseForge now. Let me know whether or not it fixes the issue.

**Comment by BritishMindslave** [comment]
Nope, seems like I crashed again!
I tried to blacklist chickens and it didn't load my world at all.

[crash-2016-10-10_17.09.01-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/520437/crash-2016-10-10_17.09.01-server.txt)

**Comment by SilentChaos512** [comment]
OK, uploading another build (0.2.5b). If this one crashes as well, maybe it will give more information, but I can't think of anything else on that line that could be null.

**Comment by BritishMindslave** [comment]
I updated Scaling Health and tried it, then I loaded a backup from the last time I played and tried as well. It doesn't crash, at least I'm not sure if it does outright, because it stays stuck on the "Building Terrain" screen. i have waited about 10 minutes on each with nothing. =u=; When I force it to crash with Task Manager, it seems to be the null pointer exception again.

I attached the crash report here too. 
[crash-2016-10-12_09.42.44-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/524705/crash-2016-10-12_09.42.44-server.txt)

I really appreciate your helping with this, by the way!

**Comment by SilentChaos512** [comment]
It's looking like some other mod is causing the crash, but I think I can prevent it at least. Those last two crash reports gave me a bit more info, so I think I've got it. Uploading build 0.2.5c now. Let me know if you still have any problems with that one.

Thanks for your patience, I know working through this is frustrating.

**Comment by SilentChaos512** [comment]
I'm going to assume this is fixed, let me know if you are still having issues.

**Comment by BritishMindslave** [comment]
I'm so so sorry it's been a while since I've been around! I had the longest work week of my life with no time to check on it LOL
It still crashes without actually crashing the game.
[idk if this is any different.txt](https://github.com/SilentChaos512/ScalingHealth/files/537090/idk.if.this.is.any.different.txt)

I might have to try and see what I need to downgrade, in terms of mod updates. I just have no idea where to start xD;;;

**Comment by SilentChaos512** [comment]
I understand, my bad. Looks like the same crash. I'll see what I can come up with.

**Comment by SilentChaos512** [comment]
Hopefully the next version will not crash, or at least give some more info. I've set it to dump as much info about the problem code as possible to the log.

**Comment by BritishMindslave** [comment]
It did crash, and it did actually close my game this time. I kept the console up, but as soon as it crashed it completely erased the information I was following. LOL 
[crash-2016-10-19_10.23.02-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/539287/crash-2016-10-19_10.23.02-server.txt)

I'm going to try running a profile, adding each mod one after the other to see exactly what the conflict is. I'll let you know the results of that when I finish!
Seriously, though, thank you for helping me out with this. It's frustrating for me, yeah, but it's likely just as frustrating for you if not more. xD

**Comment by BritishMindslave** [comment]
IT'S FIXED. It had something to do with the config files!! I replaced them with new ones and now we're hunky-dory. Man I am so sorry it was such a simple solution. xD

**Comment by SilentChaos512** [comment]
Great to hear it's fixed! That last crash report actually points to a different function... and another similar config option. So something is going wrong in the config, just not sure what. Hopefully I can add some good safety checks to prevent this from happening to anyone else.
