### ISSUE TITLE
SilentLib update required

### ISSUE THREAD

**Issue by Fortist** [SilentChaos512/ScalingHealth#90]
says I need version whatever.17 of slientlib with the latest version of scaling health

**Comment by QAngelusQ** [comment]
Same message when starting the client with "ScalingHealth-1.12-1.3.12-93"

Silentlib 2.2.17 or above

**Comment by SilentChaos512** [comment]
Knew I would forget something... It's been so long since the last Lib update. It's uploaded and should be approved in a few minutes.

**Comment by SilentChaos512** [comment]
https://minecraft.curseforge.com/projects/silent-lib/files/2544872
