### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by duhadventure** [SilentChaos512/ScalingHealth#92]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.12-1.3.12-93
Silent Lib Version: 1.12-2.2.18-100

### Expected behavior

Modpack launches successfully. 

### Actual behaviour

Crashes: https://pastebin.com/HsteLTTC

### Steps to reproduce the problem

1. Try to launch modpack
2. Modpack almost launches
3. ...
4. Crash

Can provide link to private Technicpack If needed.

**Comment by SilentChaos512** [comment]
Update Scaling Health, it isn't compatible with that version of Silent Lib.
