### ISSUE TITLE
Hearts take level instead of ExpLevel

### ISSUE THREAD

**Issue by Xaikii** [SilentChaos512/ScalingHealth#96]
### Versions

Minecraft Version: 1.12,2
Scaling Health Version: 1.3.12-93
Silent Lib Version: 2.2.17-98

### Expected behavior

Hearts taking Exp worth the Levels

### Actual behaviour

Taking Levels

### Steps to reproduce the problem

1. Use a Heart

**Comment by SilentChaos512** [comment]
Not sure I follow. The way Minecraft handles XP and levels is so weird.

**Comment by Xaikii** [comment]
Yea minecraft handles it pretty wierd
Anways in the Config you said when consume a Heart you require Experiemce worth the Level, but what actually happens is that the Levels do get removed directly. 

E. g. 
You are Level 75
A Heart costs 5 Levels

Currently it removed the Levels directly so you'd end up with 70 Levels. But if the Hearts would require Experience worth the Level, the Player would be probably still 75 or 74.

**Comment by SilentChaos512** [comment]
Removing levels is intended. I guess I need to tweak the wording on that.
