### ISSUE TITLE
Crashing server with Ticking Entity error

### ISSUE THREAD

**Issue by fivestang** [SilentChaos512/ScalingHealth#97]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.13-94
Silent Lib Version: 2.2.18-100

### Expected behavior

- not crashing

### Actual behaviour

- crashing with ticking entity/no such method error :(

### Steps to reproduce the problem

1. start the server
2. log in and do things
3. ...
4. Profit (crash)

[crash-2018-03-31_22.10.29-server.txt](https://github.com/SilentChaos512/ScalingHealth/files/1866065/crash-2018-03-31_22.10.29-server.txt)

I suspect this may be an interaction with one of the other mob altering mods I have installed.  Let me know if there's anything I can do to help diagnose further.

**Comment by SilentChaos512** [comment]
Surprised I missed that one. You should be able to disable the lunar phases feature on the server as a temporary workaround.

**Comment by fivestang** [comment]
Super, seems to be working fine now, ty!
