### ISSUE TITLE
Menu Exits when trying to configure.

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/ScalingHealth#98]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.3.13
Silent Lib Version: 2.2.18

### Expected behavior

- Being able to configure the mod through the "Mod options"
 button when you open the menu.
### Actual behaviour

- Upon clicking "Config" it just closes the menu.

### Steps to reproduce the problem

1. Go into Minecraft with the mod loaded.
2. Press ESC and click "Mod Options..."
3. Locate Scaling Health.
4. Click "Config"
5. The game will just exit back into the game.

And if this is intended, and we're supposed to edit a file to configure the mod, then I suggest you change that, because I hate having to reload 68 mods whenever I change something in the config. >.<

Kind Regards,
-L0ST

**Comment by SilentChaos512** [comment]
Try deleting config/scalinghealth/main.cfg to start with a fresh file.
