### ISSUE TITLE
[Suggestion]: Damage scaled from other sources such as Drowning, Falling into the Void, etc.

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/ScalingHealth#99]
I wonder if it's even possible to add a damage scale from other damage sources like...

Drowning
Standing on Magma Blocks
Slamming into walls while flying with an Elytra
Falling into the Void
Getting shot by Projectiles such as Arrows, Blaze/Ghast Fireballs
Fall Damage
Potions of Harming
Wither Effect
Poison Effect
Lava
Burned by Fire
Starving
Suffocating in walls
Cacti *Instant Death Cacti, anyone?*

Ok... pretty much EVERYTHING that isn't just melee damage, I suppose.

As far as I know, the higher difficulties only affects Melee Damage from Mobs... at least as far as I know after having the mod installed for some time.

An example is... there's a greater risk of dying from Zombies or Zombie Pigmen due to their damage being scaled than with... say Ghasts, Blazes... unless you stand near them, standing on Magma Blocks or swimming in Lava as their damage isn't effected.

There's a mod that does this kind of thing called 'Damage Control', sure... but it's a fixed value instead of scaling alongside the difficultly.

Just wondering if it's by any chance do-able. By the way, Slime-like enemies don't seem to be affected by the damage scaling unless it's due to their different sizes.

**Comment by SilentChaos512** [comment]
I know at least some of these are doable, probably all of them. It would be a nice addition. I will probably use a multiplier for how sharply each one scales: set it to 1.0 to scale up proportional to player max health, lower for less scaling, and higher if you're feeling evil.

Glancing at the slime code, it looks like they are ignoring all attack damage modifiers. They just base damage on slime size. That one would be difficult to fix, but I could do it.

**Comment by Rongmario** [comment]
Hook into Advancements sounds more probable and much more popular if you ask me. Kinda staging your difficulty in a noticeable way (players will be more conscious about advancements more than simple numerial values about how many mobs they've killed etc.)

**Comment by SilentChaos512** [comment]
OK, got something added for next release (will probably upload tonight). It allows a scaling multiplier to be set for individual DamageSources. You can even add sources from other mods. That gives control over most things, but there's no distinction between poison and potion of harming, I think both are "magic". All vanilla damage types are in the list by default, but with scaling disabled (value is 0.0).

As for what it scales against, you can choose between max health, player difficulty, or area difficulty. For max health, it's a multiple of the starting health value in the config (if you have 100 health and starting health of 20, that's 5x). For the difficulty modes, it defaults to +4% damage per point (that means +1000% damage at 250 difficulty), but you can change that too.

All the new configs will be under player/damage in the config.

**Comment by Rongmario** [comment]
Lovely. Thank you.

**Comment by SonicX8000** [comment]
The day of getting instant-killed by walking into a Cactus has finally come. Unless something else out there did it but eh.

**Comment by Waisse** [comment]
Can you make those damage sources scaling apply to mobs too ?

**Comment by SilentChaos512** [comment]
Sure, I'll add a config to make it affect mobs.
